### ISSUE TITLE
Unable to see and edit song mode in any of the available hydrogen versions for Windows 10

### ISSUE THREAD

**Issue by pseudomoomin** [hydrogen-music/hydrogen#682] opened 2018-12-22 16:12 UTC
Hydrogen version *          : I have tried all of the available versions
Operating system + version  : Windows 10 64 bit professional
Audio driver + version      : ASIO

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

see the title

**Comment by pseudomoomin** [comment] 2018-12-22 16:14
picture of the GUI I am getting http://prntscr.com/lyccf3

**Comment by theGreatWhiteShark** [comment] 2018-12-28 21:39
This is strange. Does this happen after startup? If not, can you give a step-by-step guide to reproduce the issue.

In addition, can you run hydrogen with the command line arguments `hydrogen --verbose=DEBUG` and paste the output in here?

**Comment by trebmuh** [comment] 2019-03-28 02:19
@pseudomoomin : don't you have a menu such as:

![hydro](https://user-images.githubusercontent.com/8705846/55124913-41616180-5108-11e9-96dc-13bd3521ab62.png)

**Comment by pseudomoomin** [comment] 2019-03-28 08:25
> 
> 
> This is strange. Does this happen after startup? If not, can you give a step-by-step guide to reproduce the issue.

Yes after startup it is immediately like this.

**Comment by Olli** [comment] 2019-04-09 09:11
I have the same problem as @pseudomoomin but in Debian Linux. 
The debug output of mine is https://gist.github.com/Olli/1b26d1dc958d9348fb600416c2fe317f
I hope it helps.
For me I did build hydrogen from the source. Before that I completely uninstall it from /usr/local/ and removed the .hydrogen user files.

**Comment by theGreatWhiteShark** [comment] 2019-04-13 09:59
Hi,

@Olli, thanks to you log I was able to reproduce the issue.

The problem is the following: Somehow H2 was not properly installed on your system and the default configuration file in _/usr/[local/]/share/hydrogen/data/hydrogen.default.conf_ is not present. When starting up H2 for the first time the config file in _~/.hydrogen/hydrogen.conf_ gets initialized with some improper parameters.

Changing `<maxBars>0</maxBars>` to `<maxBars>400</maxBars>` in the _hydrogen.conf_ file should fix the issue. @pseudomoomin: I'm not perfectly sure were this file is located on Windows systems but this should solve the issue for you too.

**Comment by Olli** [comment] 2019-04-13 10:08
Hm the missing hydrogen.default.conf was something I also noticed but I thought "Never mind" ... 
I was also not able to find the default config in the sources. Shouldn't there be the file in /data of the sources?

**Comment by theGreatWhiteShark** [comment] 2019-04-13 10:20
There is a default file in the source. It resides in _/data/hydrogen.default.conf_. But when neither it nor the users config file is accessible, the default values assigned in the Peferences::Preferences() constructor will be stored instead. Since `maxBars` is not defined in there yet, `0` will be used as a fallback. I'm working on a fix so the issue will not occur in the future anymore.

**Comment by Olli** [comment] 2019-04-13 10:27
You're right. My GIT seems do not have checked it out. Dunno why.
Thx for resolving the issue :)

**Comment by theGreatWhiteShark** [comment] 2019-04-13 10:41
No problem :)

**Comment by trebmuh** [comment] 2019-04-22 16:36
@theGreatWhiteShark @Olli @pseudomoomin since it seems to be resolved with #722 (thanks @theGreatWhiteShark !), is that OK to close this issue now?

**Comment by Olli** [comment] 2019-04-22 16:42
From my point of view: yes you can close it. It's fully resolved.

**Comment by trebmuh** [comment] 2019-04-22 16:47
OK, thanks for the quick answer.

I'm closing the issue then. Feel free to reopen it or ask for reopening it if you think it's needed.

**Closed by trebmuh** 2019-04-22 16:47 UTC
Labels: Windows, bug, more info needed
