### ISSUE TITLE
Hydrogen app will not start

### ISSUE THREAD

**Issue by ALE22-0fficial** [hydrogen-music/hydrogen#1744] opened 2023-04-12 21:39 UTC
Hydrogen version: 1.2.0
Operating system + version: Mac OS X 10.13.6 High Sierra
Audio driver + version: MacOS Core Audio 4.3.0 (At least, that's what i found)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The program will not open, it closes abruptly with the following code:

```
Hydrogen 1.2.0-'a14bebe6' [Mar 31 2023]  [http://www.hydrogen-music.org]
Copyright 2002-2008 Alessandro Cominu
Copyright 2008-2023 The hydrogen development team
Hydrogen comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it under certain conditions. See the file COPYING for details.
(E) XMLDoc::read Unable to read conversion result document [/Users/x/Library/Application Support/Hydrogen/hydrogen.conf]
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Hydrogen.app/Contents/MacOS/../Frameworks/libpcre2-16.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

If somebody can explain me how to solve, i will.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[hydrogen.log](https://github.com/hydrogen-music/hydrogen/files/11216281/hydrogen.log)

**Comment by theGreatWhiteShark** [comment] 2023-04-13 17:39
Hey @ALE22-0fficial ,

Is `/Users/x/Library/Application Support/Hydrogen/hydrogen.conf` a readable file? Could you attach it?

**Comment by ALE22-0fficial** [comment] 2023-04-13 17:45
here is it!
[hydrogen.conf.zip](https://github.com/hydrogen-music/hydrogen/files/11225036/hydrogen.conf.zip)

I don't know if it's the correct one, since i downgraded to 1.1.1 after the bug upon update, so let me know if you want me to recreate the bug to get the conf file.

(p.s. you will need to unzip it, github did not let me upload the conf file as is

**Comment by theGreatWhiteShark** [comment] 2023-04-13 17:53
> here is it!
[hydrogen.conf.zip](https://github.com/hydrogen-music/hydrogen/files/11225036/hydrogen.conf.zip)

Hmmm. That one looks legit. But it was written with the 1.1.1 version of Hydrogen.

Did you upgrade using `brew` or the `.dmg` binary in the Github release? Could you do so once again and attach the config file present while Hydrogen is crashing?

**Comment by ALE22-0fficial** [comment] 2023-04-13 18:21
I used the .dmg file downloaded, since i'm absolutely trash at using GitHub clone commands.

i will attach the config file from the crash

[hydrogen.conf.zip](https://github.com/hydrogen-music/hydrogen/files/11225320/hydrogen.conf.zip)

**Comment by theGreatWhiteShark** [comment] 2023-04-13 19:23
> i will attach the config file from the crash
>
> [hydrogen.conf.zip](https://github.com/hydrogen-music/hydrogen/files/11225320/hydrogen.conf.zip)

Okay. That one is empty.

After re-reading the error you posted above I think the problem is not the Hydrogen code itself but the way we build and provide the macOS binary. This is done in an AppVeyor  macOS 10.15 image and it seems it's incompatible with your OS version.

We [set](https://github.com/hydrogen-music/hydrogen/blob/master/.appveyor.yml#L174) `MACOSX_DEPLOYMENT_TARGET` to 10.12 in our build pipeline to circumvent this problem. I also encountered `CMAKE_OSX_DEPLOYMENT_TARGET` when browsing the web for this error. But according to the [wayBackMachine](https://web.archive.org/web/20221023184037/https://www.appveyor.com/docs/macos-images-software/) macOS version is still the same as in 1.2.0-beta1.

Does this error also occur when using the [1.2.0-beta1](https://github.com/hydrogen-music/hydrogen/releases/download/1.2.0-beta1/Hydrogen-1.2.0-beta1.dmg) release?

**Comment by theGreatWhiteShark** [comment] 2023-04-13 19:39
Damn. Let's ping the expert @cme 

In the mean time you could try installing the most recent version using `brew`.

**Comment by ALE22-0fficial** [comment] 2023-04-13 19:41
could you tell me the process of installing it through `brew`? i'm not that good with coding and i don't want to cause damage to the pc, since it's not mine

**Comment by cme** [comment] 2023-04-13 19:41
The qtdeploy tool pulls in dependencies from the build environment if they're needed. Some of them don't work with older OS's and for those, we build our own. It looks like libpcre2 is now pulled in as a dependency where it wasn't before, or it has been updated.

It looks like libpcre2 is needed by libglib, needed by libgthread, but I don't see what needs libgthread... I don't see why that should be needed by hydrogen. I'll dig some more.

**Comment by cme** [comment] 2023-04-13 19:43
> Damn. Let's ping the expert @cme
> 
> In the mean time you could try installing the most recent version using `brew`.

Yeah I was just typing that reply :D

Sadly using `brew` won't help as the hydrogen package is only a cask which downloads and installs the binary release from github :/ Unless someone else has updated it, it should still point at 1.1 I think.

**Comment by ALE22-0fficial** [comment] 2023-04-13 19:43
So... what now? am i stuck with the 1.1 version or what?

**Comment by theGreatWhiteShark** [comment] 2023-04-13 19:48
> So... what now? am i stuck with the 1.1 version or what?

Just for a little while. There will be a patch release some time soon. Meanwhile it would be great if you have time to test binaries produced on our way to fix this issue.

**Comment by theGreatWhiteShark** [comment] 2023-04-13 19:51
> Sadly using brew won't help as the hydrogen package is only a cask which downloads and installs the binary release from github :/ Unless someone else has updated it, it should still point at 1.1 I think.

I did

**Comment by ALE22-0fficial** [comment] 2023-04-13 19:52
i'm trash with coding and stuff, so... is there a guide? also, this mac is not mine, is my father's, so, i would like to not break anything since i'm already scared of tampering with the MIDI ports to get a damn step sequencer working in Logic Pro X...

**Comment by cme** [comment] 2023-04-13 20:00
> The qtdeploy tool pulls in dependencies from the build environment if they're needed. Some of them don't work with older OS's and for those, we build our own. It looks like libpcre2 is now pulled in as a dependency where it wasn't before, or it has been updated.
> 
> It looks like libpcre2 is needed by libglib, needed by libgthread, but I don't see what needs libgthread... I don't see why that should be needed by hydrogen. I'll dig some more.

It's Qt that's pulling in libglib and all its components. We could probably make this work by installing a specific (older) version of Qt in the Appveyor image, I'll try that now.

**Comment by theGreatWhiteShark** [comment] 2023-04-14 06:27
> i'm trash with coding and stuff, so... is there a guide? also, this mac is not mine, is my father's, so, i would like to not break anything since i'm already scared of tampering with the MIDI ports to get a damn step sequencer working in Logic Pro X...

Don't worry. It is just about installing other .dmg files. They are extracted into folders containing Hydrogen, its resources and some computer magic. In the current 1.2.0 dmg files there are some sparks of magic missing. We'll check whether it is possible to add them in our build process. Your system won't be affected.

**Comment by ALE22-0fficial** [comment] 2023-04-26 09:20
So... what do i have to donwload?

**Comment by cme** [comment] 2023-05-06 08:49
Wow, so the number of issues I've run into in trying to produce a build that works is, frankly, hilarious. Appveyor's out-of-date image is an absolute pain, but I've managed to get round that with a few hacks but still haven't managed to produce something that coherently uses the Qt it's supposed to -- in the deployment process it copies some things from the system homebrew install rather than the Qts in the image home directory.

This *might* be the last hurdle or not, but in the meantime I've reinstalled High Sierra on an old laptop, and even though it's not supported by Homebrew, I should be able to get a build going using MacPorts. Oy vey.

**Comment by cme** [comment] 2023-05-08 20:14
Hi @ALE22-0fficial -- I've *finally* found the time to work through some version issues on my Local High Sierra build. Using macports packages on a local 10.13 machine it seems to work more or less out of the box.

I've added the DMG to the 1.2 release, would you be able to give this a whirl?

https://github.com/hydrogen-music/hydrogen/releases/download/1.2.0/Hydrogen-HighSierra.dmg

Thanks and sorry for the delay!

**Comment by ALE22-0fficial** [comment] 2023-05-08 20:23
don't worry, it was en extremely niche use case and i'm just happy you all managed to wing it 
the app seems to work nice, will update if any bugs are found

keep up the good work, guys!

**Comment by theGreatWhiteShark** [comment] 2023-07-07 07:21
I think we can close this one now. We explicitly stated macOS >= v10.14 as a requirement for our automatically generated artifacts but also provide a High Sierra version for the latest release in both the release page and the download section of our homepage.

**Closed by theGreatWhiteShark** 2023-07-07 07:21 UTC
