### ISSUE TITLE
Wrong Playback Speed before export

### ISSUE THREAD

**Issue by puenka** [hydrogen-music/hydrogen#37] opened 2012-09-02 18:44 UTC
Mac OS X 10.6.8 - Hydrogen 0.9.6-beta1

When playing a song inside the program it plays about 10 BPMs faster than the displayed BPM. Only after exporting the tempo is correct.

**Comment by thijz** [comment] 2015-08-10 08:33
hi puenka, mauser
is this ticket still valid?
can it be retested ?

grtz
Thijs

**Comment by puenka** [comment] 2015-08-10 08:36
Actually, it's been quite some time since i've been using hydrogen, so to
me it's not of importance any longer.
Am 10.08.2015 10:33 schrieb "thijs" <notifications@github.com>:

**Comment by thijz** [comment] 2015-10-08 10:45
hi Mauser
is this ticket still valid ?

**Comment by mauser** [comment] 2015-10-10 15:33
I'm closing this since i can't reproduce it any longer..

**Closed by mauser** 2015-10-10 15:33 UTC
Labels: bug, severity 1
