### ISSUE TITLE
Playback track volume slider doesnt work (always sounds max)

### ISSUE THREAD

**Issue by lukakostic** [hydrogen-music/hydrogen#1449] opened 2022-01-10 14:48 UTC
Hydrogen version *          : 1.1.1
Operating system + version  : arch linux / manjaro
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

![image](https://user-images.githubusercontent.com/41348897/148785180-22256cc5-820f-4001-96d6-e5bebad3484e.png)

Dragging the slider / fader has no effect on the volume of the playback track, its always at max volume.
Mute button works.

**Comment by theGreatWhiteShark** [comment] 2022-04-04 19:46
That's quite strange. I can't reproduce this behavior.

You tried dragging the slider left <-> right instead of up <-> down, right?

**Comment by oleastre** [comment] 2023-08-28 10:18
Same problem on version 1.2.1 on Fedora (using either Jack or pulseaudio on top of pipewire). 
I tried bothe the flatpak and a self compiled version, same result. 
Note that I also have the impression that plugins are not working neither, but that's probably another issue.

**Comment by theGreatWhiteShark** [comment] 2023-08-29 15:06
> Same problem on version 1.2.1 on Fedora (using either Jack or pulseaudio on top of pipewire).

Indeed. I can reproduce it now.

> Note that I also have the impression that plugins are not working neither, but that's probably another issue.

The UX of the plugins is unfortunately not straight forward. The effects do live in aux channels. By using the small grey rotaries you can send audio from each instrument channel to an FX channel. See http://hydrogen-music.org/documentation/manual/manual_en.html#sect.fx_rack_LADSPA

**Comment by theGreatWhiteShark** [comment] 2023-08-29 15:31
@oleastre could you check whether the bug is fixed by #1844?

**Comment by oleastre** [comment] 2023-08-30 09:14
Tested, and the patch works on my system. Thanks for the quick fix.

**Comment by theGreatWhiteShark** [comment] 2023-08-30 16:17
Closed with #1844

**Closed by theGreatWhiteShark** 2023-08-30 16:17 UTC
Labels: bug
