### ISSUE TITLE
[BUG] Change the resolution in Pattern Editor makes H2 crash

### ISSUE THREAD

**Issue by jduemes** [hydrogen-music/hydrogen#456] opened 2016-12-13 16:22 UTC
Hydrogen 1.0.0-'1297e09'
Arch Linux 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

Steps to reproduce:
Open H2, hit Ctrl+N and try to change the resolution on Pattern Editor.
What happens next is that any sign of resolution you had till now on Pattern Editor about resolution disappears. Click on the Pattern Editor area where you normally click to put a bubble and 'boom'... it crashes.

If you roll with the mouse scroll over the RES. number, it works as expected. (I've never tried mouse scroll on this matter before)

**Comment by pvint** [comment] 2016-12-13 23:56
I cannot reproduce this.

Can you try again and do the following please?

1. In a terminal run "ulimit -c unlimited" (so it can create a core dump when it crashes)
2. run hydrogen with "hydrogen -VDEBUG"
3. Reproduce the crash

If you can send the last bunch of the console output and the core file I should be able to get more info.

Thanks!
Paul

**Comment by jduemes** [comment] 2016-12-14 13:48
Hi @pvint,

I executed "ulimit -c unlimited" but there is no coredump file after running hydrogen. Anyway I attached the output of "hydrogen -VDEBUG".

It happens a 100% of the time. No exceptions.

[output.txt](https://github.com/hydrogen-music/hydrogen/files/651856/output.txt)

**Comment by trebmuh** [comment] 2017-02-27 00:54
Doesn't appear here on a fresh build from https://github.com/hydrogen-music/hydrogen/commit/ff19658563afddd96ac6e08b3ef7e809694c2a6a on Debian stable Jessie.

**Comment by jduemes** [comment] 2017-03-18 15:08
It still happens here.

$ hydrogen --version
Hydrogen 1.0.0-'40ae063a'
$ uname -a
Linux calhorda 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux

**Comment by jduemes** [comment] 2018-12-22 21:41
For me it seems it's not happening anymore. Therefore this issue can be closed.

hydrogen-git-1.0.0.beta1.r3322.538eaeb9-1

**Comment by trebmuh** [comment] 2019-03-28 01:47
Thanks for the feedback @jduemes .
I've retried from a fresh build (https://github.com/hydrogen-music/hydrogen/commit/bbeaed1a5d46414360cbce74e81fbcc0a05e26f6) and it is not happening here (Debian Stretch / LibraZiK-2).

Closing then.

**Closed by trebmuh** 2019-03-28 01:47 UTC
Labels: bug
