### ISSUE TITLE
play button stops working

### ISSUE THREAD

**Issue by zeezee90** [hydrogen-music/hydrogen#832] opened 2020-04-04 19:11 UTC
Hydrogen version *          :1.0.0 beta-2
Operating system + version  :  windows 10
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

when i plug in or out phones, the play button stops working

**Comment by mauser** [comment] 2020-04-04 20:25
Hi! 

Thanks for the report! This issue is more or less a duplicate of #778, so i will close this issue here. 
I will have a look at the problem, but this will take a while...

**Closed by mauser** 2020-04-04 20:25 UTC
Labels: Windows, duplicate
