### ISSUE TITLE
drum pattern plays short when in song playback

### ISSUE THREAD

**Issue by snakedad** [hydrogen-music/hydrogen#971] opened 2020-11-04 19:17 UTC
Hydrogen version *          :
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

< describe your issue or feature request here ** >

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by trebmuh** [comment] 2020-11-04 19:47
@snakedad we need more information. Please update you initial message.

**Comment by snakedad** [comment] 2020-11-04 21:02
one of my tracks will begin playing a pattern (that plays perfectly in pattern mode) and when it reaches the second beat restarts the pattern (when playing in song mode).  So in essence, a 4 measure pattern plays 3.25 measures.  I thought it was a BPM change issue, because it occurred later in the song just before a BPM change, but it also happens earlier in the song when no change is present.

**Comment by trebmuh** [comment] 2020-11-04 21:43
Please, feel the asked info in the your first message (hydrogen version, operating system + version, audio driver + version).

**Comment by cme** [comment] 2020-11-05 08:22
@snakedad We'll need to reproduce this in order to understand it. Is there any way that you could share the 2hsong file with us by attaching it here?

If you don't want to share your actual beats, you could maybe try taking a copy of it, and stripping out notes until the bare minimum that reproduces the issue is left?

Thanks

**Comment by snakedad** [comment] 2020-11-05 14:15
I think I may have just figured it out.  I had some fill and cymbal tag patterns occurring simultaneously that were a different measure count (ie: only 1 measure since it was just a cymbal tag or a short fill), and it seems like the program was trying to satisfy both durations of patterns.  instead of playing the short pattern aligned to the longer pattern, it shortened the longer pattern.

i corrected it by making ALL patterns the same number of beats and measures.

**Comment by trebmuh** [comment] 2020-11-05 16:28
It is a known limitation of Hydrogen.

**Comment by cme** [comment] 2020-11-06 21:00
The Song Editor GUI probably ought to provide some feedback on that, at least.

**Comment by trebmuh** [comment] 2020-11-06 22:01
#691 would probably be something great to be worked on.
@cme: do you know someone with coding skills, hydrogen interest, and ability to work with Hydrogen current codebase?

_(/me whistle :eyes: )_

**Comment by cme** [comment] 2020-11-06 22:58
> #691 would probably be something great to be worked on.

Hmm. I'm not convinced that's the right way to go. 

Changing the size of patterns shown in the song editor grid works for cases where pattern lengths have a common denominator, but fails for tunes where time signatures change part way through. Eg from a pattern length of 8 to pattern length of 15 (yes, that's an important use case ;) 

Some sort of flexible layout would be needed to represent it visually and would be a major reworking of the song editor, and the representation in the core would need to change to support it too.

**Comment by cme** [comment] 2020-11-08 01:35
Currently the behaviour of Hydrogen when there's a length mismatch is to consider the group's length to be the length of the "first" pattern in the group (which I think might just be the first pattern the user clicked to make active) which means an almost arbitrary choice between truncating the pattern, or playing the longer pattern all the way through. 

So, as a counter-proposal, I would like to suggest:
  - defining the behaviour as taking the longest duration (easy core change) 
  - when multiple length patterns are active in a group (column in song editor), the shorter patterns should render as narrower rectangles.

This makes the *appearance* of the song editor consistent with the behaviour of the song, which should help a user understand what's happening.

It's also a halfway point to the more substantial core change of perhaps looping the shorter pattern instead.

**Comment by theGreatWhiteShark** [comment] 2020-11-08 21:59
How would a smaller pattern look like? Maybe like one of these? (or maybe even a different color)
![smaller_pattern](https://user-images.githubusercontent.com/14164547/98485108-3d6a5080-2214-11eb-9070-afc376d673ca.png)

> It's also a halfway point to the more substantial core change of perhaps looping the shorter pattern instead.

And in the 15/8 situation the shorter pattern would be played back 1.5 times? Maybe this could be optional per overall pattern

**Comment by cme** [comment] 2020-11-15 22:03
I was thinking that representing the shorter patterns with a full-height but half-width rectangle (or rather, proportionally sized). That would extend naturally to subdivided rectangles for repeated patterns. 

Also, agreed, looping shorter patterns would definitely have to be an option, and off by default I think.

**Comment by theGreatWhiteShark** [comment] 2020-11-16 07:57
Ah, nice. Encoding information about the length and whether the shorter pattern is loop in its visual representation this way is a good idea! I like it.

**Comment by cme** [comment] 2020-11-16 21:14
The result looks a little like this at the moment:

![image](https://user-images.githubusercontent.com/768466/99308868-7f1c7c00-2850-11eb-9b16-0b785553ddb0.png)

It's not *entirely* obvious what's happening just by looking, but when watching the playhead pass over the pattern editor while playing the song, I think it communicates what's going on quite well.

**Comment by snakedad** [comment] 2020-11-18 17:46
i just want to say, thank you all for looking into this and discussing / attempting solutions.  it's great to see a team trying to resolve an issue for a user.

**Comment by cme** [comment] 2020-11-19 16:18
@snakedad do you think the above visual representation would have been enough for you to figure out what Hydrogen was doing if you'd seen it in the Song Editor while editing your sequence?

**Comment by cme** [comment] 2020-11-28 21:10
Closing as #984 is on master, aiming for release with 1.1.

**Closed by cme** 2020-11-28 21:10 UTC
