### ISSUE TITLE
Hydrogen Won't Start - Runtime Error (windows 10)

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#588] opened 2018-04-19 09:02 UTC
Hydrogen version *          : 1.0.0-beta1
Operating system + version  : windows 10
Audio driver + version      : not relevant here

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

See http://hydrogen.popez.org/hcms/node/18922

**Comment by phuzzyday** [comment] 2018-05-08 16:59
Hi!  Just tried for the first time, newest Windows.  Logo shows up, then nothing.  how can I help?  Both 1.0 64bit and .9.7 win32, same.

**Comment by mikotoiii** [comment] 2018-05-08 17:18
As the main Windows guy, I have tried a lot to reproduce this error but
can't seem to. I fairly frequently change my hydrogen version to test
various things, and to test new version compatibility, etc.

I would try completely removing your Hydrogen from add/remove programs,
then moving the folder in C:\Program Files (x86)\Hydrogen for 32-bit
installs, and C:\Program Files\Hydrogen for 64 bit installs to the root of
the drive C:\ then check your C:\Users\username\Documents folder for a
folder named hydrogen and rename it. Also if you're moving from the 32 bit
version of Hydrogen 0.9.6 or 0.9.7 to the 64 bit version of 1.0.0-beta1, I
would make sure that those folders are renamed/moved from the Program Files
(x86) directory to ensure that there are no conflicts.

Once those steps are complete, reinstall the version of hydrogen you want.

Note: You don't just want to delete the folders in case there's saved songs
or drumkits that you want to restore after the fact. Currently the drumkit
servers are down, so unfortunately you can't just re-download the drumkits.

Steve

**Comment by phuzzyday** [comment] 2018-05-08 17:28
Not sure if any of this helps...  but found this stuff while removing everything..  

Version=1
EventType=APPCRASH
EventTime=131702708176660538
ReportType=2
Consent=1
UploadTime=131702729295647304
ReportStatus=100
ReportIdentifier=0ef61447-ffcc-43a2-a676-5725f08257a7
IntegratorReportIdentifier=e3034ad3-9e08-4a56-b479-bd08eeb23af0
Wow64Host=34404
NsAppName=hydrogen.exe
AppSessionGuid=0000482c-0001-0009-9976-9d4feae6d301
TargetAppId=W:00065fa0a7992b6a2168f9ac5bc67f13d2540000ffff!00000958efab9a2af28d82cc4c33309fd51d068ccee1!hydrogen.exe
TargetAppVer=2018//03//16:12:06:07!2a520a!hydrogen.exe
BootId=4294967295
TargetAsId=649
UserImpactVector=3146544
IsFatal=1
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=hydrogen.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5aabb32f
Sig[3].Name=Fault Module Name
Sig[3].Value=libportaudio-2.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=588db2e4
Sig[6].Name=Exception Code
Sig[6].Value=40000015
Sig[7].Name=Exception Offset
Sig[7].Value=000000000001f282
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.17134.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=4105
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=ecf8
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=ecf835fe6dafb8b2c1ab19b05eff12e6
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=e786
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=e7868e846c517f9322aecc8afe30836d
UI[2]=C:\Program Files\Hydrogen\hydrogen.exe
LoadedModule[0]=C:\Program Files\Hydrogen\hydrogen.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Program Files\AVAST Software\Avast\x64\aswhooka.dll
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\System32\USER32.dll
LoadedModule[8]=C:\WINDOWS\System32\win32u.dll
LoadedModule[9]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[10]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[11]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[12]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[13]=C:\Program Files\Hydrogen\libhydrogen-core-1.0.0.dll
LoadedModule[14]=C:\Program Files\Hydrogen\libarchive-13.dll
LoadedModule[15]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[16]=C:\WINDOWS\System32\sechost.dll
LoadedModule[17]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[18]=C:\Program Files\Hydrogen\libgcc_s_seh-1.dll
LoadedModule[19]=C:\Program Files\Hydrogen\Qt5Core.dll
LoadedModule[20]=C:\WINDOWS\System32\ole32.dll
LoadedModule[21]=C:\WINDOWS\System32\combase.dll
LoadedModule[22]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[23]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[24]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[25]=C:\WINDOWS\System32\shcore.dll
LoadedModule[26]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[27]=C:\WINDOWS\System32\shlwapi.dll
LoadedModule[28]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[29]=C:\WINDOWS\System32\profapi.dll
LoadedModule[30]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[31]=C:\WINDOWS\System32\FLTLIB.DLL
LoadedModule[32]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[33]=C:\Program Files\Hydrogen\Qt5Network.dll
LoadedModule[34]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[35]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[36]=C:\Program Files\Hydrogen\Qt5Xml.dll
LoadedModule[37]=C:\Program Files\Hydrogen\libportaudio-2.dll
LoadedModule[38]=C:\WINDOWS\System32\SETUPAPI.dll
LoadedModule[39]=C:\Program Files\Hydrogen\libwinpthread-1.dll
LoadedModule[40]=C:\Program Files\Hydrogen\libsndfile-1.dll
LoadedModule[41]=C:\Program Files\Hydrogen\Qt5XmlPatterns.dll
LoadedModule[42]=C:\Program Files\Hydrogen\libportmidi.dll
LoadedModule[43]=C:\Program Files\Hydrogen\libbz2.dll
LoadedModule[44]=C:\Program Files\Hydrogen\libiconv-2.dll
LoadedModule[45]=C:\Program Files\Hydrogen\liblzma-5.dll
LoadedModule[46]=C:\Program Files\Hydrogen\liblzo2-2.dll
LoadedModule[47]=C:\Program Files\Hydrogen\libnettle-6-2.dll
LoadedModule[48]=C:\Program Files\Hydrogen\zlib1.dll
LoadedModule[49]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[50]=C:\Program Files\Hydrogen\libpcre16-0.dll
LoadedModule[51]=C:\Program Files\Hydrogen\LIBEAY32.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[53]=C:\WINDOWS\System32\NSI.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[55]=C:\Program Files\Hydrogen\SSLEAY32.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[57]=C:\Program Files\Hydrogen\libFLAC-8.dll
LoadedModule[58]=C:\Program Files\Hydrogen\libvorbis-0.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[60]=C:\Program Files\Hydrogen\libstdc++-6.dll
LoadedModule[61]=C:\Program Files\Hydrogen\Qt5Gui.dll
LoadedModule[62]=C:\Program Files\Hydrogen\Qt5Widgets.dll
LoadedModule[63]=C:\Program Files\Hydrogen\libxml2-2.dll
LoadedModule[64]=C:\Program Files\Hydrogen\libogg-0.dll
LoadedModule[65]=C:\Program Files\Hydrogen\libvorbisenc-2.dll
LoadedModule[66]=C:\Program Files\Hydrogen\libharfbuzz-0.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\OPENGL32.dll
LoadedModule[68]=C:\Program Files\Hydrogen\libpng16-16.dll
LoadedModule[69]=C:\Program Files\Hydrogen\libfreetype-6.dll
LoadedModule[70]=C:\Program Files\Hydrogen\libglib-2.0-0.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\GLU32.dll
LoadedModule[72]=C:\Program Files\Hydrogen\libintl-8.dll
LoadedModule[73]=C:\Program Files\Hydrogen\libpcre-1.dll
LoadedModule[74]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[75]=C:\Program Files\Hydrogen\platforms\qwindows.dll
LoadedModule[76]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[77]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[78]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[79]=C:\WINDOWS\system32\userenv.dll
LoadedModule[80]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[81]=C:\WINDOWS\System32\TextInputFramework.dll
LoadedModule[82]=C:\WINDOWS\System32\CoreUIComponents.dll
LoadedModule[83]=C:\WINDOWS\System32\CoreMessaging.dll
LoadedModule[84]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[85]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[86]=C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
LoadedModule[87]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[88]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[89]=C:\WINDOWS\SYSTEM32\wdmaud.drv
LoadedModule[90]=C:\WINDOWS\SYSTEM32\ksuser.dll
LoadedModule[91]=C:\WINDOWS\SYSTEM32\AVRT.dll
LoadedModule[92]=C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
LoadedModule[93]=C:\WINDOWS\SYSTEM32\msacm32.drv
LoadedModule[94]=C:\WINDOWS\SYSTEM32\MSACM32.dll
LoadedModule[95]=C:\WINDOWS\SYSTEM32\midimap.dll
LoadedModule[96]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[97]=C:\WINDOWS\SYSTEM32\dsound.dll
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=17134
OsInfo[3].Key=ubr
OsInfo[3].Value=1
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=39
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=11200
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.1.17134.0-11.0.47
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=16340
OsInfo[19].Key=svolsz
OsInfo[19].Value=222
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=180410
OsInfo[22].Key=bldtm
OsInfo[22].Value=1804
OsInfo[23].Key=bldbrch
OsInfo[23].Value=rs4_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.17134.1.amd64fre.rs4_release.180410-1804
OsInfo[30].Key=buildflightid
OsInfo[30].Value=b61bd23c-20d3-47e0-bfdd-98f9db7c802b
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=FX:10F3324D,FX:30F36D18
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
File[0].CabName=WERInternalMetadata.xml
File[0].Path=WERBE3A.tmp.WERInternalMetadata.xml
File[0].Flags=327682
File[0].Type=5
File[0].Original.Path=\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBE3A.tmp.WERInternalMetadata.xml
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=hydrogen.exe
AppPath=C:\Program Files\Hydrogen\hydrogen.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=83B3A84719A615F0D90E94EA9FCA93A4
MetadataHash=318183737

**Comment by phuzzyday** [comment] 2018-05-08 17:41
Still happening.  I'm going to try my other PC with same windows.
I don't think I've ever used it before, so this is all fresh.  (I did find an old file, so I might have tried it briefly a long time ago, or not.)

**Comment by jeremyz** [comment] 2018-05-12 10:35
#598

**Comment by jeremyz** [comment] 2018-05-14 16:42
@phuzzyday, can you confirm it's fixed now.
If so, you can close that issue.

**Comment by mauser** [comment] 2020-03-19 21:27
Closed, since no feedback has been given.

**Closed by mauser** 2020-03-19 21:27 UTC
Labels: Windows, bug, more info needed
