### ISSUE TITLE
'Can't save song'

### ISSUE THREAD

**Issue by beatbag** [hydrogen-music/hydrogen#352] opened 2016-01-29 22:37 UTC
Wrote some killer patterns, but could not save the song.

**Comment by pvint** [comment] 2016-01-29 23:44
Can you provide more info?
ie:
- What version of Hydrogen
- What OS
- What happened when you tried to save the song? (ie: error message etc)
- Can you reproduce the issue?

Thx
Paul

**Comment by trebmuh** [comment] 2016-02-29 19:29
@beatbag ping

**Comment by mauser** [comment] 2016-03-25 22:33
Hi,

I'm closing now this ticket due to the lack of information...

**Comment by Josbourne2** [comment] 2019-01-24 16:44
I can reproduce, and I know the cause. In windows the default setting is to save the song to the install directory. Often this is write protected. In the save dialog, choose your home folder. Then saving will be ok.

**Comment by theGreatWhiteShark** [comment] 2022-02-07 08:51
This should be fixed with #1473

**Closed by theGreatWhiteShark** 2022-02-07 08:51 UTC
Labels: Windows
