### ISSUE TITLE
adding instrument to pattern causes distorted sound

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#235] opened 2015-03-05 11:39 UTC
load a drumkit
drag an instruments form the sound library onto the pattern
in the 'would you like to merge or add the banks?' > select Add
the instrument is now added 

in the pattern editor click the newly added instrument
> sound is distorted and it seems that 2 samples are now mixed (only on left channel ??)

**Comment by thijz** [comment] 2015-03-05 11:47
sometimes hydrogen simply crashes with this message : 

Error XSDError in file:///home/tvanseve/Git/Hydrogen/Mainrepo/hydrogen/data/drumkits/GMkit/drumkit.xml, at line 11, column 17: Element {http://www.hydrogen-music.org/drumkit}instrumentList is not defined in this scope.
Error XSDError in file:///home/tvanseve/Git/Hydrogen/Mainrepo/hydrogen/data/drumkits/GMkit/drumkit.xml, at line 11, column 17: Element {http://www.hydrogen-music.org/drumkit}instrumentList is not defined in this scope.
hydrogen: /home/tvanseve/Git/Hydrogen/Mainrepo/hydrogen/src/core/src/basics/instrument_list.cpp:202: void H2Core::InstrumentList::move(int, int): Assertion `idx_b >= 0 && idx_b < __instruments.size()' failed.
Aborted (core dumped)

**Comment by Be-OK** [comment] 2015-05-09 11:15
V 0.9.7-1a9afef OS Linux kxstudio 3.13.0-52-lowlatency #86-Ubuntu SMP PREEMPT  x86_64 U/Linux
That bug happens here to, you hear the sound and than a buzzer/distortion ,this happens with all dragged instruments.

**Comment by blablack** [comment] 2015-05-22 12:10
I noticed this as well, and it is most probably due to my code to add multibank per intrument.

I'll try to have a look at this issue ASAP.

**Comment by blablack** [comment] 2015-05-24 15:45
Patch below solves the issue for me:

```
diff --git a/src/core/src/basics/instrument.cpp b/src/core/src/basics/instrument.cpp
index 85d5f82..67ef726 100644
--- a/src/core/src/basics/instrument.cpp
+++ b/src/core/src/basics/instrument.cpp
@@ -144,7 +144,7 @@ void Instrument::load_from( Drumkit* drumkit, Instrument* instrument, bool is_li
             if( src_layer==0 ) {
                 if ( is_live )
                     AudioEngine::get_instance()->lock( RIGHT_HERE );
-                my_component->set_layer( NULL, i );
+				my_component->set_layer( NULL, i );
                 if ( is_live )
                     AudioEngine::get_instance()->unlock();
             } else {
diff --git a/src/core/src/basics/instrument_component.cpp b/src/core/src/basics/instrument_component.cpp
index 01b68ce..038377f 100644
--- a/src/core/src/basics/instrument_component.cpp
+++ b/src/core/src/basics/instrument_component.cpp
@@ -57,9 +57,9 @@ InstrumentComponent::InstrumentComponent( InstrumentComponent* other )
 	for ( int i=0; i<MAX_LAYERS; i++ ) {
 		InstrumentLayer* other_layer = other->get_layer( i );
 		if ( other_layer ) {
-			__layers[i] = new InstrumentLayer( other_layer );
+			__layers[i] = new InstrumentLayer( other_layer, other_layer->get_sample() );
 		} else {
-			__layers[i] = 0;
+			__layers[i] = NULL;
 		}
 	}
 }
```

Thing is, I don't know why I cannot reproduce the issue anymore with these changes.

Coud you guys confirm it fixes the problem on your side?

**Comment by thijz** [comment] 2015-05-26 11:08
Hi blablack
tried to apply the patch but got this error : (tried to apply it to the most recent version of your branch)

tvanseve@tvanseve-ThinkPad-W530:~/Git/Hydrogen/multilayer/test/hydrogen$ git apply --stat patch
 src/core/src/basics/instrument.cpp           |    2 +-
 src/core/src/basics/instrument_component.cpp |    4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

tvanseve@tvanseve-ThinkPad-W530:~/Git/Hydrogen/multilayer/test/hydrogen$ git apply --check patch
__error: patch failed: src/core/src/basics/instrument_component.cpp:57
error: src/core/src/basics/instrument_component.cpp: patch does not apply__


next i added the changes manually (looks like the second part of the patch doesnt really do anything) 
to /src/core/src/basics/instrument_component.cpp and that didnt do anything at first (still bad)

but to make sure tat i started from a clean situation i cloned your repo again in an other location, applied the patch (manually), build hydrogen, and now the issue seems to be fixed ??
maybe it was just a typo, who knows ...

**Comment by blablack** [comment] 2015-05-26 12:03
Hi,

Weird about the patch, it was created from a clean clone.

It would be great if someone else can confirm it fixes the problem.

BTW, I don't know why the patch fixes the problem. I believe the pointer to
the Sample were not kept when drag/dropping instruments which is why the
sample was corrupted.
But the patch only changes where the new Sample instances are declared, it
doesn't change where they are stored. It shouldn't fix the problem but
somehow still does (again, awaiting confirmation I guess).

**Comment by thijz** [comment] 2015-08-07 11:19
could not reproduce this on my main pc
yesterday i did hear it on an other laptop, but i need to verify if that laptop is running the most recent version > i'll report back

**Comment by mauser** [comment] 2015-08-07 13:28
This problem should be fixed now..

**Comment by mauser** [comment] 2015-08-31 17:46
@thijz : Can you re-test this so that we can close the ticket?

**Comment by mauser** [comment] 2016-03-26 15:58
@thijz : Any news on this?

**Comment by thijz** [comment] 2016-07-12 21:05
will retest as soon as i get my build env set up

**Comment by trebmuh** [comment] 2016-08-09 12:04
From a fresh git build (ie: https://github.com/hydrogen-music/hydrogen/commit/d7dacfedf73ede1af24ddedf260cfce5ca77df18), I can't reproduce this bug.

That said, I'm not 100% sure of the way of testing it so I made this 30sec screencast : http://download.tuxfamily.org/librazik/volatile/hydrogen-issue235.mp4

Hope that helps.

**Comment by mauser** [comment] 2016-08-18 21:08
I'm closing this ticket now since there seems to be no way to reproduce the behaviour. @thijz , just re-open it if you see this problem again..

**Closed by mauser** 2016-08-18 21:08 UTC
Labels: bug, severity 1

**Comment by trebmuh** [comment] 2016-08-18 21:56
@thijz : before I remove the screencast, could you please tell is I'm trying the right thing in it?
