### ISSUE TITLE
build error with liblo-0.31

### ISSUE THREAD

**Issue by Tarot67** [hydrogen-music/hydrogen#1256] opened 2021-04-28 20:24 UTC
Hydrogen version 1.1.0          :
slackware + role-and-release or slackware64-current  : 
alsa-1.2.4 and jack2-1.9.18  : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The problem not from include because lo_ccp.h contain effectively this class "ServerThread"
there some problem to build hydrogen with liblo-0.31. There are a error with 

hydrogen/src/core/OscServer.cpp:892:72: error: no matching function for call to ‘lo::ServerThread::add_method(std::nullptr_t, std::nullptr_t, int (&)(const char*, const char*, lo_arg**, int, void*, void*), std::nullptr_t)’
  892 |  m_pServerThread->add_method(nullptr, nullptr, generic_handler, nullptr);
      |                                                                        ^

gcc-10.3.0 say: 

 m_pServerThread->add_method(nullptr, nullptr, generic_handler, nullptr);
      |                                                                        ^
      |                                                                        |
      |                                                                        int (*)(const char*, const char*, lo_arg**, int, void*, void*)
In file included from /compile/hydrogen/src/core/OscServer.cpp:34:

it's probablly need more arguments something like that.

The complet error is here:
[  2%] Building CXX object src/core/CMakeFiles/hydrogen-core-1.1.0.dir/OscServer.cpp.o
/compile/hydrogen/src/core/OscServer.cpp: In member function ‘bool OscServer::init()’:
/compile/hydrogen/src/core/OscServer.cpp:892:72: error: no matching function for call to ‘lo::ServerThread::add_method(std::nullptr_t, std::nullptr_t, int (&)(const char*, const char*, lo_arg**, int, void*, void*), std::nullptr_t)’
  892 |  m_pServerThread->add_method(nullptr, nullptr, generic_handler, nullptr);
      |                                                                        ^
In file included from /compile/hydrogen/src/core/OscServer.cpp:34:
/usr/include/lo/lo_cpp.h:581:16: note: candidate: ‘lo::Method lo::Server::add_method(const lo::string_type&, const lo::string_type&, lo_method_handler, void*) const’ (near match)
  581 |         Method add_method(const string_type &path, const string_type &types,
      |                ^~~~~~~~~~
/usr/include/lo/lo_cpp.h:581:16: note:   conversion of argument 3 would be ill-formed:
/compile/hydrogen/src/core/OscServer.cpp:892:72: error: invalid conversion from ‘int (*)(const char*, const char*, lo_arg**, int, void*, void*)’ to ‘lo_method_handler’ {aka ‘int (*)(const char*, const char*, lo_arg**, int, lo_message_*, void*)’} [-fpermissive]
  892 |  m_pServerThread->add_method(nullptr, nullptr, generic_handler, nullptr);
      |                                                                        ^
      |                                                                        |
      |                                                                        int (*)(const char*, const char*, lo_arg**, int, void*, void*)
In file included from /compile/hydrogen/src/core/OscServer.cpp:34:
/usr/include/lo/lo_cpp.h:589:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (char*)(0), (lo_arg**)(0), (int)(0))), int>::value, void>::type*)’
  589 |         LO_ADD_METHOD( (const char*, const char*, lo_arg**, int),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:589:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (char*)(0), (lo_arg**)(0), (int)(0))), int>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:589:9: error: too few arguments to function
  589 |         LO_ADD_METHOD( (const char*, const char*, lo_arg**, int),
      |         ^
/usr/include/lo/lo_cpp.h:589:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (char*)(0), (lo_arg**)(0), (int)(0))), void>::value, void>::type*)’
  589 |         LO_ADD_METHOD( (const char*, const char*, lo_arg**, int),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:589:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (char*)(0), (lo_arg**)(0), (int)(0))), void>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:589:9: error: too few arguments to function
  589 |         LO_ADD_METHOD( (const char*, const char*, lo_arg**, int),
      |         ^
/usr/include/lo/lo_cpp.h:595:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo_arg**)(0), (int)(0))), int>::value, void>::type*)’
  595 |         LO_ADD_METHOD( (const char*, lo_arg**, int),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:595:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo_arg**)(0), (int)(0))), int>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:595:9: error: cannot convert ‘lo_arg**’ to ‘const char*’ in argument passing
  595 |         LO_ADD_METHOD( (const char*, lo_arg**, int),
      |         ^
/usr/include/lo/lo_cpp.h:595:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo_arg**)(0), (int)(0))), void>::value, void>::type*)’
  595 |         LO_ADD_METHOD( (const char*, lo_arg**, int),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:595:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo_arg**)(0), (int)(0))), void>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:595:9: error: cannot convert ‘lo_arg**’ to ‘const char*’ in argument passing
  595 |         LO_ADD_METHOD( (const char*, lo_arg**, int),
      |         ^
/usr/include/lo/lo_cpp.h:598:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo_arg**)(0), (int)(0), (lo::Message)((lo_message_*)(0)))), int>::value, void>::type*)’
  598 |         LO_ADD_METHOD( (const char*, lo_arg**, int, const Message&),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:598:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo_arg**)(0), (int)(0), (lo::Message)((lo_message_*)(0)))), int>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:598:9: error: cannot convert ‘lo_arg**’ to ‘const char*’ in argument passing
  598 |         LO_ADD_METHOD( (const char*, lo_arg**, int, const Message&),
      |         ^
/usr/include/lo/lo_cpp.h:598:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo_arg**)(0), (int)(0), (lo::Message)((lo_message_*)(0)))), void>::value, void>::type*)’
  598 |         LO_ADD_METHOD( (const char*, lo_arg**, int, const Message&),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:598:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo_arg**)(0), (int)(0), (lo::Message)((lo_message_*)(0)))), void>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:598:9: error: cannot convert ‘lo_arg**’ to ‘const char*’ in argument passing
  598 |         LO_ADD_METHOD( (const char*, lo_arg**, int, const Message&),
      |         ^
/usr/include/lo/lo_cpp.h:601:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo::Message)((lo_message_*)(0)))), int>::value, void>::type*)’
  601 |         LO_ADD_METHOD( (const char*, const Message&),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:601:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo::Message)((lo_message_*)(0)))), int>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:601:9: error: cannot convert ‘lo::Message’ to ‘const char*’ in argument passing
  601 |         LO_ADD_METHOD( (const char*, const Message&),
      |         ^~~~~~~~~~~~~
      |         |
      |         lo::Message
/usr/include/lo/lo_cpp.h:601:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo::Message)((lo_message_*)(0)))), void>::value, void>::type*)’
  601 |         LO_ADD_METHOD( (const char*, const Message&),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:601:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((char*)(0), (lo::Message)((lo_message_*)(0)))), void>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:601:9: error: cannot convert ‘lo::Message’ to ‘const char*’ in argument passing
  601 |         LO_ADD_METHOD( (const char*, const Message&),
      |         ^~~~~~~~~~~~~
      |         |
      |         lo::Message
/usr/include/lo/lo_cpp.h:604:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo_arg**)(0), (int)(0))), int>::value, void>::type*)’
  604 |         LO_ADD_METHOD( (lo_arg**, int), ((lo_arg**)0, (int)0), (argv, argc) )
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:604:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo_arg**)(0), (int)(0))), int>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:604:9: error: cannot convert ‘lo_arg**’ to ‘const char*’ in argument passing
  604 |         LO_ADD_METHOD( (lo_arg**, int), ((lo_arg**)0, (int)0), (argv, argc) )
      |         ^
/usr/include/lo/lo_cpp.h:604:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo_arg**)(0), (int)(0))), void>::value, void>::type*)’
  604 |         LO_ADD_METHOD( (lo_arg**, int), ((lo_arg**)0, (int)0), (argv, argc) )
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:604:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo_arg**)(0), (int)(0))), void>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:604:9: error: cannot convert ‘lo_arg**’ to ‘const char*’ in argument passing
  604 |         LO_ADD_METHOD( (lo_arg**, int), ((lo_arg**)0, (int)0), (argv, argc) )
      |         ^
/usr/include/lo/lo_cpp.h:605:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo_arg**)(0), (int)(0), (lo::Message)((lo_message_*)(0)))), int>::value, void>::type*)’
  605 |         LO_ADD_METHOD( (lo_arg**, int, const Message& ),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:605:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo_arg**)(0), (int)(0), (lo::Message)((lo_message_*)(0)))), int>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:605:9: error: cannot convert ‘lo_arg**’ to ‘const char*’ in argument passing
  605 |         LO_ADD_METHOD( (lo_arg**, int, const Message& ),
      |         ^
/usr/include/lo/lo_cpp.h:605:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo_arg**)(0), (int)(0), (lo::Message)((lo_message_*)(0)))), void>::value, void>::type*)’
  605 |         LO_ADD_METHOD( (lo_arg**, int, const Message& ),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:605:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo_arg**)(0), (int)(0), (lo::Message)((lo_message_*)(0)))), void>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:605:9: error: cannot convert ‘lo_arg**’ to ‘const char*’ in argument passing
  605 |         LO_ADD_METHOD( (lo_arg**, int, const Message& ),
      |         ^
/usr/include/lo/lo_cpp.h:608:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo::Message)((lo_message_*)(0)))), int>::value, void>::type*)’
  608 |         LO_ADD_METHOD( (const Message&),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:608:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo::Message)((lo_message_*)(0)))), int>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:608:9: error: cannot convert ‘lo::Message’ to ‘const char*’ in argument passing
  608 |         LO_ADD_METHOD( (const Message&),
      |         ^~~~~~~~~~~~~
      |         |
      |         lo::Message
/usr/include/lo/lo_cpp.h:608:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo::Message)((lo_message_*)(0)))), void>::value, void>::type*)’
  608 |         LO_ADD_METHOD( (const Message&),
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:608:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h((lo::Message)((lo_message_*)(0)))), void>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:608:9: error: cannot convert ‘lo::Message’ to ‘const char*’ in argument passing
  608 |         LO_ADD_METHOD( (const Message&),
      |         ^~~~~~~~~~~~~
      |         |
      |         lo::Message
/usr/include/lo/lo_cpp.h:611:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h()), int>::value, void>::type*)’
  611 |         LO_ADD_METHOD( (), (), () );
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:611:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h()), int>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:611:9: error: too few arguments to function
  611 |         LO_ADD_METHOD( (), (), () );
      |         ^
/usr/include/lo/lo_cpp.h:611:9: note: candidate: ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h()), void>::value, void>::type*)’
  611 |         LO_ADD_METHOD( (), (), () );
      |         ^~~~~~~~~~~~~
/usr/include/lo/lo_cpp.h:611:9: note:   template argument deduction/substitution failed:
/usr/include/lo/lo_cpp.h: In substitution of ‘template<class H> lo::Method lo::Server::add_method(lo::string_type, lo::string_type, H&&, typename std::enable_if<std::is_same<decltype (h()), void>::value, void>::type*) [with H = int (&)(const char*, const char*, lo_arg**, int, void*, void*)]’:
/compile/hydrogen/src/core/OscServer.cpp:892:72:   required from here
/usr/include/lo/lo_cpp.h:611:9: error: too few arguments to function
  611 |         LO_ADD_METHOD( (), (), () );
      |         ^
make[2]: *** [src/core/CMakeFiles/hydrogen-core-1.1.0.dir/build.make:776: src/core/CMakeFiles/hydrogen-core-1.1.0.dir/OscServer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:302: src/core/CMakeFiles/hydrogen-core-1.1.0.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
bash-5.1$ 

Thank!

regards,
JeanSeb
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by theGreatWhiteShark** [comment] 2021-04-30 14:55
I can't reproduce this with liblo 0.31 found at https://github.com/radarsat1/liblo/releases/tag/0.31 . Could you tell which exact commit in `liblo` and `hydrogen` you are on?

**Comment by theGreatWhiteShark** [comment] 2021-09-29 17:15
Fixed in #1333 . In the end a newer version of `gcc` caused this problem.

**Closed by theGreatWhiteShark** 2021-09-29 17:15 UTC
Labels: more info needed

**Comment by Tarot67** [comment] 2021-09-29 19:35
Yes it's done hydrogen work! Great!

thank you
