### ISSUE TITLE
plugin browser bug

### ISSUE THREAD

**Issue by Reaper10** [hydrogen-music/hydrogen#304] opened 2015-09-27 00:03 UTC
I have windows 10 and I'm using hydrogen 0.9.7 I tried to add a fx plugin to the mixer I clicked edit and the plugin browser window didn't open.

**Comment by mauser** [comment] 2016-01-07 21:50
Hi, i'm closing this issue since it is a duplicate of #341 (and #341 has more comments..).

**Closed by mauser** 2016-01-07 21:50 UTC
Labels: bug, Windows
