### ISSUE TITLE
export to wave adds long dead time !

### ISSUE THREAD

**Issue by fhenryco** [hydrogen-music/hydrogen#1853] opened 2023-10-02 14:24 UTC
Hydrogen version *          :1.2.0 
Operating system + version  : Mageia 9
Audio driver + version      :  pipewire on pulseaudio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

My distribution (mageia) upgrade came with version 1.2.0 of hydrogen and (apparently) a new bug when exporting to a wave file: it adds a dead time (several measures) at the end so the wave file is not anymore the song i can hear in hydrogen and i cant use it as a loop! For instance it is twice longer than it should in the attached wave file. Got the same behaviour with 1.2.2 Appimage ! Got the issue even with default song opening in Hydrogen (so not mine)

**Comment by theGreatWhiteShark** [comment] 2023-10-02 17:28
Hey @fhenryco ,

Hydrogen versions prior to 1.2.0 had a bug due to which samples did not ring out but were cut at the end of the song. This has been fixed and local testing (using the sample you uploaded on SourceForge) did not showed anything strange.

Could it be that you are working with long samples and the dead time you are referring to is your samples fading out?

You can make Hydrogen cut the samples at the end of a pattern yourself by manually setting the length of a note (right click and dragging to the right) to the very end of the pattern.

**Comment by fhenryco** [comment] 2023-10-02 18:01
I get exactly the same issue with samples from the default hydrogen drum kit: i can reproduce the problem with just floor tom and Stick from GMRockit. But you are right that this must be related to the sample length even in this case  because if i do what you say (make Hydrogen cut the samples at the end of a pattern myself by manually setting the length of the notes) then the wave file generated stops where it should i.e. exactly at the end of the pattern.

so are you saying that i need to do that for the dozen of notes i typically have in a pattern ??!! : see the difference between my two screen shots : only a few notes and it's already getting ugly:

![Screenshot_20231002_193018](https://github.com/hydrogen-music/hydrogen/assets/20909200/199bcd4e-4b01-4365-be04-b591cf936584)
![Screenshot_20231002_195239](https://github.com/hydrogen-music/hydrogen/assets/20909200/7585564a-c94c-47d8-b4b0-951696b14eee)

In the old version of Hydrogen i did not have to set where the notes was finishing , and the wave i obtained were perfect for a loop, as if somehow the export wave tool was performing a cyclic continuation of the notes at the end to the begining of the pattern : at the end i could hear exactly  the samething when playing the pattern in loop within hydrogen and playing the generated wave file in loop.

Or did i miss something ?

**Comment by theGreatWhiteShark** [comment] 2023-10-02 19:06
> so are you saying that i need to do that for the dozen of notes i typically have in a pattern ??!! : see the difference between my two screen shots : only a few notes and it's already getting ugly:

There are two things you can do here:

1. check the "Auto-Stop Note" feature in the instrument editor for your instruments. This immediately stops sample rendering as soon as the same sample is triggered again. Now, you only have to set the length of the last note. But this will also affect the sound in a bad way as there are no overlaps anymore
2. use a stop note. It took me some time to realize how it's done because there is, unfortunately, a bug in the current release rendering the stop notes like regular ones (I'll fix it). But using <kbd>Shift</kbd> + `left click` you can add a note which stops all playback of the associated instrument.

> Or did i miss something ?

The previous version did not loop back audio to the beginning of the song but just cut the sample prematurely.

Why is the current export not working properly for loops. Hydrogen tells you the exact time a pattern ends by moving the playhead to the adjacent pattern while playback is stopped. Just click the ruler below the timeline and you will get e.g. 6.486s for four patterns and 148 bpm. This information you can use in an external tool to customize the loop range.

On the other hand, one does not need strange workarounds anymore, like an extra long final pattern containing only the final note at the very beginning.

**Comment by fhenryco** [comment] 2023-10-02 19:13
It must be something else because now even after adding stop notes at the end of the pattern:
![Screenshot_20231002_210811](https://github.com/hydrogen-music/hydrogen/assets/20909200/e1a63a61-536d-4e4f-89c1-afbf0b80885c)

the wave file has a much longer duration than expected. you can download the wave file here: 
https://www.grosfichiers.com/pZjVwGXxnvu
the pattern is repeated twice in the song that is exported to wave so that you can hear in the wave  where it should normally stop, but does not!

**Comment by fhenryco** [comment] 2023-10-02 19:24
Thank you , we probably posted almost at the same time as i did not notice your last post before posting myself

**Comment by theGreatWhiteShark** [comment] 2023-10-03 07:54
Do the two options I suggested work for your purposes or are there still some open points?

**Comment by cme** [comment] 2023-10-03 08:31
I guess it sounds like we need a "Export sample for loop" option that intentionally chops the export at the end of the last pattern?

**Comment by fhenryco** [comment] 2023-10-03 08:36
Thank you for your effort but as you can see in my last screenshot, i tried the stop notes (which are not blue but rather a little bit smaller black dots) on all instruments and yet the end of the wave file is still much beyond the stop note. I had also the auto-stop activated from the begining. So the most usefull of your proposed solution is the accurate determination of the time at the end of the pattern which i was able to successfully and quite easily apply in my daw (bitwig) to limit the clip in time so that the behaviour of the loop is All right.

**Comment by theGreatWhiteShark** [comment] 2023-10-03 10:48
>  i tried the stop notes (which are not blue but rather a little bit smaller black dots)

oh dear! Seems like I put the wrong default value. The color of the stop notes can be set in Options > Preferences > Appearance > Colors > Pattern Editor > Note Off. You can pick any color to improve their visibility. I just happen to set their default color to black too.

> on all instruments and yet the end of the wave file is still much beyond the stop note

Hmm. I can not reproduce this behavior. Could you attach the song?

> I guess it sounds like we need a "Export sample for loop" option that intentionally chops the export at the end of the last pattern?

I like that idea. It somewhat reproduces the behavior of former versions and might be quite helpful when working with simple audio players instead of proper DAWs. But then it should work as expected by @fhenryco: the fade out should be added to the beginning of the song. This way looping the export in a media player will sound exactly like looping a song/pattern within Hydrogen.

**Comment by fhenryco** [comment] 2023-10-03 21:04
Thank you. So i will probably double such patterns in the future : 6/4

**Comment by theGreatWhiteShark** [comment] 2023-10-04 16:26
> Thank you. So i will probably double such patterns in the future : 6/4

No, you don't have to. The slight increase of the pattern length is just a temporary workaround. The NoteOff notes not being picked up correctly is a bug and we are working on a fix. It will be part of version 1.2.3 of Hydrogen and I post an updated AppImage here as soon as the fixes are ready.

**Comment by theGreatWhiteShark** [comment] 2023-10-07 08:46
@fhenryco could you check whether [this AppImage](https://ci.appveyor.com/api/buildjobs/6moyy3j59i05kwxt/artifacts/Hydrogen-x86_64.AppImage) fixes your issues with the stop notes?

**Comment by fhenryco** [comment] 2023-10-07 10:48
Thought an AppImage was fully portable yet running it i get the message GLIBCXX_3.4.26 not found

**Comment by theGreatWhiteShark** [comment] 2023-10-07 11:31
> Thought an AppImage was fully portable yet running it i get the message GLIBCXX_3.4.26 not found

No, they aren't. When built on a pretty old Linux distribution they should run on most recent distributions using the same compiler (due to the forward compatibilty of `gcc` and `clang`). It's not perfect but it is already a lot.

Hmm. But I thought the 1.2.2 AppImage did run on your system. Then it's quite strange for the one linked above not to work.

I just took a look inside and compared it with the latest release AppImage. Both binaries and their associated libraries seem to require the same GLIBCXX version and 3.4.26 was required by the last release too.

To reproduce

``` bash
./Hydrogen-1.2.2-x86_64.AppImage --appimage-extract
objdump -x squashfs-root/usr/lib/libhydrogen-core-1.2.2.so | grep GLIBCXX
```

**Comment by fhenryco** [comment] 2023-10-07 12:51
The explanation is that i never run experimental things on my working distro. here i used a debian 9 VM as a sandbox. I'll try on a more recent VM distro as soon as possible.

**Comment by fhenryco** [comment] 2023-10-08 10:03
testing it in a newly created VM, it cannot find my samples which are custom wave sounds and not from any library.
How can i tell H2 the directory of my wave sounds so it can load them with the .h2song file ? (it was some work to initially  load each sound as a new instrument, can i avoid this?)

**Comment by fhenryco** [comment] 2023-10-08 13:21
and the new created instruments were not created as part of a drumkit. If now i want to create a drumkit i need to load a new one and this is replacing my own instruments .... so i apparently cant save my instruments as part of a new drumkit

**Comment by theGreatWhiteShark** [comment] 2023-10-08 18:25
>  it cannot find my samples which are custom wave sounds and not from any library.
How can i tell H2 the directory of my wave sounds so it can load them with the .h2song file ?

For samples in .h2song files you have basically two options for loading them:

1. When loading a drumkit or drag/drop instruments from other drumkits into your song the samples are taken from these drumkit folders. They are referenced in the .h2song file using the name and path of the drumkit and the plain filename of the sample.
2. When loading samples via the instrument editor Hydrogen assumes these are not part of the installed drumkits and stores absolute paths to the sample in the .h2song.

So, you can either put all your freshly added samples into drumkit using Drumkits > Save or Drumkits > Save As or ensure Hydrogen can find them at the same absolute paths.

> If now i want to create a drumkit i need to load a new one and this is replacing my own instruments .... so i apparently cant save my instruments as part of a new drumkit

When pressing Drumkits > Save the current instruments of your song replace the once in the last loaded drumkit. When using Drumkits > Save As you can create a fresh kit without overwriting the one you loaded.

**Comment by fhenryco** [comment] 2023-10-09 07:57
I tested successfully the Appimage in my sand box: the stop notes now work as expected.

My problem with Drumkits > Save As is that i get the following message :

The drum kit entered in the current song is not on the disc.
Please load an existing drum kit first.
Current kit: []

but loading an existing drumkit will overwrite my instruments. may be the solution would be to load an almost empty drumkit ...(?)

**Comment by theGreatWhiteShark** [comment] 2023-10-09 17:56
> I tested successfully the Appimage in my sand box: the stop notes now work as expected.

Great!

> My problem with Drumkits > Save As is that i get the following message :
>
> The drum kit entered in the current song is not on the disc.
Please load an existing drum kit first.
Current kit: []
>
> but loading an existing drumkit will overwrite my instruments. may be the solution would be to load an almost empty drumkit ...(?)

Damn it. Having just the instruments of the loaded kit but not most of its metadata stored in a .h2song already caused a number of issues. A legacy design decision and actually the thing I'm working on right now for the 1.3.0 release (#1849).

Sorry for all the trouble and thanks for reporting back all those bugs!

I prepared you [yet another AppImage](https://ci.appveyor.com/api/buildjobs/w4b42mo7t7p71t3n/artifacts/Hydrogen-x86_64.AppImage) using which you should be able to save the drumkit.

**Comment by fhenryco** [comment] 2023-10-11 15:38
thanks: with the last appimage i could save my drumkit

**Comment by theGreatWhiteShark** [comment] 2023-10-11 18:43
Awesome. Are there still open points or can we close here? I would transfer the "export for looping" feature into a dedicated issue

**Comment by fhenryco** [comment] 2023-10-11 21:00
Thanks, please let me know if something comes out for the "export for looping" feature.
I'm currently looking for a jazz complete song template allowing few adaptations and variations to apply to a Jazz standard using brushes such as https://www.youtube.com/watch?v=iRT8mbRWV9k. I already have loaded a good drumkit with brushes and want to see if i can save time writting myself the complete song...i also had a look at the forum but may be not at the right place...

**Comment by theGreatWhiteShark** [comment] 2023-10-12 14:29
> Thanks, please let me know if something comes out for the "export for looping" feature.

Alright. How about you create the issue? This way you get email notifications when we start working on it. (But that will probably take quite a while. There is already a long list of stuff we committed to implementing first)

>  I already have loaded a good drumkit with brushes and want to see if i can save time writing myself the complete song...i also had a look at the forum but may be not at the right place...

When Hydrogen was started over 20 years ago it wasn't designed to allow seamless switching of drumkits. For most kits, whenever you load a them, you have to adjust the patterns in order for the notes of e.g. a kick still belonging to a kit. That's why patterns/songs are somewhat tied to a drumkit and there is no online repo containing various patterns and songs I'm aware of.

But I intend to integrate this seamless switching in version 1.3. So, maybe there will be such an online repo at some point in the future

**Comment by theGreatWhiteShark** [comment] 2023-10-13 06:42
Maybe this get's you started https://github.com/hydrogen-music/Song-and-pattern-repository

**Closed** 2023-10-24 14:14 UTC
Labels: bug
