### ISSUE TITLE
Not exporting kick (1st in list) drum

### ISSUE THREAD

**Issue by sonicpainter** [hydrogen-music/hydrogen#573] opened 2018-03-21 17:27 UTC
Hydrogen version *          :1.0.0 beta1
Operating system + version  : Win7 Home Premium
Audio driver + version      : RealTek High Definition Audio Driver ver. 6.0.1.6196

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When I export as separate tracks, the kick drum does not get exported. It might be the first drum in the list not being exported? 

Here is the file: [3-13-18 beat.zip](https://github.com/hydrogen-music/hydrogen/files/1835170/3-13-18.beat.zip)

Also, since version 0.9.6 on both Mac and Windows 7 versions, I sometimes get an empty audio file of the correct duration when exporting. This happened recently with the version 1.0-beta1

Thanks for all the hard work. I love this application!

**Comment by mauser** [comment] 2018-03-21 20:38
Hi! 

This problem (the missing first instrument) is a known bug of older versions of Hydrogen (0.9.7 and before). I've rewritten the internals of the export dialog in the current version of Hydrogen (1.0), so i'm surprised that this issue is still happening. 

In addition, i can't reproduce it on my system. If i'm exporting your song to seperate tracks, everything looks fine. This is how my export directory looks like after exporting your song:

```
insgesamt 5,4M
-rw-r--r-- 1 sebastian sebastian 1,4M Mär 21 21:32 3-13-18 beat-Kick (Tama Superstar 22")_0.wav
-rw-r--r--` 1 sebastian sebastian 1,4M Mär 21 21:32 3-13-18 beat-Snare (Pearl Free Floating Maple 14x3.5)_4.wav
-rw-r--r-- 1 sebastian sebastian 1,4M Mär 21 21:32 3-13-18 beat-Tambourine (Pearl PTM-10GH)_22.wav
-rw-r--r-- 1 sebastian sebastian 1,4M Mär 21 21:32 3-13-18 beat-Tambourine Pedal (Pearl PTM-10GH)_23.wav
```

Are you sure that you exported with Hydrogen 1.0.0-beta1?

**Comment by trebmuh** [comment] 2018-03-23 19:15
I've tried to export your song on my system and I can't reproduce your issue. The 4 (used in the song) instruments are exported as expected.

@sonicpainter : does removing the quote character as suggested is changing the behavior?

**Comment by sonicpainter** [comment] 2018-03-23 20:36
Yes, removing the quotation marks allowed me to export the Koch drum audio successfully. Thank you!!!

**Comment by elpescado** [comment] 2018-03-23 21:51
We shouldn't use those characters in file names. Hydrogen could replace them with some character (e.g. `_`) or simply drop. Question each platform should handle its disallowed characters, or maintain set of troublesome characters common for all platforms. The latter will help interoperability, I think (eg. prevents from exporting files on Linux that cannot be used on Windows).

**Comment by trebmuh** [comment] 2018-03-23 22:10
This thread is a duplicate of https://github.com/hydrogen-music/hydrogen/issues/462
I'm closing with a duplicate tag then.

**Closed by trebmuh** 2018-03-23 22:10 UTC

**Comment by sonicpainter** [comment] 2018-04-02 17:47
Yes, removing the quotation mark fixed the issue.
