### ISSUE TITLE
incorrect position of song cursor with variable BPM

### ISSUE THREAD

**Issue by lunadog** [hydrogen-music/hydrogen#103] opened 2013-06-18 11:46 UTC
In a song with multiple BPM changes, when the song is stopped, clicking on the timeline will position the cursor correctly, but when play is then pressed, the song starts in the wrong position.

I can't attach patches here, so I will add it to the dev. forum.

**Comment by thijz** [comment] 2015-08-10 10:52
just retested with todays latest github code > issue is still there
if you remove the BPM markers all is ok again

**Comment by lunadog** [comment] 2015-08-11 06:41
Is it worth just implementing the solution I posted?

**Comment by thijz** [comment] 2015-08-11 07:57
looks like i missed the link to the patch :-S
i'll try to apply the patch and let you know the outcome
grtz
Thijs

**Comment by theGreatWhiteShark** [comment] 2020-04-29 20:24
I can confirm this issue and already fixed it for the Jack audio driver (which handles the Timeline differently).

@trebmuh can you assign me for this issue?

**Comment by trebmuh** [comment] 2020-04-30 13:58
@theGreatWhiteShark done

**Comment by theGreatWhiteShark** [comment] 2022-02-14 08:44
Fixed with #1435

**Closed by theGreatWhiteShark** 2022-02-14 08:44 UTC
Labels: bug, severity 2
