### ISSUE TITLE
NSM supports fails if NSM session name contains accents

### ISSUE THREAD

**Issue by Houston4444** [hydrogen-music/hydrogen#420] opened 2016-10-15 13:00 UTC
Hy.
All is in the title. My NSM session name is: éfe
non-session-manager launched from terminal, it says:
(E) SongReader::getPath Song file /home/houston/NSM Sessions/Ã©fe/Hydrogen.nXOYQ not found.

Obviously hydrogen can't open song.

**Comment by mauser** [comment] 2016-11-28 17:42
Hi! 

Thanks for reporting the issue. The problem is now fixed in our git repository. Hydrogen is now handle any command line arguments with non-ascii charactersets better.

**Closed by mauser** 2016-11-28 17:42 UTC

**Comment by trebmuh** [comment] 2016-11-28 18:22
Written here: https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-1.0
