### ISSUE TITLE
Size and Resolution dropboxes continuously reopen

### ISSUE THREAD

**Issue by pvint** [hydrogen-music/hydrogen#324] opened 2015-11-02 00:51 UTC
Since revision 36a2268 the Size and Resolution dropboxes reappear after making a selection.

It seems to be related to the timing code in that commit - commenting the "m_timer->start" out in the following method in src/gui/src/widgets/Button.cpp prevents the problem (but also negates the new timer feature):

void Button::buttonPressed_timer_timeout()
{
        emit clicked(this);

        if(m_timerTimeout > 50)
                m_timerTimeout = m_timerTimeout / 2;
        m_timer->start(m_timerTimeout);
}

**Comment by blablack** [comment] 2015-11-02 09:50
I will try to have a look at this bug this evening.

Aurélien

**Comment by pvint** [comment] 2015-11-07 00:11
Looked at the commit - looks good, and I thought it would do it, but the problem persists (for me, anyway. I'm testing running KDE Plasma 5.4.1, and when the dropdown appears, it works and I can select a different resolution, but it pops right back up and I actually cannot even use any other windows as it keeps the focus. I have to CTRL-ALT-F2 to a tty console and kill hydrogen)

**Comment by blablack** [comment] 2015-11-07 12:21
I retested it and I can't reproduce it anymore - as far as I can tell the logic (signal emissions) for the non "press&hold" buttons should be back to what it used to be.

Can you clean and recompile maybe? Could someone else test it?

**Comment by pvint** [comment] 2015-11-07 16:37
Tested this morning on a fresh git clone (even tried from your fork to be sure) and have the same thing.

To see better what is happening I added a bit of logging:
void Button::mouseReleaseEvent(QMouseEvent* ev)
{
        setPressed( false );
WARNINGLOG("void Button::mouseReleaseEvent(QMouseEvent* ev");
        if (ev->button() == Qt::LeftButton) {
                m_timer->stop();
        }
        else if (ev->button() == Qt::RightButton) {
                emit rightClicked(this);
        }

}


void Button::buttonPressed_timer_timeout()
{
        emit clicked(this);
WARNINGLOG( QString::number( m_timerTimeout) +  " Button::buttonPressed_timer_timeout()");
        if(m_timerTimeout > 50)
                m_timerTimeout = m_timerTimeout / 2;
        m_timer->start(m_timerTimeout);
}



With it logging like this, I ran hydrogen, clicked and held the Stop button for a second or so, then clicked and released the Resolution button, here's the relevant part of the output:

(W) Button::buttonPressed_timer_timeout 31 Button::buttonPressed_timer_timeout()
(I) AlsaAudioDriver::stop stop
(W) Button::buttonPressed_timer_timeout 31 Button::buttonPressed_timer_timeout()
(I) AlsaAudioDriver::stop stop
(W) Button::buttonPressed_timer_timeout 31 Button::buttonPressed_timer_timeout()
(W) Button::mouseReleaseEvent void Button::mouseReleaseEvent(QMouseEvent* ev




(W) Button::buttonPressed_timer_timeout 2000 Button::buttonPressed_timer_timeout()
(W) Button::buttonPressed_timer_timeout 1000 Button::buttonPressed_timer_timeout()
(W) Button::buttonPressed_timer_timeout 500 Button::buttonPressed_timer_timeout()
(W) Button::buttonPressed_timer_timeout 250 Button::buttonPressed_timer_timeout()
(W) Button::buttonPressed_timer_timeout 125 Button::buttonPressed_timer_timeout()
(W) Button::buttonPressed_timer_timeout 62 Button::buttonPressed_timer_timeout()
(W) Button::buttonPressed_timer_timeout 31 Button::buttonPressed_timer_timeout()
(W) Button::buttonPressed_timer_timeout 31 Button::buttonPressed_timer_timeout()
(This continues on for many many lines until I kill H2)

Notice the mouseReleaseEvent in the first segment - that was on the Stop button, the bottom segment is from when I clicked and released on the resolution - there is no mouseReleaseEvent
I'm wondering if this might possibly be a QT bug? I'll do some more tests and try with older QT versions (I'm on 5.4.2)
 Thanks
Paul

**Comment by blablack** [comment] 2015-11-07 17:13
Ok so that makes sense, you are not testing the right code.
The pull request has not been merged with the master branch just yet.

You have 2 options here:
- test de code from the pull request manually (
https://help.github.com/articles/checking-out-pull-requests-locally/)
- try the code from my own branch (
https://github.com/blablack/hydrogen/tree/button_press_hold)

**Comment by pvint** [comment] 2015-11-07 17:42
Ah! Sorry, I looked but missed that branch.
That makes much more sense, since I saw the diffs and it looked like it should work.

Sorry about that ;)

**Comment by pvint** [comment] 2015-11-08 16:41
I confirmed that it's working vorrectly now - sorry for the confusion!

**Closed** 2015-11-29 16:12 UTC
