### ISSUE TITLE
MIDI actions : event parameter not saved for PROGRAM_CHANGE event

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#242] opened 2015-04-01 13:06 UTC
message from Alexandre DENIS (contact@alexandredenis.net) that was sent to us via the dev ml : 

Hi,

I encountered a bug in Hydrogen MIDI settings.

Steps to reproduce:
-- open Preferences, select "MIDI System" tab
-- create the following mapping :
  PROGRAM_CHANGE 1 SELECT_NEXT_PATTERN 1
  PROGRAM_CHANGE 2 SELECT_NEXT_PATTERN 2
-- close the dialog
-- open it again, the settings now read:
  PROGRAM_CHANGE 0 SELECT_NEXT_PATTERN 2

Looks like columns Event, Action, and Action Param are saved, but column
Event Param is lost. A quick look in hydrogen.conf confirms that it's
actually the case: column Event param is not saved.

I am using Hydrogen 0.9.6.1 from kxstudio package.

Thank you,
-Alexandre.

**Comment by thijz** [comment] 2015-04-01 13:07
confirmed : also present in latest 0.9.7

**Comment by aldenis** [comment] 2015-04-01 13:43
I did some more tests. Looks like only PROGRAM_CHANGE is affected.
I tried to manually add a <eventParameter> in hydrogen.conf, but it didn't work.

**Comment by jdekozak** [comment] 2015-08-10 11:48
Hi Alexandre,

Would you please describe the symptom of the bug ? Not saving a value is not bug, it might already be a cause.

I took a look at code and MIDI specs, here is my understanding :
* PROGRAM_CHANGE is unique and the event parameter is useless to carry,
* if you want to compare with CONTROL_CHANGE (aka CC), it is not unique hence the event parameter must be used to identify the source of the change.
* but both events can carry a value !

My guess, to solve the issue that is not described in the first e-mail, you have nothing to do, it works !
;)

Regards,

**Comment by aldenis** [comment] 2015-08-11 09:44
Hi,
It looks like there is an ambiguity on how the MIDI actions are supposed to work and how event filtering is performed.
To me, it looked like it was possible to catch a programm change with a specific number by giving the prog. number as "param", since the param box is not greyed out when PROGRAM_CHANGE is selected as event type, and MIDI learn feature actually fills this column with the program number.
However, there is actually no "catch all" value for param so as to distinguish between catch all events v.s. catch events with a specific number.

Thus we have actually two bugs:
-1- a usabilty issue. "param" box should be greyed out for event types that are not able to filter by param value. Moreover, MIDI learn should not fill param when it is actually not used. It is very confusing for the user.
-2- a feature request. Improve MIDI events filtering, so as to be able to catch all program changes or a specific program number, all notes or a specific note, all values for a given cc, or a given value for a given cc.

What I want to achieve here is: I have a MIDI controler without transport buttons (Akai LPD8). In "pattern control mode" (i.e. pads send program changes, that trigger SELECT_NEXT_PATTERN actions), I want to have pad 8 toggle start/stop, and pads 1-7 select patterns. It looked as if it should be doable directly in hydrogen, but it is not. As a workaround, I use qmidiroute to filter and modify events so as to feed hydrogen with what it expects.

**Comment by jdekozak** [comment] 2015-08-11 12:16
Hi,

You should give a try to SELECT_NEXT_PATTERN_CC_ABSOLUT. This is the midi action that is really taking the value carried by PROGRAM_CHANGE. (SELECT_NEXT_PATTERN is using the one that is put in the midi preferences panel.)

Enter the following parameters in the midi preferences panel :
PROGRAM_CHANGE 0 SELECT_NEXT_PATTERN_CC_ABSOLUT 0

But it will only solve half of your problem, you won't be able to toggle the start/stop with PROGRAM_CHANGE 8, Hydrogen has no built-in "mapping by value" feature. Here I won't say this is a feature for Hydrogen, you can use qmidiroute as you did, or mididings as I do with my Korg ES-1.

Regards,

Note : I have tried testing the above described solution with VMPK plug into Hydrogen, it doesn't work on my platform and looks like a bug !

**Comment by aldenis** [comment] 2015-08-11 21:16
Hi,
Yes, SELECT_NEXT_PATTERN_CC_ABSOLUT is in the workaround I use. I set qmidiroute to catch program change 8 and to transfrom it in a CC (unfortunately, it does not support MMC), and to let pass through other program changes. In hydrogen, I set an action SELECT_NEXT_PATTERN_CC_ABSOLUT upon program change, and PLAY/STOP_TOGGLE upon the CC. The workaround exists.

But whatever, the problem is that hydrogen interface shows a param for every MIDI events and ignores it in some cases, which is misleading for the user. Moreover, the MIDI learn feature fills this param with a value that the event filter will ignore. Very confusing.

**Comment by thijz** [comment] 2015-08-13 10:36
hi guys
to come back to the original issue : the 'confusion' about entering a prog change value ?
would it be enough if that field was simply grayed out (like aldenis mentioned in one of his previous comments) ?

grtz
Thijs

**Comment by jdekozak** [comment] 2015-08-14 19:58
Hi,

It could be useful to gray out the field, for sure. It will avoid confusion. But IMO, this is cosmetic, and not the first thing to do, read below.

I had a quick look at the MidiSenseWidget source code file (the midi learn feature), and the code for a PROGRAM_CHANGE midi event is simply not there ! I saw NOTE, CC and MMC, but the case of PROGRAM_CHANGE doesn't exist, I bet there is a bug and fixing it will help the user to fill in correctly the midi preferences.

Regards,

**Comment by aldenis** [comment] 2015-08-14 22:02
Hi,
That's strange, because MIDI learn *do* work for PROGRAM_CHANGE. Or am I missing something?
Tools > Preferences > Midi System > click the red bullet
then I press pad 8 in "program change" mode, and hydrogen sets event to PROGRAM_CHANGE, and param to 7.

**Comment by jdekozak** [comment] 2015-08-16 12:20
Hi Alexandre,

I cannot reproduce your described behavior with my platform, and that's so strange that I took a look at midi drivers in Hydrogen codebase, I have noticed differences between ALSA and JACK midi drivers. I am using ALSA midi driver. Which one are you using ?

Regards,

**Comment by aldenis** [comment] 2015-08-16 13:31
Hi,
I am using JackMidi, and Hydrogen 0.9.6.1 from kxstudio package, on Debian sid.

**Comment by mauser** [comment] 2015-08-31 18:10
Hi! 

The bugfix from @jdekozak  is now in our repository. Can someone re-test this and report if the issue is now completely fixed?

**Comment by mauser** [comment] 2016-03-26 16:13
I'm closing this one now, seems to be fixed.

**Closed by mauser** 2016-03-26 16:13 UTC
Labels: bug, paper cuts
