### ISSUE TITLE
Midi Track Output

### ISSUE THREAD

**Issue by Markomfc** [hydrogen-music/hydrogen#684] opened 2019-01-08 01:40 UTC
Hydrogen version *    0.9.7      :
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hi new here

I have been trying to create a drum track for song but when I export the midi file it comes out sounding like a wood block hitting on every note. I've had this program for a while and never had this problem and I don't remember changing any settings either so if anyone else has had this problem or similar any help would be welcome 

Cheers

**Comment by elpescado** [comment] 2019-01-08 10:42
Hi,

This is [known issue](https://github.com/hydrogen-music/hydrogen/issues/307) and has been fixed in [1.0.0-beta1](https://github.com/hydrogen-music/hydrogen/pull/450). The issue is in 0.9.7 MIDI export was changed so it uses MIDI note settings as pitches in exported MIDI files. Some songs created using earlier versions every drumkit piece has MIDI note set to the same value (36), which incidentally maps to Hi Bongo in General MIDI spec, exported MIDI files contain only that notes. So, there's workaround - go to Instrument properties panel and set "Note" value to different value for each instrument. Or, if you are using one of built-in drum kits, just reload it. Hoe that helps!

![zrzut ekranu 2018-10-14 o 20 47 12](https://user-images.githubusercontent.com/1619113/46920861-b0347d80-cff4-11e8-9692-07ad052b7cdd.png)

**Comment by trebmuh** [comment] 2019-01-27 12:56
@Markomfc can you try a 1.0.0 beta version and confirm here that fixes the issue?

**Comment by Czsaro** [comment] 2019-11-15 20:55
Hydrogen 1.0.0 0d3bb860
Linux Xubuntu 18.04
Sound : alsa audio driver

Built-in drum kits, GMRockKit. I confirm reloading this drums kit and exporting it to MID works well. I can open it with LMMS 1.2.1 (AppImage), it is loaded in a track and sounds are exact.

**Closed** 2020-03-19 22:32 UTC
Labels: MIDI related
