### ISSUE TITLE
Display on 16:9 QHD+( 3200 x 1800) Laptop

### ISSUE THREAD

**Issue by Parshiwal** [hydrogen-music/hydrogen#683] opened 2018-12-26 19:03 UTC
Hydrogen version *          : 0.9.7 and 1.0.0 Beta 1
Operating system + version  : Windows 10 Enterprise 1803 build 17134.472
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The display of program on my 13.3" 16:9 QHD+( 3200 x 1800) Laptop (Asus Zenbook) is very problematic. Please refer to the image attached.
It becomes totally non usable because there is no way to change the view/display.
![hydrogen](https://user-images.githubusercontent.com/46168028/50454638-3bad8180-0949-11e9-8859-dcbcd081364f.png)

**Comment by elpescado** [comment] 2018-12-31 10:03
1.0.0 release was [supposed](https://github.com/hydrogen-music/hydrogen/pull/487) to solve this issue:/

Unfortunately, I don't have any high-DPI screen to test this.

**Comment by trebmuh** [comment] 2019-08-21 10:30
Duplicate of #264 ?

**Comment by theGreatWhiteShark** [comment] 2021-11-05 08:52
Duplicate of #264 . Please have a look there for comments and solutions.

**Closed by theGreatWhiteShark** 2021-11-05 08:52 UTC
