### ISSUE TITLE
Annoying window at pattern change

### ISSUE THREAD

**Issue by Houston4444** [hydrogen-music/hydrogen#788] opened 2019-11-27 10:07 UTC
Hydrogen version *          : 1.0.0-'b40bff46'
Operating system + version  :  Ubuntu 18.04
Audio driver + version      :  no matter

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I'm starting a song with different pattern sizes inside.
While playing in song mode, each time I switch the view from a pattern to another with a different length, an annoying error window appears with the text: "Is not possible to change the pattern size when playing".
It doesn't make hydrogen stop playing or crash, but it is quite annoying, and clearly, it is a bug.

 Steps to reproduce.

1. Start hydrogen
2. fill Pattern 1
3. Set Pattern 2 size different from Pattern 1 size
4. write a song containing Pattern 1 and Pattern 2
5. Start playing
6. click on Pattern 1, and Pattern 2, and Pattern 1, and Pattern 2, etc...

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by thijz** [comment] 2020-01-29 14:03
confirmed on 0d3bb860696c7149cd0eb9f722a9c13751a359c7

**Comment by mauser** [comment] 2020-03-09 23:52
Hi! 

This is a duplicate of #708 , so i will close this issue (and mention it in #708).

**Closed by mauser** 2020-03-09 23:52 UTC
Labels: bug, confirmed
