### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by thomasmilani86** [hydrogen-music/hydrogen#620] opened 2018-06-20 06:51 UTC
Hydrogen version *          :
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Website has been apparently down for a while. Just wanted to give a heads-up on that. Sorry if it is the wrong place.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by trebmuh** [comment] 2018-06-20 17:01
Duplicate of https://github.com/hydrogen-music/hydrogen-music/issues/1

**Closed by trebmuh** 2018-06-20 17:01 UTC
Labels: duplicate
