### ISSUE TITLE
V1.0.0.Beta1; Default Drumkit import url wrong

### ISSUE THREAD

**Issue by JohnRanger** [hydrogen-music/hydrogen#747] opened 2019-07-28 15:32 UTC
Hydrogen version *          : V1.0.0.beta1 x64
Operating system + version  : Win10 x64, 10.0.17134.885
Audio driver + version      :  does not matter in this case

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Issue: as of 2019-07-28, the drumkit import URL which is installed by default when installing above hydrogen version, doesn't work.

but if it is changed to the following:
[https://musical-artifacts.com/hydrogen_drumkits.xml ](url) then the drumkits gets found and can be downloaded.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

With kind regards,

John

**Comment by trebmuh** [comment] 2019-08-09 15:57
Can't confirmed that here.
The http://www.hydrogen-music.org/feeds/drumkit_list.php works here.
Is that the same we are talking about ?

@JohnRanger can you retry please?

**Comment by MceN-GR** [comment] 2019-09-05 16:55
I have the same issue.. I can't download from default link. I didn't try the other link.

**Comment by Archloy** [comment] 2019-09-13 20:01
Hi ! I'm using V1.0.0.beta1 x64 on Archlinux and same problem here. 
Tried the other url listed here but with no effect. 
The interface does not list anything, no drumkits or patterns. Links are OK, I can wget the content, but not in H2 interface. 
I've launched with -v Debug option, and filter all "H2Core::audioEngine_process(uint32_t" because the problem isn't in audioEngine I think ;), logfile in attachment. And a screenshot, after clicking on "refresh".
Thanks  
![2019-09-13-215606_1920x1080_scrot](https://user-images.githubusercontent.com/8998288/64891316-eb5e8700-d671-11e9-8e9d-5493159aa7a2.png)
[logFiltered.log](https://github.com/hydrogen-music/hydrogen/files/3611625/logFiltered.log)

**Comment by mauser** [comment] 2019-09-13 22:49
Hi! 

Thanks for the report, it seems at least the second URL leads to an error in the logs. What happens if you use http://hydrogen-music.org/feeds/drumkit_list.php (without the "www.") ?

In addition, i've added some additional debug output to the SoundLibraryImportDialog in the current master branch of Hydrogen some minutes ago.

**Comment by Archloy** [comment] 2019-09-14 10:02
Hi ! 
So, I've tried to add the url without www, with no effects on the official beta1 pre-release.
After that, compiling and install package from "AUR" repository (build a local package from git master directly, adding patches for translations). You can get package build script (PKGBUILD) here https://aur.archlinux.org/packages/hydrogen-git 

Now using Hydrogen v1.0.0-'c31a0af7' and it works well with any links listed here :) 
Download and install is working. I just can't resize the window, does it be a fixed width modal window of it's my tilling manager's bug ? 
And a least one question : Do you have any "nightly build" repository, for users that are not software developers ? 
No problem detected, I can load my projects, all good ! 
Thanks for help !
Note : The only listed pattern "JazzRockFast" return 404.

**Comment by theGreatWhiteShark** [comment] 2019-09-15 10:44
> I just can't resize the window, does it be a fixed width modal window of it's my tilling manager's bug ?

Can you open a separate issue (incl. which window manager you do use etc.) so we can keep track of this problem?

**Comment by mauser** [comment] 2020-03-17 22:18
>  Note : The only listed pattern "JazzRockFast" return 404.

I've fixed the issue with the 404, the pattern should be available again. Since the remaining part of the issue seem to be not reproducable, i will close this issue. Just comment if you have more (or new) information.

**Closed by mauser** 2020-03-17 22:18 UTC
Labels: more info needed
