### ISSUE TITLE
manuals and tutorials list don't appear anymore in the GUI

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#346] opened 2015-12-30 21:01 UTC
Following a thread on the mailing list today : http://sourceforge.net/p/hydrogen/mailman/message/34728714/ , I'm just reporting here that I can confirm (Debian stable package 0.9.6.1) that when opening the "menu -> infos -> user manual", I've got an empty windows while I used to have a list of available manuals and tutorials:
![user-manuals-0 9 6 1](https://cloud.githubusercontent.com/assets/8705846/12057355/80823212-af40-11e5-91ec-742f1ab6ad71.png)
Looking on a old linux box (Ubuntu 10.04 Lucid) running Hydrogen 0.9.4.2, it should be:
![user-manuals-0 9 4 2](https://cloud.githubusercontent.com/assets/8705846/12057360/99092822-af40-11e5-928a-5920b84bfdc9.png)

This issue might be (or not) related to https://github.com/hydrogen-music/hydrogen/issues/74

Next step for me is trying to make clear if it's related to the code itself (I'll will install an Hydrogen from a fresh GIT pull) or from the debian packaging.

**Comment by trebmuh** [comment] 2016-02-29 19:31
Note that it doesn't appear neither with a fresh git pull build ( https://github.com/hydrogen-music/hydrogen/commit/956fd11414815318aa4a0d7379ff1d368dc31d0b )

**Comment by thijz** [comment] 2016-03-05 21:33
duplicate of #74

**Comment by mauser** [comment] 2016-03-26 11:12
Closing this one (as it is a duplicate). Discussion can go on in #74.

**Closed by mauser** 2016-03-26 11:12 UTC
