### ISSUE TITLE
I keep setting up custom kits I've saved them, even exported them as a back but when I return to work on them the sounds do not work. 

### ISSUE THREAD

**Issue by liquidshadows71** [hydrogen-music/hydrogen#622] opened 2018-07-02 11:28 UTC
Hydrogen version *          :0.9.7
Operating system + version  : windows7 sp1 32bit
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When I set up a custom drumkit it works great. But if I return later the kits plays no sounds. preloaded kits work fine. I even tryed exporting a kit as a back up and it will not load at all. 

_edit: message edited by @trebmuh for a better display_

**Comment by trebmuh** [comment] 2018-07-02 13:44
@liquidshadows71 : please check if this still happens with [1.0.0-beta1](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0-beta1) and report back here.

**Comment by FrictionCow** [comment] 2018-08-05 21:12
@trebmuh Hello, I am having the same issue as reported in this ticket. I am using the latest git build (commit 969c42d7faad4db21764012cc2b9508f676feca4), and I'm on Ubuntu 18.04 64-bit (running JACK2 for audio), so I this bug is also cross-platform, and still persists. I also noticed that in all of my non-working imported drumkits, the drumkit.xml file lacks all <layer> tags and anything that was in them. All the actual samples still remain though. I hope that helps this issue get resolved.

**Comment by mauser** [comment] 2018-08-13 19:32
@FrictionCow : Do you have a step by step guide to reproduce this issue? I would like to look into it, but at the moment i can't reproduce it

**Comment by FrictionCow** [comment] 2018-08-13 23:08
@mauser In my situation, I try to import a local h2drumkit (made in hydrogen 0.9.7) file into the user drumkits. Then I either exit hydrogen, or load a different drumkit, and reload the original drumkit. Either way, there's no sound. And in the hydrogen/data/drumkits/.../drumkit.xml of the imported file, there should be no <layer></layer> parts. Everything else, remains in the drumkit files, just not the layers. The imported drumkit.xml file does contain the newer elements like <image> and <instrumentComponent>.

I've tried to make a new drumkit, export it, delete it, and re-import it (in 1.0.0-beta1) to test this out with, but it seems this issue only affects drumkits in an older version of hydrogen?

**Comment by trebmuh** [comment] 2018-09-12 20:51
> hydrogen overwrites it to delete the "layer" element when the program starts

mmm, kind of annoying!

**Comment by theGreatWhiteShark** [comment] 2018-09-14 14:12
I can confirm this issue. The same happened to me a couple of times with a custom drumkit. However, I was not able to reproduce the problem yet.

**Comment by theGreatWhiteShark** [comment] 2018-09-14 16:03
Okay, it just happened again and, fortunately, this time I was able to reproduce it and to boil it down to a minimal example using the attached drumkit 
[testKit1.tar.gz](https://github.com/hydrogen-music/hydrogen/files/2383960/testKit1.tar.gz)

Steps to reproduce the issue:
- copy the extracted drumkit where Hydrogen can find it
``` bash
cp testKit1 ~/.hydrogen/data/drumkits
cat testKit1/drumkit.xml | grep layer | wc -l
```
> 4

It still got two *layer* nodes containing two sound files.

- open up **Hydrogen** (I used todays commit bdeed83) and close it again
``` bash
hydrogen --verbose=DEBUG > h2.log.0.txt
cat testKit1/drumkit.xml | grep layer | wc -l
```

> 4

[h2.log.0.txt](https://github.com/hydrogen-music/hydrogen/files/2383979/h2.log.0.txt)

Still two *layer* nodes.

- Finally, open up **Hydrogen** a second time.
``` bash
hydrogen --verbose=DEBUG > h2.log.1.txt
cat testKit1/drumkit.xml | grep layer | wc -l
```
> 0

[h2.log.1.txt](https://github.com/hydrogen-music/hydrogen/files/2383985/h2.log.1.txt)

Suddenly, all *layer* nodes are gone.


Here is what changed in the **drumkit.xml** file. (I use `meld` to visualize the changes)

![drumkitchange-0](https://user-images.githubusercontent.com/14164547/45561142-500cb900-b847-11e8-8f7a-c9dbc7d24a2e.png)

After the first run of **Hydrogen** some additional additional nodes have been inserted into the original file (left) and the environment containing the *layer* were restructured (right).

Running **Hydrogen** a second time did produce the following:

![drumkitchange-1](https://user-images.githubusercontent.com/14164547/45561150-556a0380-b847-11e8-842a-3fec4f56f4a0.png)

Left is the resulting **drumkit.xml** from starting Hydrogen the first time. Right are the changes applied when starting it a second time. As you can see, all the *layer* nodes have just been removed.

**Comment by mauser** [comment] 2018-09-15 00:05
That looks great, thanks for your input!!

**Comment by jeremyz** [comment] 2018-09-15 17:57
drumkit.xml does not validate against drumkit.xsd,
thus Legacy::load_drumkit( dk_path ) is called and then save_file( dk_path, true, -1 );
but the rewritten dumkit.xml is still not valid !!!!!
so at the second startup, Legacy::load_drumkit( dk_path ) is used again,
but it is not designed to read the <layer> tag within <instrumentComponent> ...

the rewritten drumkit.xml must be valid, I'm on it ...

**Comment by jeremyz** [comment] 2018-09-15 18:39
<Decay>40960</Decay> that was the problem

**Closed by jeremyz** 2018-09-15 18:39 UTC
Labels: bug, severity 1
