### ISSUE TITLE
Could not export pattern dialog shows up every time I try to copy track

### ISSUE THREAD

**Issue by BiswajitPual** [hydrogen-music/hydrogen#941] opened 2020-09-17 13:19 UTC
Hydrogen version *          : 1.0.0
Operating system + version  : Windows 10
Audio driver + version      :  Logitech Headphones + 10.0.19041.1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Every time I try to copy a pattern or try to import it, I keep getting "Failed To Export Dialog".

**Steps to reproduce (In my case)**

1. Create a pattern.
2. Copy it.
3. You should get the error telling it's failed to Export.

1. Create a pattern.
2. Export it.
3. Try to import it.
4. You should get the same error.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by BiswajitPual** [comment] 2020-09-17 14:46
> I've tried with 1.0.1 on my LibraZiK-3 (Debian GNU/Linux) and it works as expected here.
> 
> @BiswajitPual : could you try the same with the [newest 1.0.1 version](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.1) and report back here? Thanks.

The problem still persists.

**Comment by trebmuh** [comment] 2020-09-17 15:17
Thank you for testing. You'll need to wait for someone with windows' skills to check that now.

**Comment by mauser** [comment] 2020-09-24 18:20
Hi @BiswajitPual ! 

i've couldn't reproduce the issue, but i can see from the code what goes wrong. What happens in your case is that Hydrogen is trying to save a temporary version of a pattern to a temporary directory. This fails somehow, and the "could not export pattern" dialog is raised. 

The first problem is that the caption of the dialog is wrong. This should be sth. like "Could not create temporary copy of pattern" or sth. like that. The second problem is that Hydrogen is not able to write the pattern to that directory. I don't know why this is, the temporary directory is retrieved by asking QT (our window toolkit), and QT should ask your system about that directory. It could be that the directory does not exist or is not writable. You could try to launch Hydrogen as adminstrator (just for testing..), this could solve the issue if it is a permission problem. 

I will add some debug output about the used directories (user/system drumkit directory, temporary directory,...) to Hydrogen to make it clearer to the user where Hydrogen stores files. In addition, it makes sense that Hydrogen throws an error on startup if it is not able to write to the temporary directory.

**Comment by mauser** [comment] 2020-09-24 19:47
@BiswajitPual: If you want, you could try [this](https://ci.appveyor.com/api/buildjobs/h3418f1xilb9xxu2/artifacts/build%2FHydrogen-1.1.0-win64.exe) version of Hydrogen which includes my current fixes. I've added a check which checks if the temp directory is write on startup of the Hydrogen application. If it is not writable, a warning will pop up which also includes the path which hydrogen wants to write to.

**Comment by SithlordIII** [comment] 2020-09-26 20:06
I get same issue on Windows 10 with ver1.0.0 and 1.0.1 - it also wont allow a delete of a pattern comes up with same error  - I have run as admin but no change - I have a version 0.9.7 that work fine on another windows 10 machine but when install 0.9.7 on win 10 with issue   all the dialog boxes are white with no text     but can copy and delete patterns

**Comment by mauser** [comment] 2020-09-27 09:47
@SithlordIII : Could you try out the version of Hydrogen which i have linked in my last post? It doesn't solve the problem, but it gives a error messages that would help to understand the problem

**Comment by BiswajitPual** [comment] 2020-09-27 11:00
@mauser , I tried the new version in both normal and "run as admin"

I'm getting the this error now.

"Could not save pattern to temporary directory"

**Comment by SithlordIII** [comment] 2020-09-27 11:01
@mauser :  Thank you for your reply ,  Just installed the version in the link   I get the "could not save pattern to temporay directory" dialog when I copy or delete a pattern - I have run as admin aswell  , I have tried on a differnet machine (WIN 10)  thats not had hydrogen installed before , I have checked all permissions in the folders and all apear to be ok

**Comment by dhpinkerton** [comment] 2020-11-09 04:08
I'm also getting the "could not save pattern to temporay directory" dialog when I copy or delete a pattern on Win10

**Comment by SithlordIII** [comment] 2020-11-24 07:51
Hi, @mauser are we near a solution to the windows issue preventing copy/delete of patterns  in windows 10 o/s   Warmest Regards

**Comment by dhpinkerton** [comment] 2020-11-24 08:33
I got it working by create a c:\tmp directory, giving all users full permission to it and then setting the  system environment variables TMP & TEMP to use this new directory. 

![users_tmp](https://user-images.githubusercontent.com/74167174/100068571-d42d4300-2e8b-11eb-8890-8f0c0e00062d.PNG)
![system_tmp](https://user-images.githubusercontent.com/74167174/100068587-d7c0ca00-2e8b-11eb-9d15-aaf1bb47caf2.PNG)

**Comment by SithlordIII** [comment] 2020-11-24 23:01
@dhpinkerton Thank you for your reply,  Just tried this but no joy for me , I uninstalled and reinstalled hydrogen rebooted and still showing cannot export for copy/delete , tried as admin to  and rechecked security permissions

**Comment by dhpinkerton** [comment] 2020-11-24 23:15
I forgot to mention I also deleted the TMP & TEMP variables from the user profile.  In a dos shell typing "set" should show the current values.  Confirm you are pointing to the new tmp directory.

**Comment by SithlordIII** [comment] 2020-11-25 08:20
Morning @dhpinkerton THANK YOU  After a little messing about got your solution to work , will get my son to have a proper play today     I was changing SYSTEM enviroment variables to the C:\Tmp  not USER PROFILE enviroment variables   which I have now done


1 Open the Control Panel (icons view), and click/tap on the User Accounts icon.

2 Click/tap on the Change my environment variables link on the left side,

Again Thank you and will get my son to fully test later today     I have 2 other machines with same issue so will try above on them this evening

**Comment by cme** [comment] 2020-11-25 09:21
Hi @SithlordIII @dhpinkerton, can I ask you what the file permissions on your *default* user temp directories (`C:\Users\%USERNAME%\AppData\Local\Temp`) are? Do the directories exist and are writable?

**Comment by SithlordIII** [comment] 2020-11-25 09:30
I tried to add the permissions @dhpinkerton [2] listed above to the
(C:\Users\%USERNAME%\AppData\Local\Temp) 

  I added users and everyone as user to full control but didnt work     


when I changed USER environment variables to the c:\Tmp   it worked with
the users  set to full control 

On 25/11/2020 09:21, Colin McEwan wrote:

> Hi @SithlordIII [1] @dhpinkerton [2], can I ask you what the file permissions on your _default_ user temp directories (C:\Users\%USERNAME%\AppData\Local\Temp) are? Do the directories exist and are writable? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1] https://github.com/SithlordIII
[2] https://github.com/dhpinkerton
[3]
https://github.com/hydrogen-music/hydrogen/issues/941#issuecomment-733578121
[4]

**Comment by SithlordIII** [comment] 2020-11-25 09:32
I will check these on the other machine when i get home

On 25/11/2020 09:21, Colin McEwan wrote:

> Hi @SithlordIII [1] @dhpinkerton [2], can I ask you what the file permissions on your _default_ user temp directories (C:\Users\%USERNAME%\AppData\Local\Temp) are? Do the directories exist and are writable? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1] https://github.com/SithlordIII
[2] https://github.com/dhpinkerton
[3]
https://github.com/hydrogen-music/hydrogen/issues/941#issuecomment-733578121
[4]

**Comment by mauser** [comment] 2020-11-25 15:41
Hi everyone,

this thread shows that we really need more debugging capabilites with Hydrogen on Windows. Hydrogen writes a log file to the user directory (normally), but somehow this also does not work on windows (at least not on my machines). 

My plan is to add the following features so we can debug issues like this easier: 
-  open the log file or its directory via the debug menu
-  choose the log level via the debug menu
- repair logging to the log file on windows

This does not directly fix this bug, but it should help to nail down the problem..

**Comment by mauser** [comment] 2020-11-25 19:33
@SithlordIII : 

Could you try [this](https://ci.appveyor.com/api/buildjobs/5ypr16r1ui5a01kp/artifacts/build%2FHydrogen-1.1.0-win64.exe)  version of Hydrogen? It should show a command windows with log output. Furthermore, you can set the log level via "Debug" -> "Log level" -> "Debug", then try to copy a pattern. After the pattern copying fails, either look at the console window or open the log file directly via "Debug" -> "Open log file". You could also try to attach that file to your comment.

**Comment by SithlordIII** [comment] 2020-11-25 20:13
@mauser Thank you rest permissions and user variables back to where they where originally and got original error / have installed version you linked to  set debug etc   tried copying and delete a few times image of console window below   (but would ot let e open LOG file )
![Untitled4](https://user-images.githubusercontent.com/22499606/100277166-9cd99780-2f5a-11eb-8993-821a98b9314c.png)
![Untitled3](https://user-images.githubusercontent.com/22499606/100277192-a95df000-2f5a-11eb-964e-7f6d776abe5a.png)
![Untitled2](https://user-images.githubusercontent.com/22499606/100277195-aa8f1d00-2f5a-11eb-8a25-406ba2d1afee.png)
![Untitled](https://user-images.githubusercontent.com/22499606/100277197-aa8f1d00-2f5a-11eb-9bca-b55745c02db3.png)

**Comment by mauser** [comment] 2020-11-25 20:45
Ok, two additional  things: 

Can you open "Debug" -> "Show filesystem information" and show us a screenshot of that dialog? In addition, could you hit the "open" button in the first row of that dialog to open the temporary directory? It would be great if you could try to create a file in that directory.

**Comment by SithlordIII** [comment] 2020-11-25 20:53
@mauser     last images show empty folder    right clicked created text document ok openened edited and re saved 
![Untitled6](https://user-images.githubusercontent.com/22499606/100280437-188a1300-2f60-11eb-8c8c-85fef3d81487.png)
![Untitled7](https://user-images.githubusercontent.com/22499606/100280449-1e7ff400-2f60-11eb-9f1a-a4f6459f0bf4.png)
![Untitled8](https://user-images.githubusercontent.com/22499606/100280462-2344a800-2f60-11eb-95af-a40144e79ff6.png)

**Comment by mauser** [comment] 2020-11-25 21:10
@SithlordIII : Thanks a lot, that explains it. It is the whitespace in your username which causes the problem. I've created a new windows user "example user" and now i can reproduce it also on my windows computer. That's a classic :) I will see why this gives us trouble on windows and what we can do about it, but not today. Thanks for providing the screenshot and beeing patient!

**Comment by SithlordIII** [comment] 2020-11-25 21:18
@mauser Your most welcome happy to help anyway we can  and thank you for such a fantastic musicall tool too ,

**Comment by mauser** [comment] 2020-11-27 12:24
[This version](https://ci.appveyor.com/api/buildjobs/h9canbiuepsp9j16/artifacts/build%2FHydrogen-1.1.0-win64.exe) might fix this problem.

**Comment by SithlordIII** [comment] 2020-11-27 12:30
thank you will download and get my son to test as soon as im home

On 27/11/2020 12:24, Sebastian Moors wrote:

> This version [1] might fix this problem. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1]
https://ci.appveyor.com/api/buildjobs/h9canbiuepsp9j16/artifacts/build%2FHydrogen-1.1.0-win64.exe
[2]
https://github.com/hydrogen-music/hydrogen/issues/941#issuecomment-734811008
[3]

**Comment by SithlordIII** [comment] 2020-11-27 20:11
@mauser Evening   Installed version requested  and this version allows coying and deleting of patterns   Thank You , I will get my son to have a proper play but looks like issue has now been resolved without the need to change tmp folders and alter folder permissions well done  and Thank you

**Comment by mauser** [comment] 2020-11-27 22:04
Perfect! I will close this issue now, but just comment again if anything is still going wrong.

**Closed by mauser** 2020-11-27 22:04 UTC
Labels: Windows, bug

**Comment by dhpinkerton** [comment] 2020-11-28 07:53
Download failed

![image](https://user-images.githubusercontent.com/74167174/100496779-efa98e00-31aa-11eb-91b8-e7dcb8f9e225.png)

**Comment by mauser** [comment] 2020-11-28 21:37
> Download failed
> 
> ![image](https://user-images.githubusercontent.com/74167174/100496779-efa98e00-31aa-11eb-91b8-e7dcb8f9e225.png)

The chances are high that this is (another) false positive. It seems to happen often that software which has been compiled with mingw is detected as a virus and removed by some malware protection tools.

The binary has been built with the AppVeyor cloud build service, so i can't guarantee that it is malware free, but it would seems to be not very likely..

**Comment by SithlordIII** [comment] 2020-11-29 13:21
@mauser  @dhpinkerton Ive downloaded ok no issues found scanned using Windows defender and Sohpos Antivirus   -- only issue was I had Smart Screen saying was an unpublised/verified exe - just select run anyway ,   re scanned machine and all ok no issues

**Comment by aimbot-napalm** [comment] 2021-02-12 18:40
Hello everyone, I encountered the same problem. The second 1.1.0 Hydrogen version from @mauser has the console (quite a useful thing), however I had a problem with the playback (the program stopped after playing the first bar). The solution to the "copying" problem was found on the 1.0.1 version. While copying a pattern, the program probably creates a temporary file and it uses the pattern name to name the file. There are signs you can't use in the file names (my problem were the the slashes that I used for writing pattern time signatures, after changing them everything worked as usual). Be sure to check this thing boys and girls. :)
