### ISSUE TITLE
0.9.7 Beta 2 for Win - PortMidi not working with loopback

### ISSUE THREAD

**Issue by Nat-Napoletano** [hydrogen-music/hydrogen#382] opened 2016-07-08 12:23 UTC
PortMidi is not working with loopback. Symptom: no MIDI input to Hydrogen. MIDI-IN indicator never illuminates.

Tested and fails with LoopBe and MIDI Yoke. No problem with Tools->Preferences->Input selection. Seems to attach with no problem.

Hydrogen 0.9.6 works with no problem.

**Comment by mauser** [comment] 2016-07-10 11:58
Hi!
What do you mean exactly by "not working with loopback"? What is "loopback"?

**Comment by Nat-Napoletano** [comment] 2016-07-13 15:58
Thanks for asking Mauser. I've done more experimentation so I have more info, but I'll explain the loopback thing at the end.

Hydrogen 0.9.7 Beta 2 for Win will not receive any MIDI serial packets from any input device using port audio. The MIDI indicator light never blinks. I have tried several MIDI devices including a Novation Launchpad, Presonus Audiobox. Korg M50 keyboard with windows driver and loopback software. 

Hydrogen 0.9.7 reports no error when you select the device and restart the MIDI service. 

I'm testing on a Toshiba laptop and I'm certain of the laptop's MIDI system integrity because of the many other programs running correctly, and because Hydrogen 0.9.6 works correctly. I'm surprised by this fault because it seems like a serious bug that would have been detected by the authors.

MIDI loopback software is described by one of the authors:  LoopBe1 is an internal MIDI device for transferring MIDI data between computer programs. Basically LoopBe1 is an "invisible cable" to connect a MIDI outport of an application to any other application´s MIDI inport. Hydrogen 0.9.6 works correctly with LoopBe1 and I can play the drums with a virtual keyboard or any hosted VST sequencer.

**Comment by mauser** [comment] 2016-07-13 17:24
Hi! 

Thanks for the more detailed informations, i will have a look at the problem.. 

About bugs being detected by authors: Well, this is an open source project which is run by people in their free time. Hydrogen works with different audio and midi backends on various Unix/Linux Systems, Mac OS X and Windows, so it is very unlikely that all combinations will be tested. This is one reason why we release "beta" versions of hydrogen. And i think that most of the people which are involved in the project are testing their stuff only on linux..

**Comment by mikotoiii** [comment] 2016-07-13 18:02
Unfortunately i don't have a setup to test out the portmidi stuff myself
yet.

The only thing that i can think of off the cuff is that the portmidi which
comes bundled is a wrapper for hydrogen to communicate with the portmidi
driver? You can try and install the windows version of portmidi from their
sourceforge page here, though it was last modified in 2010:
https://sourceforge.net/projects/portmedia/files/portmidi/217/pmdefaults-setup-w32-217.zip/download

**Comment by Nat-Napoletano** [comment] 2016-07-13 18:07
Hi Mauser. I fully understand the generosity behind open source. I tend to be a little Asperger. Please extend my thanks to the authors for their brilliant work if you have any contact with them. The human interface in Hydrogen is tops, and that includes payware.

When I said that I was surprised by MIDI fault, I meant that, if true, it was a major undetected fault and maybe more likely that I was screwing something up (user error). 

Are you the one doing the cross compiles for windows? Thanks you for your gift to the community. I'm an old hardware engineer and it takes me forever to do that type of thing.

I really like the new MIDI automation controls in 0.9.7. In fact they make a difference of night and day because I can have a remote MIDI program change patterns and change songs. I'm highly motivated to get MIDI working on 0.9.7. I plan to test on another machine under different conditions to see if I can be of more help.

**Comment by Nat-Napoletano** [comment] 2016-07-13 18:21
Hi mikotoiii. I'm a little confused by your suggestion. In Hydrogen 0.9.6 and 0.9.7, it seems to come bundled with some portMIDI components. After installing Hydrogen, you merely need to select Tools->Preferences->MIDI System->MIDI driver: PortMIDI and then all of the MIDI devices show up under inputs. But on 0.9.7, the MIDI messages never seem to get picked up by Hydrogen. On Hydrogen 0.9.6, MIDI in works with no problem.

Are you telling me that I should install an external PortMIDI service on the machine?

**Comment by mikotoiii** [comment] 2016-07-13 20:15
I'm more suggesting something that you can try to get it working. I'll have
to see if I can get a midi set up to run some tests.

**Comment by mauser** [comment] 2016-07-13 21:07
Hi,

i can confirm the problem. On my Windows 7 installation, the PortMidi initially failed to load completely. After plugging my usb-midi device in and out some times (and restarting Hydrogen), Hydrogen was able to load the PortMidi Driver and choose my Midi Device as an Input . But even then, no midi input could be received. 

After starting hydrogen from command line, i can see that the PortMidi driver complains that the Midi input device is missing, so this looks like an issue with Hydrogen's PortMidi driver.

**Comment by mauser** [comment] 2016-07-14 21:30
I think that i've spotted and fixed the problem, it was also present on Linux. I'm building a new Windows binary at the moment but i'm afraid it will take until the weekend until i'm back at my pc to upload it.

**Comment by mauser** [comment] 2016-07-14 21:50
Faster then expected: try this [test-version](http://stuff.smoors.de/Hydrogen-0.9.7-win32-portMidiFix.exe).

**Comment by Nat-Napoletano** [comment] 2016-07-16 19:13
WOW! Thanks mauser. You are da man. The MIDI stream is definitely being received by your test version of hydrogen, and the basic functioning remains solid. 

I'm testing out the MIDI control. Most of the functions that I need seem to be working reliably. I'm going on to do a complete test of all MIDI functions so that I can be a help to the hydrogen community. It may take a few days, I'm automating the testing with ChucK audio. 

I may have found something already: the MIDI control function "PLAYLIST_SONG" has a parameter associated with it. Hydrogen seems to select playlist song 1 (one), no matter what this parameter is set to. PLAYLIST_NEXT_SONG and PLAYLIST_PREVIOUS_SONG seem to work fine.

I'll post a full report in a day or two.

**Comment by mauser** [comment] 2016-07-16 22:03
Thanks for the feedback and the new tests! I'm going to close this ticket now, just create a new one if you find any bugs concerning the midi actions.

**Closed by mauser** 2016-07-16 22:03 UTC
