### ISSUE TITLE
Bug soloing instrument

### ISSUE THREAD

**Issue by mikotoiii** [hydrogen-music/hydrogen#555] opened 2018-03-08 17:24 UTC
Hydrogen version *          : 1.0.0-'1a477ffe' (HEAD: 1a477ffe380f153c5d9fb3495d9874df7f75334f)
Operating system + version  : Windows 7 X64
Audio driver + version      : PortAudio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Hydrogen crashes when trying to solo an instrument.

Steps to reproduce: 
1 - Launch Hydrogen
2 - Click solo on any instrument on the left side under the pattern

Additional Details:
I've uninstalled Hydrogen 1.0.0 and installed 0.9.7 from Sourceforge and the problem does not exist there. I've also tested that this problem exists on both the 32 and 64 bit binaries.

I've also tested on my Linux system, and can't seem to replicate the issue there. I don't have a Mac to test against unfortunately.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by mikotoiii** [comment] 2018-03-08 19:17
For further testing I started playing with soloing tracks, and tracked things down a little more. 

If you start hydrogen without the mixer active, and try to solo an instrument from the left it will crash. If you start hydrogen and turn on the mixer, then you can solo from the left even after turning off the mixer.

If you turn off the mixer, and solo an instrument, clicking solo again will not unmute the instruments.

This behavior can be replicated on linux as well.

**Comment by mauser** [comment] 2018-03-12 21:44
Hi! 

Thanks for spotting this issue, i'm able reproduce it here and can see where and why it happens.

**Comment by elpescado** [comment] 2018-03-13 06:32
I think I encountered this bug on a Mac.

**Comment by mauser** [comment] 2018-03-13 23:18
Hi! 

The bug has been caused by me and should be fixed now. Occured on all platforms, not only windows.

**Closed** 2018-03-13 23:18 UTC

**Comment by trebmuh** [comment] 2018-03-22 21:15
Looks good to me after playing a bit with the solo action on a build from https://github.com/hydrogen-music/hydrogen/commit/bfc355ee5c3fa1a62f12d056427bc1a827764a61
