### ISSUE TITLE
instrument volume not saved

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#337] opened 2015-11-26 11:50 UTC
open a new song
select one of the instruments
goto instrument > layers
change the c. volume
save song

open song
c. volume is back at the default 11'

**Comment by blablack** [comment] 2015-11-28 17:58
@thijz reproduced, but not reproduced in https://github.com/blablack/hydrogen/tree/sample_selection :)

We can wait for the pull request to be accepted or I can extract the fix.
Let me know!

**Comment by thijz** [comment] 2015-11-29 21:09
@blablack : hi Aurelien!
good to know that there already is a fix :-)
let's just wait for the pull request to get accepted

**Comment by blablack** [comment] 2015-12-29 20:12
@thijz sorry for the late reply!
No i meant this pull request: https://github.com/hydrogen-music/hydrogen/pull/291

**Comment by mauser** [comment] 2016-03-28 10:24
Hi everyone! 

I've split the bugfix from the pull request and put it in the master branch, the issue seems to be fixed now.

**Closed by mauser** 2016-03-28 10:24 UTC
Labels: bug, severity 3
