### ISSUE TITLE
LINNDRUM Machine samples

### ISSUE THREAD

**Issue by Reaper10** [hydrogen-music/hydrogen#827] opened 2020-04-02 18:45 UTC
i found a free LINNDRUM Machine samples pack for you here-> https://www.youtube.com/watch?v=u_d0CM2H98E
[LinnDrum Samples.zip](https://github.com/hydrogen-music/hydrogen/files/4423037/LinnDrum.Samples.zip)
i even added a picture of it

**Comment by mauser** [comment] 2020-04-05 12:10
Hi,

i'm going to close this issue sine it is not a bug or a feature request for Hydrogen. 

Furthermore, any licensing information is missing from the Zip File, which brings up legal questions. I

**Closed by mauser** 2020-04-05 12:10 UTC
