### ISSUE TITLE
Windows and Mac builds are neglected

### ISSUE THREAD

**Issue by elpescado** [hydrogen-music/hydrogen#385] opened 2016-07-14 07:37 UTC
Windows and Mac builds often feel like second-class citizens - there are no stable builds available, development builds are often outdated.

This is unfortunate, as those are popular platforms, and especially among musicians, Linux is rarely platform of choice. This limits Hydrogen user base which in turn limits number of possible collaborators, and that is detrimental to Hydrogen development.

Hydrogen is one of nicest drum machines among both open source and commercial offerings but lack of good Windows and Mac builds is holding it back.

**Comment by mikotoiii** [comment] 2016-07-14 11:46
I'm not sure about the mac version, but I believe that most people compile it from source for that? 

The Windows version is a little bit old now, and there hasn't been a 64bit package generated and uploaded yet. I think that a portion of the problem is that the files are on sourceforge, which saves us the bandwidth since the Windows version according to sourceforge gets downloaded on average 1k times a day. This introduces limited availability in other people putting freshly compiled builds (ie, nightly, monthly, etc.) up.

It's definitely worth a discussion to see if there's a better way we can be doing things. @mauser had expressed some interest in redesigning the website, and I definitely have some ideas for that for starts.

**Comment by thijz** [comment] 2016-07-14 13:57
> This limits Hydrogen user base which in turn limits number of possible collaborators, and that is detrimental to Hydrogen developmen

i personally dont care too much about windows, but this statement is true ...

**Comment by Nat-Napoletano** [comment] 2016-07-14 17:06
Hi mikotoiii. Are you saying that (downloaded on average 1k times a day) X 60MB = 60GB per day is a problem? Some storage services look like they would do that for $5 per month. I'd pay for a year of that service just for one working copy of Hydrogen Windows.

**Comment by mikotoiii** [comment] 2016-07-14 17:30
I have no idea if it's a problem or not. I don't manage the website or
hosting or anything like that.

**Comment by mauser** [comment] 2016-07-14 18:10
@elpescado : The windows builds are now updated with every release (also with the development releases). This happens since @mikotoiii contributed his very helpful cross compilation scripts (which are fantastic, btw). So from my point of view, the situation on windows should be ok. Or is there still anything missing? Of course it is true that there are no builds for past version's, that's true.

On Mac OS X, the situation is a little bit different. There is no current disk image available, but it is quite easy to compile hydrogen and its dependencies on your own (based on macports/homebrew/whatever...).  I build occasional images on my own for prior version, but i had to stop that since my Macbook got too old and has no support for current versions of Mac OS X.

**Comment by mauser** [comment] 2016-07-14 18:14
> It's definitely worth a discussion to see if there's a better way we can be doing things. @mauser had expressed some interest in redesigning the website, and I definitely have some ideas for that for starts.

Yes! We definitely have to move away from the current one. I've started to migrate the content to Wordpress, but then the time was lacking to finish off everything.. At the moment i'm concentrating on getting 0.9.7 ready for rc1 , but after that, the website is the next thing to do..

**Comment by mikotoiii** [comment] 2016-08-29 21:06
Just updated the cross compile script #404. Should hopefully make getting Windows releases out quicker and easier.

**Comment by mauser** [comment] 2016-09-30 21:41
Hi,

i'm going to close this ticket now since recent packages for Windows and OS X are now available on SF.

**Closed by mauser** 2016-09-30 21:41 UTC
Labels: enhancement

**Comment by elpescado** [comment] 2016-10-03 06:36
Can we have them linked from Hydrogen web page?
