### ISSUE TITLE
Crashes upon attempting to start new file

### ISSUE THREAD

**Issue by Skywola** [hydrogen-music/hydrogen#445] opened 2016-12-01 01:11 UTC
I go to Project > New
Each time it crashes, saying Hydrogen stopped working.  Does not give any other info.
Running Windows 10.

**Comment by mauser** [comment] 2016-12-01 06:43
Hi @Skywola, 

which version of hydrogen are you using? 
have you already tried to re-install hydrogen? 
does it work to open existing sogs?

**Comment by Skywola** [comment] 2016-12-01 16:01
Version - 0.9.7-fcl [Oct 3 2016]

Have you already tried to re-install hydrogen?  No, but I will check for any newer version, and do this, and see what happens.
Does it work to open existing songs?   That works fine.




Shawn Irwin
4802 N 12TH ST  apt 1072,
PHOENIX, AZ 85014, USA
skywola@hotmail.com<mailto:skywola@hotmail.com>
www.tachufind.com<http://www.tachufind.com>



________________________________

**Comment by Skywola** [comment] 2016-12-01 16:57
Tried reinstall, same result, however . . . . the search that I did for the  download brought up the

32-bit version, on Sourceforge (not sure  why, as I was searching for 64-bit), but upon further

examination, I did find a 64-bit version.  Tried running that, it did not work because the interface

was all messed up.  So I re-tried the 32-bit version, and when I had it installed, I went to its

location, right clicked it, and chose compatibility settings, had Windows find the  setting,

clicked  OK when  it did, then re-tried starting a new file  and it worked fine.




Shawn Irwin
4802 N 12TH ST  apt 1072,
PHOENIX, AZ 85014, USA
skywola@hotmail.com<mailto:skywola@hotmail.com>
www.tachufind.com<http://www.tachufind.com>



________________________________

**Comment by mauser** [comment] 2016-12-07 21:31
Hi! 

Thanks for the feedback! The messed up interface was probably because your installation folder (especially the graphics folder) had images from a newer version of hydrogen in it. 
I'm going to close this ticket now since i can't reproduce the issue and it has resolved after re-installing.

**Closed by mauser** 2016-12-07 21:31 UTC
