### ISSUE TITLE
GMRockKit Missing Sample Layers

### ISSUE THREAD

**Issue by rock-hopper** [hydrogen-music/hydrogen#633] opened 2018-08-05 15:44 UTC
Hydrogen version *          : 1.0.0-beta
Operating system + version  : AVLinux 2018.6.25 (Debian Stretch)
Audio driver + version      : jack2 1.9.12

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The samples for the last 2 instruments of GMRockKit (Hat Semi-Open and Bell) are not loaded when the kit is loaded. The actual wav files are present in the data directory but the instrument layers appear empty in Hydrogen.

**Comment by mauser** [comment] 2018-08-12 14:49
Hi! 

this is a duplicate of #561 , which is already fixed in the master. But thanks for reporting!

**Comment by trebmuh** [comment] 2018-08-20 15:34
@rock-hopper any info if/when Hydrogen is launched from a terminal maybe? Can you please give us a step-by-step howto, then we'll be able to confirm that the issue is reproducible. Thanks.

PS: I'm reopening this issue, waiting for some more info then

**Comment by mauser** [comment] 2018-08-20 19:27
Hi! 

That's strange. If re-checked the filenames of the samples and the entries in the drumkit.xml and everything looks just fine. What exactly happens on your side? Is there anything special shown in the "Layer" Tab of the Instruments page? 

It should look a like this:
![layertab-2018-08-20 21-26-24](https://user-images.githubusercontent.com/202461/44361934-c542d380-a4bf-11e8-8960-da4b6b0f0967.png)

**Comment by rock-hopper** [comment] 2018-08-21 15:38
I simply cloned the repo ([latest commit](https://github.com/hydrogen-music/hydrogen/tree/fbe7a78fd829d6e4e0b3d30b03037224ac2e680a)), built and installed the deb package, and ran Hydrogen. Clicking on the layers tab reveals this:
![hydrogen](https://user-images.githubusercontent.com/4257276/44411780-39808400-a55f-11e8-89b1-8a652beb0712.png)

I tried manually editing the drumkit.xml file but any changes appear to be ignored. Does Hydrogen cache this file somewhere?

**Comment by mauser** [comment] 2018-08-21 16:45
Hi! 

I think i've found the problem. It's not in the drumkit but in the song file. If you open a new file, then Hydrogen loads the file EmpySong.h2song. 

This file has been saved with the old version of the drumkit which is missing those layers. Since the instruments are saved to the song file, the layers are empty. If you reload the drumkit (via Sound library ->  GMRockKit -> Load), everything works fine. 

I will save that the empty song again and commit it to the repo. 

By the way, this issue also helped me to discover to other bugs, so thanks a lot for your feedback!!

**Comment by mauser** [comment] 2018-08-21 20:25
The DefaultSong has been updated with def59f1fac57781b91af575bc13d4072cd539986. If you could do a `git pull`and try again...

**Comment by mauser** [comment] 2018-08-22 19:39
Hm, i'm not sure about his one.. I can't reproduce it at all on my systems. Are you sure that you've used "Project -> New" to create a new song?

If yes, is there anything interesting printed in the command line output of Hydrogen? If not, maybe with "hydrogen -VDebug"? The last command will give you a lot of output, but maybe there are some warnings concerning the samples.

**Comment by rock-hopper** [comment] 2018-08-23 16:11
Running "hydrogen -VDebug" reveals that Hydrogen is looking for the samples in ~/.hydrogen/data/drumkits/GMRockKit but the files are not there:
> (I) SongReader::readSong Reading /usr/share/hydrogen/data/DefaultSong.h2song
> (W) SongReader::readSong Trying to load a song created with a different version of hydrogen.
> (W) SongReader::readSong Song [/usr/share/hydrogen/data/DefaultSong.h2song] saved with version 1.0.0
> (W) LocalFileMng::processNode node 'playbackTrackFilename' is empty
> (W) LocalFileMng::readXmlString 	using default value : '' for node 'playbackTrackFilename'
> (I) Song::Song INIT 'Untitled Song'
> (E) Filesystem::check_permissions /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Softest.wav is not a file
> (E) Sample::load Unable to read /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Softest.wav
> (E) SongReader::readSong Error loading sample: /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Softest.wav not found
> (E) Filesystem::check_permissions /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Soft.wav is not a file
> (E) Sample::load Unable to read /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Soft.wav
> (E) SongReader::readSong Error loading sample: /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Soft.wav not found
> (E) Filesystem::check_permissions /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Med.wav is not a file
> (E) Sample::load Unable to read /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Med.wav
> (E) SongReader::readSong Error loading sample: /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Med.wav not found
> (E) Filesystem::check_permissions /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Hard.wav is not a file
> (E) Sample::load Unable to read /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Hard.wav
> (E) SongReader::readSong Error loading sample: /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Hard.wav not found
> (E) Filesystem::check_permissions /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Hardest.wav is not a file
> (E) Sample::load Unable to read /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Hardest.wav
> (E) SongReader::readSong Error loading sample: /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/HatSemiOpen-Hardest.wav not found
> (E) Filesystem::check_permissions /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Softest.wav is not a file
> (E) Sample::load Unable to read /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Softest.wav
> (E) SongReader::readSong Error loading sample: /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Softest.wav not found
> (E) Filesystem::check_permissions /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Soft.wav is not a file
> (E) Sample::load Unable to read /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Soft.wav
> (E) SongReader::readSong Error loading sample: /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Soft.wav not found
> (E) Filesystem::check_permissions /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Med.wav is not a file
> (E) Sample::load Unable to read /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Med.wav
> (E) SongReader::readSong Error loading sample: /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Med.wav not found
> (E) Filesystem::check_permissions /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Hard.wav is not a file
> (E) Sample::load Unable to read /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Hard.wav
> (E) SongReader::readSong Error loading sample: /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Hard.wav not found
> (E) Filesystem::check_permissions /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Hardest.wav is not a file
> (E) Sample::load Unable to read /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Hardest.wav
> (E) SongReader::readSong Error loading sample: /home/rockhopper/.hydrogen/data/drumkits/GMRockKit/Bell-Hardest.wav not found

When the "Hat Semi-Open" or "Bell" instrument is clicked:
>(W) Sampler::__render_note NULL sample for instrument Hat Semi-Open. Note velocity: 0.5
>(W) Sampler::__render_note NULL sample for instrument Bell. Note velocity: 0.4

**Comment by mauser** [comment] 2018-08-26 10:51
Hi! 

Do you have an older version of GMRockKit installed in /home/rockhopper/.hydrogen/data/drumkits/GMRockKit ?

**Comment by rock-hopper** [comment] 2018-08-27 18:49
You were right, an old version of the kit was installed there. Removing this solved the issue.

**Comment by trebmuh** [comment] 2018-08-27 19:06
Nice. Re-closing then.

**Closed by trebmuh** 2018-08-27 19:06 UTC
Labels: bug, more info needed

**Comment by mauser** [comment] 2018-08-27 20:35
Great, happy that this issue is finally resolved :smile:

**Comment by thijz** [comment] 2018-08-28 16:29
Maybe a drumkit version number should/could be added so this type of problem can be detected ?
