### ISSUE TITLE
Unable to load Ian Paice kit

### ISSUE THREAD

**Issue by musashihumar09** [hydrogen-music/hydrogen#1830] opened 2023-08-08 21:20 UTC
Hydrogen version *          : 1.2.1
Operating system + version  : Windows 10
Audio driver + version      :  NVIDIA

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When I try to load the Ian Paice kit from either the internal drumkit page or as a download from the Sourceforge page, I can't seem to get it to load into the user drumkits section. The other kits I have tried loading in do just fine, but that one in particular won't work.

**Comment by theGreatWhiteShark** [comment] 2023-08-09 17:38
Hey @musashihumar09 ,

That sounds strange. Could you set the log level to 'Debug' and paste in here what is reported while loading the kit?

Is the same happening with one of the other new kits, e.g. John Bonham?

**Comment by musashihumar09** [comment] 2023-08-14 20:09
Hi, @theGreatWhiteShark 

Here is what the log file said. From what I can see, the file is corrupted, even when loaded from the H2 SourceForge.

(E) PortAudioDriver::connect Can't use device '', using default stream[0m
(E) PortAudioDriver::connect Can't use device '', using default stream[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Pearl Kick]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Pearl Snare]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Sabian Hat Open]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Pearl Tom Floor]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Pearl Tom 2]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Pearl Tom 1]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Sabian Crash]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Paiste Ride]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Zildjian Splash]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Sabian Hat Closed]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Sabian Hat Pedal]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Pearl Side Stick]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Pearl Snare Rimshot]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Sabian Hat Semi-Open]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Hand Clap]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Sabian Hat Swish]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Sabian Hat Choke]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Cowbell]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Paiste Bell]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Paiste Ride Flink]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Sabian Crash Flink]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_path_search drumkit [] not found using lookup type [0][0m
(E) ::static QString H2Core::Filesystem::absolute_path(const QString&, bool) File [] not found[0m
(E) SoundLibraryDatabase::getDrumkit Unable determine drumkit path based on supplied string [][0m
(E) Drumkit::loadDoc [] is not valid drumkit folder[0m
(E) Legacy::loadInstrumentComponent Unable to load instrument component. Neither 'filename', 'instrumentComponent', nor 'layer' node found. Aborting.[0m
(E) Instrument::load_from Unable to load component for instrument [Zildjian Splash Choke]. Aborting.[0m
(E) InstrumentList::load_from Unable to load instrument [1]. The drumkit is corrupted. Skipping instrument[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [10] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [10] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [1] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [2] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [1] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [1] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [2] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [1] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [2] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [1] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [1] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [6] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [5] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [4] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [1] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [2] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [1] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [3] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [1] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [6] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [5] not found. Using empty instrument.[0m
(E) Note::map_instrument Instrument with ID [7] not found. Using empty instrument.[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) DrumPatternEditor::drawNote Instrument not found..skipping note[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m
(E) Filesystem::drumkit_list drumkit Ian Paice is not usable[0m

**Comment by theGreatWhiteShark** [comment] 2023-08-16 17:13
Ah, okay. It seems like the downloaded drumkit is bricked. Hydrogen can not even access it.

Is anything present in `.hydrogen/data/drumkits/Ian Paice ` in your home folder? In case there is a `drumkit.xml` file, could you post it here?

In any case, removing this folder and downloading  the kit again does hopefully fix your issue.

Is it possible you experience problems with the "The Black Pearl Kit" as well? (at least there are associated errors in the logs)

**Comment by musashihumar09** [comment] 2023-08-16 18:04
I tried redownloading. Same issue. Weirdly enough, the Black Pearl kit works just fine when I go to use it.

**Comment by theGreatWhiteShark** [comment] 2023-08-16 19:07
Okay. I think I can reproduce it. I try to come up with a patch soon

**Comment by musashihumar09** [comment] 2023-08-17 00:16
@theGreatWhiteShark Thank you! I appreciate that!

**Comment by theGreatWhiteShark** [comment] 2023-08-17 18:02
@musashihumar09 

Should be fixed. The kit folder contained a trailing whitespace. Because of that it was not possible to extract the downloaded .h2drumkit.

When removing the `Ian Paice` folder from `.hydrogen/data/drumkits/` and downloading the kit again, it should work fine. (you may have to press the "Update list" button in the online import dialog)

**Closed** 2023-09-09 19:53 UTC
Labels: bug, Windows, drumkit
