### ISSUE TITLE
Greek translation messages don't fit in gui

### ISSUE THREAD

**Issue by nikoss** [hydrogen-music/hydrogen#443] opened 2016-11-28 21:10 UTC
Greek language uses more syllables than English. As a result, sentences, phrases, words, can be 2 or even 3 times as long. This is a common problem with translations and GUI. 
But, it gets even worse, when applications use predefined sizes for windows, buttons, message frames, etc. Just like Hydrogen does.

I am attaching a few screen shots demonstrating the issue
![hydrogen_in_greek_001](https://cloud.githubusercontent.com/assets/4921343/20686032/9b620bb2-b5bf-11e6-967c-b42cf496ad75.jpg)
![hydrogen_in_greek_002](https://cloud.githubusercontent.com/assets/4921343/20686031/9b5d78fe-b5bf-11e6-8d92-ebafc3d4c6ef.jpg)
![hydrogen_in_greek_003](https://cloud.githubusercontent.com/assets/4921343/20686033/9b6bf942-b5bf-11e6-88d4-55a6ccdc838b.jpg)

**Comment by trebmuh** [comment] 2016-11-28 21:21
Duplicate of https://github.com/hydrogen-music/hydrogen/issues/397 .

**Comment by mauser** [comment] 2016-11-29 19:44
Hello @nikoss,

thanks for reporting those issue! I have attached your images to the issue #397 , since this issue collects similiar problems with hydrogen.

**Closed by mauser** 2016-11-29 19:44 UTC
