### ISSUE TITLE
Drumkits and GM standard

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#391] opened 2016-08-09 12:37 UTC
Putting that quickly here for it not to be lost in my mind:

**The story:**
There are frequently discussions on linuxmao.org about hydrogen. In some of those discussions, it's been pointed out that the fact the drumkits are not GM compatible is a big minus.
I've talked with some people lastly which could be interested in making some of the actual drumkits GM compatible which could be great.
For those who don't know about the GM standard, the most interesting thing with this this is that the instruments are all ordered in the same way trough the different drumkit, which allow you to check how does your pattern/song sound with different drumkits.

**Suggestion:**
I would find it very useful to have an indication in the sound library about the GM compatibility (or not) of the drumkit. I made a quick mock up just as a first idea for further discussion:

![hydrogen-gm-compatibility](https://cloud.githubusercontent.com/assets/8705846/17516461/bf312d58-5e3e-11e6-9a9b-936dfafa1e88.png)

I guess this would need a "GM compatibility" indication in the drumkit.xml file for each drumkit.

**Comment by mauser** [comment] 2016-08-10 20:36
Hi! 

Well, the discussion is not new and has been carried out here and on our mailing list as well. My soluation would be to introduce a midi mapping for midi input. 

Nevertheless, i would rate this ticket as an duplicate of #38 (with the addition of that nice image/concept). But in my opinion, it would be better to use a multi-purpose tagging system (not only limited to GM ability).

**Closed by mauser** 2016-08-10 20:36 UTC

**Comment by trebmuh** [comment] 2016-08-10 23:06
Thanks for pointing me the relevant issue number.
