### ISSUE TITLE
Programs closes when you try to add an instrument that is already on the pattern

### ISSUE THREAD

**Issue by jasane** [hydrogen-music/hydrogen#186] opened 2014-07-13 18:18 UTC
I know that the user must know what instruments it got on the pattern, but sometimes it occur to forget that they're there, for e.g. when you have much instruments, so when you try to add this instrument the programs exits and leave no message for the user or even save the project

**Comment by thijz** [comment] 2015-08-13 10:19
hi jasane
can you please retest this on the lates 0.9.7 github code and let us know if this issue is still present ?
thanks!
grtz
Thijs

**Comment by mauser** [comment] 2015-08-31 17:48
I'm closing this ticket now since it seems to be not possible to reproduce the problem..

**Closed by mauser** 2015-08-31 17:48 UTC
Labels: bug
