### ISSUE TITLE
Ambiguous shortcut detected - H2 1.0.0-'456b9c2'

### ISSUE THREAD

**Issue by jduemes** [hydrogen-music/hydrogen#453] opened 2016-12-11 18:52 UTC
As I try to activate the Director with the known Alt+D shortcut I get a H2 popup window with title "Ambiguous shortcut detected" with content:
The key sequence 'Alt+D' is ambiguous. Use 'Configure Shortcuts' from the 'Settings' menu to solve the ambiguity.
No action will be triggered,

Opening Director from the menu (View-> Director) works as expected.

Using Plasma5 on Arch Linux 4.8.12-3-ARCH #1 SMP PREEMPT Thu Dec 8 16:10:23 CET 2016 x86_64 GNU/Linux

**Comment by pvint** [comment] 2016-12-11 20:16
I can confirm this. 

Looks like this was introduced in commit 393617cc398fae606471a76d9c46e95387ba30be when the "Banks" menu was renamed to "Drumkits" and the ALT-D shortcut selected for that menu.

Should we maybe just change the shortcut for opening the Drumkits menu to Alt-K?

**Comment by mauser** [comment] 2016-12-11 22:17
Hi! 

Yes, Alt-K would be a good replacement if this is not currently used. I will replace that in the next days..

**Comment by pvint** [comment] 2016-12-11 22:40
I had a look and Alt+K is not used elsewhere - I merged the change. 1297e0977c3fcad5026b3b2dfb311cb6c5babc7b

Paul

**Closed by pvint** 2016-12-11 22:40 UTC
