### ISSUE TITLE
Exporting issue

### ISSUE THREAD

**Issue by LoveBodhi** [hydrogen-music/hydrogen#942] opened 2020-09-18 06:57 UTC
Hydrogen version *          : 1.0.1
Operating system + version  :  Windows 10
Audio driver + version      : PortAudio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When I exporting drum kit and re-install them, the sample data are corrupted!!!! (I choose 0.97 or higher)
Also, When I choose older format and re-install them, it won't appear at all!!!!

**Comment by trebmuh** [comment] 2020-09-22 12:32
I've been trying to reproduce your issue and am not able to do so yet.
@LoveBodhi please provide a precise step by step process in order for us to try to reproduce the issue.

**Comment by LoveBodhi** [comment] 2020-09-22 22:59
[Test1.zip](https://github.com/hydrogen-music/hydrogen/files/5264430/Test1.zip)
This is the issued file

**Comment by mauser** [comment] 2020-09-24 16:10
Hi! 

thanks for the file! It seems that there is some corrupt data at the end of the drumkit xml file. We had an issue like this in the past, but i don't remember if we found out where that corrupted data originates from. I'm going to investigate this.. Does this happen for every drumkit?

**Comment by LoveBodhi** [comment] 2020-09-24 22:59
No, other drum kits won't happen! (like FreePats Colombo Drum Kit)

**Comment by mauser** [comment] 2020-09-25 17:50
Just for the record: The same (or at least a very similiar) behavior appeared in #628. There was also additional data at the end of the drumkit.xml file.

**Comment by mauser** [comment] 2020-09-25 18:18
@LoveBodhi : Could you explain in more detail what you mean with "wav data corrupted"? Does that mean that Hydrogen changes the .wav file after the kit has been exported? If so, could you attach or link the original (uncorrupted) sample?

**Comment by LoveBodhi** [comment] 2020-09-25 22:33
[Kick.zip](https://github.com/hydrogen-music/hydrogen/files/5285654/Kick.zip)

This is uncorrupted wave file

**Comment by camtarn** [comment] 2021-01-30 19:55
Hydrogen version * : 1.0.1
Operating system + version : Windows 10 Home v2004 build 19041.746
Audio driver + version : Microsoft generic USB audio v10.0.19041.388, via PortAudio

Also having the same issue. My drumkit is attached:

[BFS drumming.zip](https://github.com/hydrogen-music/hydrogen/files/5898623/BFS.drumming.zip)

It looks like this issue causes #1138, in that importing a broken drumkit will cause the layer waveform viewer to crash Hydrogen when loading.

**Comment by camtarn** [comment] 2021-01-30 20:22
I can reproduce this by the following steps:

- Open Hydrogen
- Drumkits -> New, [OK]
- Layers -> Load Layer
- Select the attached sample
- Drumkits -> Save As
- Name: foo / Author: bar / License: baz / Information: qux / Image: [empty] / Image License: [empty]
- [Save]
- Drumkits -> Export
- Drumkit: foo
- [Export]

The exported drumkit is corrupted.

Attached sample:
[54014_domingus_DJEMBE_HI_1.zip](https://github.com/hydrogen-music/hydrogen/files/5898662/54014_domingus_DJEMBE_HI_1.zip)

**Comment by trebmuh** [comment] 2021-01-30 20:37
Can't reproduce here with a build from GIT master 1bacb4a on a LibraZiK-3 (Debian Buster based).

**Comment by cme** [comment] 2021-01-30 20:56
The problems here all seem to be experienced on Windows. I'll see if I can get my Windows cross-build environment working again to debug.

**Comment by cme** [comment] 2021-01-31 18:34
*headdesk*

https://sourceforge.net/p/mingw/bugs/1236/

**Comment by cme** [comment] 2021-02-01 21:35
Verified that @LoveBodhi 's Kick.wav sample is exactly the same issue (next byte after the correctly copied bytes was 0x1a EOF). Fix is on master, closing.

**Closed by cme** 2021-02-01 21:35 UTC
Labels: Windows

**Comment by mauser** [comment] 2021-04-16 22:17
@cme: Just stumbled upon this issue again and was very surprised to read about your solution. Nice find :)
