### ISSUE TITLE
Hydrogen crashes when deleting the first bank of an Instrument

### ISSUE THREAD

**Issue by blablack** [hydrogen-music/hydrogen#258] opened 2015-05-24 15:58 UTC
To reproduce this issue:
1. Have a drumkit with the main instruments bank called "One"
2. Have a second drumkit with the msian instruments bank called "Two"
3. Load the first drumkit
4. Drag&Drop an instrument from the second drumkit
5. When Hydrogen asks to merge or add the banks, chose merge
6. The drumkig in Hydrogen now has 2 banks: "One" and "Two"
7. Try and delete the bank "One", Hydrogen will crash

**Comment by blablack** [comment] 2015-06-07 20:30
Here is a patch that fixes that issue.

```
diff --git a/src/gui/src/InstrumentEditor/InstrumentEditor.cpp b/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
index 9accc1b..8de46fa 100644
--- a/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
+++ b/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
@@ -57,7 +57,6 @@ InstrumentEditor::InstrumentEditor( QWidget* pParent )
 	: QWidget( pParent )
 	, Object( __class_name )
 	, m_pInstrument( NULL )
-	, m_nSelectedComponent( 0 )
 	, m_nSelectedLayer( 0 )
 {
 	setFixedWidth( 290 );
@@ -419,12 +418,12 @@ InstrumentEditor::InstrumentEditor( QWidget* pParent )
 	m_pLayerPitchFineRotary->move( 199, 400 );
 	//~ Layer properties
 
-	m_nSelectedComponent = 0;
 	QStringList itemsCompo;
 	popCompo = new QMenu( this );
 	itemsCompo.clear();
 
 	std::vector<DrumkitComponent*>* compoList = Hydrogen::get_instance()->getSong()->get_components();
+	m_nSelectedComponent = Hydrogen::get_instance()->getSong()->get_components()->front()->get_id();
 	for (std::vector<DrumkitComponent*>::iterator it = compoList->begin() ; it != compoList->end(); ++it) {
 		DrumkitComponent* p_compo = *it;
 		if( !itemsCompo.contains( p_compo->get_name() ) )
@@ -1176,7 +1175,7 @@ void InstrumentEditor::compoChangeAddDelete(QAction* pAction)
 			}
 		}
 
-		m_nSelectedComponent = 0;
+		m_nSelectedComponent = Hydrogen::get_instance()->getSong()->get_components()->front()->get_id();
 
 		selectedInstrumentChangedEvent();
 		// this will force an update...
```

**Comment by mauser** [comment] 2015-06-14 10:39
Hi! 

Just tried to reproduce the bug, but i'm struggling with the terminology.. what is a 'bank'? It would be great if we could work out a little tutoria on the multi bank / component thing which we can place on the wiki

**Comment by thijz** [comment] 2015-06-14 11:33
+1 : short tutorial would be great

**Comment by blablack** [comment] 2015-06-22 09:08
Hi @mauser and @thijz I'll write a quick introduction and tutorial.
It's very straight forward.......once you know what's going on :)

FYI I had an other issue open regarding this:
https://github.com/hydrogen-music/hydrogen/issues/248

**Comment by blablack** [comment] 2015-06-29 16:31
I wrote a first shot of the tutorial here:
https://github.com/hydrogen-music/hydrogen/issues/248
Let me know what you think of it.

**Comment by mauser** [comment] 2015-06-29 20:44
Thanks for the tutorial, @blablack !
But some things are still unclear to me. First things is the terminology.. is a component the same as a bank? And i read sometime of "drumkit components" and "instrument components" in the source code.. Whats the reason behind that?

**Comment by blablack** [comment] 2015-06-30 12:38
'bank' and 'component' are interchangeable.
I started coded with 'component' thinking 'bank' was already used
somewehere.
From a user perspective it should say 'bank' everywhere.

The reason behind instrument and drumkit components:
- instrument components are used to store the instrument layer (instrument
-> component[] -> layers[]), the component id (that should match an id in
the drumkit component list) and the gain for that specific component for
that specific instrument
- the drumkit components are used to store the shared information regarding
that component: the id, the name, the volume/solo/mute as set in the
Hydrogen's mixer

**Comment by mauser** [comment] 2015-07-13 20:57
Hi Aurelien! 

I would be fine with the term "bank"..do you remember where it was already used? I don't think that we 'officially' used the term yet, at least not in the application. 

About 'merging and adding': I think i got the concepts now. At the moment i think that the "merge or add" dialog when dragging instruments to a new drumkit is a little bit "too much" for the avarage user. In my opinion the multiple banks feature should not affect the average user which uses only one bank. May this could be done by using "add" as an default and use a drag+some modifier (alt?) for merging instrument. Or maybe (in addition) a global option where you can specifiy the default behaviour.

**Comment by blablack** [comment] 2015-07-13 22:08
I don't remember exactly - I think I may have seen the term "bank" in
conversations on the LAU or in github tickets.

As for a default, I would say "merge" should be the default value.
Otherwise even for the average user, "add" will duplicate the bank every
time you drag an instrument even when there is only one bank.
After using multi bank for a few weeks now (with simple or multi banks
drumkits) I don't think I ever used "add" myself :-)

Let me know if there is anything I can do to help?

**Comment by mauser** [comment] 2015-07-26 12:54
Ok, i will create a new ticket for the "merge/add" stuff. Can someone re-test this issue? It should be fixed now..

**Closed** 2015-08-31 17:44 UTC
Labels: bug
