### ISSUE TITLE
sample leakage

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#958] opened 2020-10-19 11:19 UTC
Hydrogen version *          : b51508b3d6267df9c36e0e8fe0ae7de58f5fd972
Operating system + version  :  Linux
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If I open Hydrogen and change the drumkit from e.g. GMRock to BigMono I get

```
Objects map :                        class	constr   destr   alive
	[            AudioEngineInfoForm ]	     1	     1	     0
	[                       Director ]	     1	     1	     0
	[             FilesystemInfoForm ]	     1	     1	     0
	[              SimpleHTMLBrowser ]	     1	     1	     0
	[                    HydrogenApp ]	     1	     1	     0
	[               InstrumentEditor ]	     1	     1	     0
	[          InstrumentEditorPanel ]	     1	     1	     0
	[                   LayerPreview ]	     1	     1	     0
	[                    WaveDisplay ]	     2	     2	     0
	[                 InstrumentRack ]	     1	     1	     0
	[             LadspaFXProperties ]	     4	     4	     0
	[                       MainForm ]	     1	     1	     0
	[                          Mixer ]	     1	     1	     0
	[              DrumPatternEditor ]	     1	     1	     0
	[            NotePropertiesRuler ]	     5	     5	     0
	[    PatternEditorInstrumentList ]	     1	     1	     0
	[             PatternEditorPanel ]	     1	     1	     0
	[             PatternEditorRuler ]	     1	     1	     0
	[                PianoRollEditor ]	     1	     1	     0
	[                  PlayerControl ]	     1	     1	     0
	[                MetronomeWidget ]	     1	     1	     0
	[                 PlaylistDialog ]	     1	     1	     0
	[                     SongEditor ]	     1	     1	     0
	[          SongEditorPatternList ]	     1	     1	     0
	[        SongEditorPositionRuler ]	     1	     1	     0
	[                SongEditorPanel ]	     1	     1	     0
	[           SoundLibraryDatabase ]	     1	     1	     0
	[               SoundLibraryInfo ]	     1	     1	     0
	[              SoundLibraryPanel ]	     1	     1	     0
	[               SoundLibraryTree ]	     1	     1	     0
	[                   SplashScreen ]	     1	     1	     0
	[             AutomationPathView ]	     1	     1	     0
	[                         Button ]	   311	   311	     0
	[                  CpuLoadWidget ]	     1	     1	     0
	[                          Fader ]	    34	    34	     0
	[                    MasterFader ]	     1	     1	     0
	[                           Knob ]	   128	   128	     0
	[                       LCDDigit ]	   564	   564	     0
	[                     LCDDisplay ]	   114	   114	     0
	[                     LCDSpinBox ]	     1	     1	     0
	[                       LCDCombo ]	     5	     5	     0
	[             MidiActivityWidget ]	     1	     1	     0
	[                   PixmapWidget ]	   120	   120	     0
	[                         Rotary ]	    51	    51	     0
	[                 AlsaMidiDriver ]	     1	     1	     0
	[                JackAudioDriver ]	     1	     1	     0
	[                  TransportInfo ]	     1	     1	     0
	[                    AudioEngine ]	     1	     1	     0
	[       AutomationPathSerializer ]	     1	     1	     0
	[                           ADSR ]	  3048	  3048	     0
	[                 AutomationPath ]	     1	     1	     0
	[                        Drumkit ]	    50	    50	     0
	[               DrumkitComponent ]	    52	    52	     0
	[                     Instrument ]	  1512	  1512	     0
	[            InstrumentComponent ]	  1529	  1529	     0
	[                InstrumentLayer ]	  4918	  4918	     0
	[                 InstrumentList ]	    51	    51	     0
	[                           Note ]	    27	    27	     0
	[                        Pattern ]	     9	     9	     0
	[                    PatternList ]	    20	    20	     0
	[                       Playlist ]	     1	     1	     0
	[                         Sample ]	  5171	  4917	   254
	[                           Song ]	     1	     1	     0
	[                     SongReader ]	     1	     1	     0
	[           CoreActionController ]	     1	     1	     0
	[                     EventQueue ]	     1	     1	     0
	[                        Effects ]	     1	     1	     0
	[                   LadspaFXInfo ]	   436	   436	     0
	[                        XMLNode ]	 10780	 10780	     0
	[                         XMLDoc ]	    50	    50	     0
	[                       Hydrogen ]	     1	     1	     0
	[                   LocalFileMng ]	     1	     1	     0
	[                     MidiAction ]	  2524	  2524	     0
	[                  ActionManager ]	     1	     1	     0
	[                        MidiMap ]	     1	     1	     0
	[                      NsmClient ]	     1	     1	     0
	[                      OscServer ]	     1	     1	     0
	[                    Preferences ]	     1	     1	     0
	[               WindowProperties ]	    64	    64	     0
	[                        UIStyle ]	     1	     1	     0
	[                     H2RGBColor ]	    79	    79	     0
	[                        Sampler ]	     1	     1	     0
	[                          Synth ]	     1	     1	     0
	[                       Timeline ]	     1	     1	     0
Total :    254 objects.
```

**Comment by mauser** [comment] 2020-10-20 21:02
@theGreatWhiteShark : Ok, that one is a strange story :) It seems that this bug has been introduced by the two of us..


Technically, the problem is one of the copy constructors of `InstrumentLayer`: 

```
InstrumentLayer::InstrumentLayer( InstrumentLayer* other, Sample* sample ) : Object( __class_name ),
	__start_velocity( other->get_start_velocity() ),
	__end_velocity( other->get_end_velocity() ),
	__pitch( other->get_pitch() ),
	__gain( other->get_gain() ),
	__sample( new Sample( sample ) ) // <-- BUG
{
} 
```
The problem is that during the load of a drumkit the caller of this function assumes, that InstrumentLayer takes ownership of the memory to which `sample` points to. But that won't happen, because we're just using `sample` to create a new instance of the a sample. The Sample instance to which `sample` points won't be deleted. This happens in instrument.cpp:215, looking like this:

```
Sample* pSample = Sample::load( sample_path );
if ( pSample == nullptr ) {
     .....
} else {
 if ( is_live ) {
	AudioEngine::get_instance()->lock( RIGHT_HERE );
 }
 pMyComponent->set_layer( new InstrumentLayer( src_layer, pSample ), i );
 if ( is_live ) {
		AudioEngine::get_instance()->unlock();
}
```
The problematic `new`has been introduced by @theGreatWhiteShark  in ee2f8ef78fd0b57790d770e63dcf28c41d23dad4, which i've reverted during #764 but then reverted back again, so it was introduced again :) 

I don't have time today to make any intensive tests, so i don't know if taking back ee2f8ef78fd0b57790d770e63dcf28c41d23dad4 will introduce new problems. Will check later this week (also what the other callers of the copy constructor think about ownership :frowning_face: )

**Comment by theGreatWhiteShark** [comment] 2020-10-21 06:55
How about we use shared pointers for the Samples and proper container as std::vector within them? This way we don't have to deal with leakage of this type anymore. After all, the Samples do store the audio and are quite big. Leakage in there might be embarrassing.

I sort of already started doing this. But this will probably needs a while

**Comment by mauser** [comment] 2020-10-21 20:38
Hi! 

this should be fixed now with #963 (the memory leak and the segmentation fault during save). Please have a look, i hope that we talked about the same save-problem. 

About the smart pointers: I think that this is only half of the story. Even with smart pointers, you can end up in similar situations if there is a reference to the sample for too long. But yes, i would also think that this would help in a lot of situations in Hydrogen.

Another related issue is the general memory management in Hydrogen. We're loading ALL samples of the complete soundlibrary into memory, which is quite a waste. Those samples are only used for previews or to draw the illustrations of the sample. If we add an instrument to the song, it gets re-created and another sample is created. This could be much improved by using a lazy-loading approach for samples of all drumkits which are loaded as part of the soundlibrary. We have discussed this a long time ago (i guess this was even before we went to github), but i suppose memory usage was not a really a concern for many people after that time so it just went down in priority and has been forgotten..

**Closed** 2020-10-22 20:29 UTC
Labels: bug

**Comment by theGreatWhiteShark** [comment] 2020-10-22 21:06
>  We're loading ALL samples of the complete soundlibrary into memory, which is quite a waste.

We do? I thought all the `load_samples` flags in the various call for loading drumkits were set to false. With this in mind it is quite strange that `Hydrogen::loadDrumkit()` does not just link the Samples already loaded but, instead, only uses their paths to reload them ( https://github.com/hydrogen-music/hydrogen/blob/master/src/core/src/hydrogen.cpp#L3320 and https://github.com/hydrogen-music/hydrogen/blob/master/src/core/src/basics/instrument.cpp#L199 ). Is there a reason a Song needs it's own copy of the Samples?

You are right about the memory overhead and this could very well bring smaller/older computers to their knees for very large/many drumkits (e.g. a drumgizmo drumkit is >5GB and has to be held in RAM while playing. No chance to run such things with my hardware). On the other hand, this reminds me on a remark from @thijz in some issue (I can't find it right now) that Hydrogen is not able to smoothly (with no audible gap) switch between songs in a playlist. Having the samples of all songs in the playlist loaded into memory beforehand should make switching a lot faster.

Regarding the preview: e.g. Non-Timeline calculates a very coarse-grained version of every audio file once it is encountered and only uses this light-weighted version for display. I'm not quite sure how well this will work with such short samples as we do use but it may be an option.

**Comment by mauser** [comment] 2020-10-26 21:10
>We do? I thought all the load_samples flags in the various call for loading drumkits were set to false. With this in mind it >is quite strange that Hydrogen::loadDrumkit() does not just link the Samples already loaded but, instead, only uses their >paths to reload them ( https://github.com/hydrogen-music/hydrogen/blob/master/src/core/src/hydrogen.cpp#L3320 and >https://github.com/hydrogen-music/hydrogen/blob/master/src/core/src/basics/instrument.cpp#L199 ). 

You're absolutely right, we do this already correctly :smile:  This has slipped my attention completely or i forgot about it. I'm sorry for the confusion! If this would be the cause of @thijz issue, then we could introduce a "pre-fetch samples for playlist" option or such a thing quite easily.
