### ISSUE TITLE
Small issues with exporting to WAV as seperate tracks

### ISSUE THREAD

**Issue by JohnCPun** [hydrogen-music/hydrogen#462] opened 2016-12-26 12:26 UTC
Hello,

I have noticed two small issues while exporting to wave using 0.9.7-beta2 (so it might already be fixed in the current stable build).

**1) Tracks with forbidden OS characters in the name are not exported**

Steps:
Have at least one drums track with a forbidden character for the OS in its name (for example Tom 12").
Make a song where you use that track.
Go to project > export
Select export to WAV and "Export to seperate tracks".
Press Export
It will now export the tracks to wav files with a name following the format <song name><track name>

Expected:
All the tracks are exported. Tracks with forbidden characters in their name will have to characters removed/renamed in the name of the export file.

Observation:
The tracks without forbidden characters in their name willl export correctly. The tracks with them won't be exported.
When changing the name to remove the forbidden character they are correctly exported.

**2) Some track is exported twice, the second time being exported while muted**

Steps:
Make a song using multiple tracks
Go to project > export
Select export to WAV and "Export to seperate tracks".
Press Export
It will now export the tracks to wav files

Expected:
Every track is exported once.

Observation:
One track is exported at it's regular location (going through the tracks from top to bottom) and then once more at the end. Only the second time the resulting export file will be empty.
At first I wanted to say that it was the first track, as it was the first track in my song. But then I changed the position of the track to be second, and it is still exporting it twice. It is however doing this for all my songs. At first it didn't ask me if I wanted to override the existing track, but after moving it, it does.
I also noticed that if I decline to overwrite the existing file and leave the export dialog open and press "export" once again it will only export that track.
It is the Kick-track in a custom drumkit, that I compiled out of several other kits, so I'm not sure from which kit it originally came from.

**Comment by pvint** [comment] 2016-12-28 02:07
Hi @JohnCPun, thanks for the report, and tanks for describing it so well.

I should be able to have a look at these over the next few days.
Paul

**Comment by JohnCPun** [comment] 2016-12-28 14:57
Glad to be of help.
I know how important the tiniest detail can be with reproducing bugs, so I always try to be a complete as possible in my descriptions :)

**Comment by mauser** [comment] 2017-01-05 19:06
Problems during export are also mentioned here: http://hydrogen.popez.org/hcms/node/17246

**Comment by mauser** [comment] 2017-01-12 20:37
Here is another one: http://hydrogen.popez.org/hcms/node/17254

**Comment by mauser** [comment] 2017-01-12 20:40
@pvint : I was able to reproduce some of the problems here on my systems. I'm currently starting to look at the code and to fix smaller issues first.. That dialog needs a fresh-up for sure :) Just mention it if you already have done some changes locally or if you found any problems..

**Comment by pvint** [comment] 2017-01-15 19:35
@mauser : Like you I have reproduced some of these, but I haven't gone any further than that. I've been having trouble finding/making time for this lately. I should be able to have a look at the dialog soon, and I will keep you posted :)

**Comment by mauser** [comment] 2017-01-21 10:06
Hi! 

I've re-written  larger parts of the internal export handling now,  hope that i can test and upload it tomorrow. So hopefully mostt of the export problems should be gone then :)

**Comment by mauser** [comment] 2017-02-20 22:02
Hi! 

My fixes for the export dialog are now in the master branch. It would be great if someone could re-test the export issues..

**Comment by trebmuh** [comment] 2017-02-27 12:38
Added here: https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-1.0

@JohnCPun : did you have any time to rebuild Hydrogen from git master and to test if this (so well described, thanks for that!) issue is still here?

**Comment by JohnCPun** [comment] 2017-02-27 16:21
I will try to do it this weekend.

Unfortunately I will have to get it all figured out how to get anything from github, as while we do use GIT at my job (where I am a tester and developer), I actually have never pulled anything from github, leave along build it.

**Comment by JohnCPun** [comment] 2017-03-04 14:58
I feel really bad for asking for this, but I really don't have the time/energy to look into setting up a build environment and building Hydrogen.
Is there any possibility anybody could put up a build for me to download somewhere that I can just run?

**Comment by elpescado** [comment] 2017-03-04 18:31
What OS are you using?

**Comment by JohnCPun** [comment] 2017-03-05 02:37
Windows 7 64 bit, thanks :)

**Comment by mikotoiii** [comment] 2017-03-05 03:43
If no one gets one built before Monday, I'm sure I can get one compiled and
uploaded on Monday sometime.

On Mar 4, 2017 22:37, "JohnCPun" <notifications@github.com> wrote:

Windows 7 64 bit, thanks :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hydrogen-music/hydrogen/issues/462#issuecomment-284200576>,
or mute the thread

**Comment by trebmuh** [comment] 2018-03-25 10:55
Quoting @elpescado from https://github.com/hydrogen-music/hydrogen/issues/573 about the "forbidden OS characters" issue:

> Double quote character (") is one of [characters disallowed](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) in filenames on NTFS filesystem. That might be why your first track isn't exported.

and

> We shouldn't use those characters in file names. Hydrogen could replace them with some character (e.g. _) or simply drop. Question each platform should handle its disallowed characters, or maintain set of troublesome characters common for all platforms. The latter will help interoperability, I think (eg. prevents from exporting files on Linux that cannot be used on Windows).

**Comment by mauser** [comment] 2020-03-20 19:33
I'm closing this issue now, since it seems to be fixed. If that's not the case, just comment again.

**Closed by mauser** 2020-03-20 19:33 UTC
Labels: bug

**Comment by unicornsasfuel** [comment] 2020-10-28 22:03
OS: Windows 10
Hydrogen version: 1.0.1

There seems to have been a regression, I experienced this bug again. The Forzee Stereo Drumkit available through Online Import has double quote characters in its instrument names, and those with double quotes fail to export as separate tracks.

The workaround mentioned in this issue worked for me, too. Renaming the instruments to not include double quotes caused the export to work as expected.
