### ISSUE TITLE
FX not showing up in 9.7.

### ISSUE THREAD

**Issue by hobertuefer** [hydrogen-music/hydrogen#341] opened 2015-12-12 22:41 UTC

**Comment by mikotoiii** [comment] 2015-12-12 23:19
What OS are you running? Possible duplicate of #304?

**Comment by hobertuefer** [comment] 2015-12-13 12:49
Dear

the messag ref. #304 was also coming from me - i am running win 10 / win 
10 pro - i can only see the button "peak" in the mixer-view

krgds

heinz

Am 13.12.2015 um 00:19 schrieb mikotoiii:
>
> What OS are you running? Possible duplicate of #304 
> <https://github.com/hydrogen-music/hydrogen/issues/304>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hydrogen-music/hydrogen/issues/341#issuecomment-164201343>.
>

-- 
Heinz Obertüfer
Oberhofstrasse 20
CH-8265 Mammern
+41 79 532 56 60

**Comment by mikotoiii** [comment] 2015-12-16 19:03
I will have a look at this when I get a little time, i'm not sure exactly how the LADSPA plugins work on both Linux and Windows, as I don't use them. I can note that if it's doing things to the drumkit itself, it could be an issue with the path, which i have a ticket open for, and a PR for the fix waiting to be reviewed and merged.

**Comment by mauser** [comment] 2016-01-07 21:52
Hi,

after having a quick look at the build script, it seems to me that ladspa hasn't been recognized on my system when building the latest version of 0.9.7. It seems to be missing in the mxe environment.

@hobertuefer: This means that currently effects are not supported on windows, sorry! We will look further into the issue..

**Comment by hobertuefer** [comment] 2016-01-08 00:39
...as expected....anyway thx to this reply...however, hydrogen is an excellent tool, even using it live...if this issue would be solved...great...

**Comment by mikotoiii** [comment] 2016-01-08 01:31
I'll be having a look at the build script and the mxe and cmake stuff to
see if I can get it figured out here after the weekend.

**Comment by mauser** [comment] 2016-08-05 23:05
@hobertuefer : Could you see if [this](http://stuff.smoors.de/Hydrogen-0.9.7-win32-ladspaFix.exe) version of Hydrogen works for you? I think that i've re-enabled ladspa successfully..

**Comment by hobertuefer** [comment] 2016-08-06 11:04
Dear Sebastian

Many thanks, think i could work – now, where to get the effects and where (path?) to put them, that they show up and can be choosen

Krgds

Heinz

 

Von: Sebastian Moors [mailto:notifications@github.com] 
Gesendet: Samstag, 6. August 2016 01:05
An: hydrogen-music/hydrogen <hydrogen@noreply.github.com>
Cc: hobertuefer <hobertuefer@bluewin.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [hydrogen-music/hydrogen] FX not showing up in 9.7. (#341)

 

@hobertuefer <https://github.com/hobertuefer>  : Could you see if this <http://stuff.smoors.de/Hydrogen-0.9.7-win32-ladspaFix.exe>  version of Hydrogen works for you? I think that i've re-enabled ladspa successfully..

**Comment by mauser** [comment] 2016-08-06 12:13
Hi! 

You can use the Effects from [here](http://www.fosshub.com/Audacity.html/LADSPA_plugins-win-0.4.15.exe). Just install them where you want and create an environment variable called LADSPA_PATH which points to the directory which holds the plugins. 

Please be aware that not all plugins from that package seem to be working along with hydrogen.  

I suppose that there might be even more open-source ladspa plugins out there for windows. If you find some, let us know!

**Comment by hobertuefer** [comment] 2016-08-06 14:05
Hi

Works fines – great – 

Many thx

 

Von: Sebastian Moors [mailto:notifications@github.com] 
Gesendet: Samstag, 6. August 2016 14:13
An: hydrogen-music/hydrogen <hydrogen@noreply.github.com>
Cc: hobertuefer <hobertuefer@bluewin.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [hydrogen-music/hydrogen] FX not showing up in 9.7. (#341)

 

Hi! 

You can use the Effects from here <http://www.fosshub.com/Audacity.html/LADSPA_plugins-win-0.4.15.exe> . Just install them where you want and create an environment variable called LADSPA_PATH which points to the directory which holds the plugins. 

Please be aware that not all plugins from that package seem to be working along with hydrogen. 

I suppose that there might be even more open-source ladspa plugins out there for windows. If you find some, let us know!

**Closed** 2016-08-06 21:40 UTC

**Comment by herenciano243** [comment] 2016-08-14 09:20
Traduction
Désactiver la traduction instantanée
Hello,

I just read the post # 341 and I do not find the answer to my problem.

Indeed, the H version 0.9.6 that I had previously allowed to charge all LADSPA plugins found in the subfolder ... \ ladspaplugs the installation directory, and this under Windows 10.

Currently in version 0.9.7-beta 2 H and always under Windows 10, when I press the "edit" it nothing happens: it appears no windows inviting me to load a plugin.
 
It's a shame because the rest of the application works fine, and the improvements are excellent.

Thank you for reading me
Manuel Sanchez
