### ISSUE TITLE
Pb of size of the inteface

### ISSUE THREAD

**Issue by LaurentG91** [hydrogen-music/hydrogen#530] opened 2017-09-25 15:33 UTC
We can't resize the inteface according to screen definition.
It becomes unusable with a 3000x2000 screen resolution.
By using a zoom factor inside the preference apprearence, it could be solved.

Best regards
Laurent

**Comment by theGreatWhiteShark** [comment] 2021-11-05 08:51
Duplicate of #264 . Please have a look there for comments and solutions.

**Closed by theGreatWhiteShark** 2021-11-05 08:51 UTC
