### ISSUE TITLE
data/doc/ isn't present in the 1.0.0 release tarball

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#926] opened 2020-08-15 15:28 UTC
This is quite annoying for distribution purpose.

In https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0 , the https://github.com/hydrogen-music/hydrogen/archive/1.0.0.tar.gz doesn't contains the data/doc/ subfolder probably because it's a GIT module and the assets doesn't add it automatically.

This leads distributions such as Debian (and probably others) to [not distribute the doc with the software](https://salsa.debian.org/multimedia-team/hydrogen/-/blob/master/debian/hydrogen-doc.install).

I strongly suggest to release shortly a 1.0.1 with a .tar.gz assets including the data/doc/ module.

**Comment by mauser** [comment] 2020-08-17 20:53
Will be fixed with the next path release..

**Comment by trebmuh** [comment] 2020-09-03 18:58
As I can see your releasing a point version right now, I'm wildly pinging you here lord @mauser  !

**Comment by mauser** [comment] 2020-09-03 19:16
There is no way to put the content of the doc submodule in the generated tarballs by Github. This is a requested feature, but it does not seem possible at the moment. I will put a note on the release page and put the "enhanced" tarballs on SF. The Windows and Mac installers are fixed, they are shipped with the documentation.

**Comment by trebmuh** [comment] 2020-09-03 19:33
@mauser , you can attach any asset you want, see [sfizz](https://github.com/sfztools/sfizz/releases/tag/0.4.0) as an example.

**Comment by mauser** [comment] 2020-09-03 19:44
The problem is that i can't remove the tarballs from Github, which do not include the doc files. I've added an additional tarball to the release, SF includes now only the "fixed" tarball.

**Closed by mauser** 2020-09-03 19:44 UTC
Labels: bug, severity 1

**Comment by trebmuh** [comment] 2020-09-03 19:59
> The problem is that i can't remove the automatically created tarballs from Github, which do not include the doc files.

Yes, I know, this is very not optimal from github.

> I've added an additional tarball to the release, SF includes now only the "fixed" tarball.

Awesome :+1: Hopefully distro will get it right. Great idea for the "attention" note. I've put in in bold and added a parenthesis to stress the "packager point of view". Hope this is fine for you.

**Comment by trebmuh** [comment] 2020-09-04 19:06
Hi @mauser it looks like there are only the html files in the tarball's data/doc (in contrast with https://github.com/hydrogen-music/documentation where there are a lot of other files). Is that done on purpose?

**Comment by mauser** [comment] 2020-09-04 19:14
The tarball includes the generated documentation for 1.0. The other files are the sources files of the documentation, so in my opinion they are not needed in the tarball. For development purposes, you need the git repo, not the tarball.

**Comment by trebmuh** [comment] 2020-09-04 19:16
OK, make sense.
