### ISSUE TITLE
latest git version: error while loading shared libraries: libhydrogen-core-1.1.0.so

### ISSUE THREAD

**Issue by grammoboy2** [hydrogen-music/hydrogen#986] opened 2020-11-20 19:34 UTC
hydrogen 
hydrogen: error while loading shared libraries: libhydrogen-core-1.1.0.so: cannot open shared object file: No such file or directory

See:
https://github.com/hydrogen-music/hydrogen/issues/677#issuecomment-533369426

**Comment by cme** [comment] 2020-11-20 23:34
The library is dynamically linked. If you're doing `make install` to a system location, you'll need to run `ldconfig` afterwards. Or if installing to a non-standard location, you'll need to make sure $PREFIX/lib is on your LD_LIBRARY_PATH.

Maybe Hydrogen's `install` target should run `ldconfig`, but there doesn't seem to be any clear consensus about whether that's the job of a library's build system, a system packaging tool, or the user.

**Comment by mauser** [comment] 2020-11-28 18:15
Hi! 

As this is a duplicate of #677, and the discussion is already proceeding in that issue, i'm going to close this one.

**Closed by mauser** 2020-11-28 18:15 UTC
