### ISSUE TITLE
Hydrogen creates midifile which has an unchangeble tempo in Roland's drumtutor program

### ISSUE THREAD

**Issue by ThomasDrummer** [hydrogen-music/hydrogen#124] opened 2013-10-09 19:18 UTC
Hi,
I am a user of the Roland HD-1 drumtutor program. When I created a drumtrack on Hydrogen I saved it as a midifle and then imported in the HD-1 Drumtutor program. The tempo 120 BPM couldn't be changed then.  I solved it more or less by first importing the midifile in the program:  Midieditor and then without any change saving it with that program. After that I loaded the midifile in the Drum tutor program and the tempo could be changed. Also Audacity did the same trick with importing the midile and exporting it again. How is that possible?

**Comment by thijz** [comment] 2015-08-10 06:37
ThomasDrummer, xjjx, 
any update on this ?

grtz
Thijs

**Comment by xjjx** [comment] 2015-08-10 06:52
I still can't find this :( Cannot confirm or deny this issue. At least not yet.

**Comment by dawookieuk** [comment] 2015-09-24 20:27
I can confirm this behaviour. My setup is OS X 10.9 running hydrogen 0.9.6 and Roland Drum Tutor v 1.0.1.

I have forked a repo and modified the MIDI file writing in the 0.9.6 branch and the MIDI files now import into Roland Drum Tutor with the song name being extracted from the Song Properties dialog as displayed by the Project->Show Info menu item. The rest of the MIDI file is now much more compliant with the SMF standard but that may not bother you too much. ;-)

If some nice people could pull from my repo and test (currently the 0.9.6 branch, not master) and confirm a fix I'll generate a pull request.

**Comment by mauser** [comment] 2015-09-24 21:09
Hi! 

I can't test it (i don't own the software) but i had a quick look at your branch. If i understand your changes correctly, the problem was that in our files, there was no tempo meta track?

**Comment by dawookieuk** [comment] 2015-09-24 22:18
Hi. 

That's correct. The only meta event being written to the file was the Track Name event. 

From the perspective of SMF compliance there was another issue, which is that there was only a single track. From the reading I've done I've the last week or so, it appears that a format 1 SMF file should have the first track chunk in the file followed immediately by a copyright notice meta event then (in no particular order) Set Tempo, Time Signature and Track Name meta events.  There should then be a track end chunk, a new track chuck and then any note on/note off events which arevthen terminated with a track end chunk.

The master branch code was producing a single track chunk with Track Name as the only meta event, followed by note on/note off events and a track end chunk. This structure doesn't appear to be compliant with the Standard Midi Format documentation.

I think the Roland software should be more tolerant of  a missing Set Tempo meta event, it does follow the standard of assuming 120bpm but not allowing the tempo to be changed meant I was unable to create midi tracks that I could then practise to - if I could do that at 120bpm I wouldn't need to practise ;-)

My fork generates midi files that are fully SMF format 1 compliant - AFAIK, I'm by no means a midi expert but I've read a lot about the subject recently from a few sources. The generation of the note events is the original code as that was working perfectly well, I've only tidied up the structure and added the meta events  necessary to make the files SMF compliant so that any DAW should be able to import them cleanly.

I can supply dumps of the midi files that I've been using to explain further if that would help.

**Comment by dawookieuk** [comment] 2015-09-25 01:12
I just found a major issue with the MIDI file export in 0.9.7.

It appears that as well as the behaviour inherited from 0.9.6, the note events written to the MIDI file now ALL have a note number of 60 irrespective of the note in the song - which is great if you're a fan of Hi Bongo but not so good for everyone else. ;-)

Applying the files from the 0.9.6 branch of my fork appears to correct this behaviour so I've committed them and pushed up to the master branch of my fork. 

I will perform a test build on my Linux machine tomorrow to confirm.

**Comment by mauser** [comment] 2015-10-04 09:24
Hi! Is someone here who can re-rest this issue with the current git code?

**Comment by dawookieuk** [comment] 2015-10-15 11:32
I have also created a drum kit to match the note values of the Roland TD4 module, it may work with other members of the Roland TD range but I can't promise anything. I will be submitting it as a drum kit so that it can be downloaded from within the app but if anyone would like to test it in the mean time it can be found here:

https://github.com/dawookieuk/hydrogen-TD4-drumkit

I've tested it on my rig and it seems to work okay, if you do use it please let me know how you get on.

**Closed** 2016-03-26 16:00 UTC
Labels: bug, question
