### ISSUE TITLE
UI appearance on high resolution Screens

### ISSUE THREAD

**Issue by philloflynn** [hydrogen-music/hydrogen#757] opened 2019-08-21 10:27 UTC
Hydrogen version *          :
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The UI needs the facility to resize on high resolution screens like a surface pro 6 screen

**Comment by trebmuh** [comment] 2019-08-21 10:30
@philloflynn you didn't mention on which operating system (linux ? mac ? win ? other ?).

Plus, it might be a duplicate of #264 .

**Closed** 2019-08-21 10:31 UTC

**Comment by philloflynn** [comment] 2019-08-21 10:37
Yes. it is the same issue. I tried to find a duplicate bug report. BTW I'm using windows 10

**Comment by trebmuh** [comment] 2019-08-21 10:55
Please, report on the #264 thread issue then. Don't forget to add the OS and the Hydrogen version used.

**Comment by philloflynn** [comment] 2019-08-21 11:03
Is there any point? Genuine question. It seems you have to redo the ui for scaling which doesn't seem to be on the agenda

**Comment by trebmuh** [comment] 2019-08-21 11:57
Chances are devs are working on the most commented/desired issues.

**Comment by philloflynn** [comment] 2019-08-21 12:06
Ok. I'll Comment on the other thread. Thank you kindly!!
