### ISSUE TITLE
H2 Beta3 destroyed song files from previous H2 versions

### ISSUE THREAD

**Issue by Pirat61** [hydrogen-music/hydrogen#198] opened 2014-09-16 08:51 UTC
Hello

I switched from UbuntuStudio 12.04.4, 32 bit, with Hydrogen 0.9.6-SVN to UbuntuStudio 14.04.1, 64 bit, with Hydrogen 0.9.6-Beta3. New and clean installation, no upgrade.

When I load a song, previously made in H2-SVN into H2-Beta3, H2 play the song and everything works. But when I save this song (with or without changes), close it and load it again, every instrument is muted. Clicking on the button "Mute Instrument" does nothing. H2 play the song, but there is no sound.

So I compared the h2.song-xml.files in a text editor and found the following issues in the converted file (SVN > Beta3):

1) The tag "drumkit" is empty.

2) The entire section "layer" is missing.

H2 cannot find the sound library, because the converted xml file does not contain any path information.

**Comment by thijz** [comment] 2015-02-26 07:51
any update on this one ?

**Comment by thijz** [comment] 2015-09-25 11:13
bump :-)

**Comment by mauser** [comment] 2016-11-29 19:46
Hi,

i will close this ticket now since i can't reproduce this issue any more in newer version of hydrogen.

**Closed by mauser** 2016-11-29 19:46 UTC
Labels: bug
