### ISSUE TITLE
Transport out of sync in certain condition

### ISSUE THREAD

**Issue by drmanfred** [hydrogen-music/hydrogen#922] opened 2020-08-14 06:14 UTC
Hydrogen version *          : 1.0.0
Operating system + version  : ubuntu studio (Focal Fossa 20.04 LTS)
Audio driver + version      : Alsa 1.0.25

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I'm using Hydrogen in combination with Ardour (as time master) and Jack transport synchronization under Ubuntu Studio. Because I'm using live recorded audio files I need bpm speeds with decimal fractions and some speed changes in a song.
There is an issue concerning moving the play-head. When a song has a speed change then there is a small time offset between Ardour and Hydrogen after the play-head is set to a point behind the speed change.

**Comment by theGreatWhiteShark** [comment] 2020-08-17 09:28
Hey,

Just to be sure: within Hydrogen you (or the Auto driver) selected the Jack driver for audio output and synchronization? (since you put the Alsa driver in your description which does not support transport synchronization using Jack).

About the bug itself: does this only occur with changes from/to bpm speeds with decimal fractions?  Does the offset occur when the playhead passes the bpm marker and/or when transport is stopped, relocated into a region with different speed, and started again?

**Comment by theGreatWhiteShark** [comment] 2020-08-27 10:38
Okay, so it was actually me rewriting large parts of the code handling this synchronization since the release candidate. Does this bug only occur in Hydrogen version 1.0.0 or also earlier like in the [beta1 release](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0-beta1)?

Can you describe whats happening when Hydrogen and Ardour get out of sync? If there's just a tiny offset of the 1-2 buffersizes, the problem is with the changes in the Jack driver. If there is a relocation into a more far away part of the song, it's an issue with the Hydrogen timeline.

How come you used the BBT information to the relocation? I removed it a couple of months ago since it seemed to was the cause of a bunch of issues. The basic time unit in Jack is a frame and some clients do round the it's value to generate the tick in the BBT. They thus provide not the precise location of transport but something like the beginning of a pattern instead.

I did test the implementation with Non Timeline, Qtractor, and Ardour. But maybe I missed something. Could you recommend a stable version of Ardour? I just noted that Ardour provides an [excessive OSC interface](https://manual.ardour.org/using-control-surfaces/controlling-ardour-with-osc/osc-control/) maybe we can come up with an (at least semi) automated test to ensure both Hydrogen and Ardour will be in Sync in all future releases.

**Comment by drmanfred** [comment] 2020-08-29 12:17
I first noticed that something went wrong with the synchronization in 1.0.0-rc1. That was the version which was updated by ubuntu from the previous version 0.9.7. I assume that the behavior didn't change between 1.0.0-rc1 and 1.0.0. 
If you take for example a song in Ardour with the first 10 bars in 130 bpm and the next 10 bars in 100 bpm. Configure Ardour as JACK time master and Hydrogen with Jack transport in slave mode. Start playing. The speed change in bar 10 will be handled correct and the drums are in synch. Stop the song at bar 12 then relocate the play head to bar 16 and start playing. Then Hydrogen is about 2 bars behind completely out of synch. (Hydrogen plays somewhere in bar 15 while Ardour is in bar 17) 
In general Hydrogen is always out of synch after a relocation behind the first speed change.
I use Ardour in version 5.12.0 which is provided by ubuntu studio. But it is the same behavior with version 6.2.0 which I compiled from the sources.  
Because I'm not deep in the matter and no expert with Jack transport synchronization mechanism I thought it would be a good idea to use the BBT information.
At the moment I guess my solution is not really working always. I'm rather sure there are still some issues.
Unfortunately I have a lot other work to do the upcoming week. So I can investigate earliest a week later.
If you have a better suggestion for example using OSC I would appreciate it.

**Comment by theGreatWhiteShark** [comment] 2020-08-29 14:48
The Jack transport synchronization itself is pretty straight forward. Unfortunately, the interna of Hydrogen was not designed to properly work with the frame based concept of Jack which makes it a pain in the ass to get the synchronization with tempo changes right.

The other thing is Ardour itself. I took a look at 5.12.0 release and the Jack timebase implementation seems to be ... buggy. For one, Ardour is not considering tempo changes supplied by a different timebase master and, even more crucially, you can not check whether your Ardour is indeed the Jack timebase master or not. On Jack server-side it works as follows: as soon as a client asked to be the timebase master it gets this privilege while the former master will not be informed about this but instead Jack simple won't call its registered callback routine. Setting a check in Ardour -> Transport > Timebase Master makes Ardour the timebase master but as soon as you hit the J.MASTER button in Hydrogen Ardour is released from this duty with the check being still there.

Not quite sure whether the problem is on Hydrogen's side. But there seem to be a number of users working with this DAW so I will take a look too and try to make it work anyway.

**Comment by theGreatWhiteShark** [comment] 2020-10-02 21:06
@drmanfred you were perfectly right. One does need the BBT information in order to keep H2 in sync. Due to the rounding I described earlier it won't be absolute precise but sufficient.

Could you test the code in #922 and report whether this solves your problems.

What won't work - but this is quite an edge case - is a when relocating into a Hydrogen pattern which is larger than a bar in Ardour while having a change in measure in the middle of the measure (eg. 4/4 -> 3/4). I'm afraid there is nothing we can do except adjusting the length of the pattern since the Jack server does not provide the location of the change in measure and we can thus not calculate the corresponding transport location in Hydrogen.

**Comment by drmanfred** [comment] 2020-10-05 14:20
Hi @theGreatWhiteShark 
I made some tests with your fix922 branch. 
To start with the good news: The relocation bug in conjunction with speed changes did not occur with Ardour 5.12.0 any more. :-)
But when I made the same test with Ardour 6.2.0 there was still an issue:
The relocation works also with Ardour 6.2.0 when the transport is stopped, then relocated and started again. But relocation while the transport is rolling leads not to a proper relocation of Hydrogen when there is no speed change in between.
Thank you for leaving some debug-code "printState()" in the sources. So I called it at the end of your new function "relocateUsingBBT()" to see what's going on.
It looks like the data of the JackTransportPosition was not consistent in case a moving transport is relocated. While the frame (pPos->frame) holds the new position the BBT information shows still the old position. So Hydrogen keeps playing with a wrong position. In case when there was a speed change between the two positions the function "relocateUsingBBT()" is called a second time (in another cycle of "updateTransportInfo") when BBT date was updated. This time H2 gets the correct position.
I wonder how this could happen and I tried to compare Ardour 5.12.0 from the ubuntu package with the self-built Ardour 6.2.0.
The difference is that 5.12 first updates the BBT data and then the frame position, while 6.2 first updates the frame position and then the BBT data.
Unfortunately this second update (the BBT-data) was not detected by H2. Perhaps you have an idea.

Changing the measure would be the next challenge I would have looked at.
In my understanding and usage of Hydrogen I would always keep the pattern length accordingly to the bar measures in Ardour. I'd like to have the bar numbers and the pattern numbers in both position rulers consistent. So your edge case with different lengths of bars and patterns wouldn't bother me.
I made a short test with some changes in measure (4/4, 3/4, back in 4/4) but a relocation within the 3/4 part did not work properly. And sorry, right now a haven't made more analysis why it went wrong.

**Comment by theGreatWhiteShark** [comment] 2020-10-05 21:02
About your first observation: I experienced this in 5.12.0 as well. But only occasionally and not in a seemingly reproducible manner. I added a commit in the pull request that might fix this problem (sorry, can't test it right now). This should also cope with another open issue that the BBT information was not used for relocation directly after initializing the Jack audio driver.

Damn. You are right about the measures. But when thinking about it I don't see much we can do about it. The problem is the following:
H2 uses its patterns as what is Jack conceiving as bars. So, for relocation the goal of the algorithm is to convert Jack's bar into H2's pattern. When we relocate at a certain point, we can access - among others - the tempo and the measure at the particular position. But due to H2 internals we can not use the provided frame but only the BBT information as reference and thus the system with both tempo and measure being variable becomes under determined. We would either need to require one of them to be constant or all its previous changes known. To rephrase it: with measure and speed provided there is a very large set of previous tempo/measure combinations which would result in exactly the provided location. But since H2 changes the size of a tick / the number of ticks per beat upon a tempo change and thus effectively is rescaling time. This causes those combinations to have the same BBT information but a different frame.

Maybe I'm missing something but I don't see a simple solution for supporting both variable measures and speeds at the same time.

**Comment by drmanfred** [comment] 2020-10-06 16:43
Your last commit really fixes the problem of the "not consistent updates" of the play-head position of Ardour. Now relocation works with 5.12 and 6.2. Chapeau! Though the new function "compareAdjacentBBT" triggers the relocation function more often than necessary it's no problem except for songs that contain changes in measures. There it comes to false relocations even without user action.
As you explained in your last posting there is no way to solve the problem of relocating in a song with speed and measure changes in general without knowing the "history" of all the changes. I think you are completely right with that. To be determinate  one "degree of freedom" has to be sacrificed.
In my opinion one way would be to keep the bars (in Ardour) and the patterns in H2 consistent. As a musician I'm used to handle  scores and there all bars get numbers. And in an orchestra or a band when the musicians refer to a certain point of the song the say it in terms of numbers of bars (and beats). 
Under this condition it would be easily possible to solve that problem. I shrank your relocation function leaving out the part of counting the passed patterns because it did not work in a general way. I would propose to use the jack bar information for the pattern position. 
I used the relocateUsingBBT() function in the attached text file and it worked fine. 
[relocateUsingBBT.txt](https://github.com/hydrogen-music/hydrogen/files/5335339/relocateUsingBBT.txt)

**Comment by theGreatWhiteShark** [comment] 2020-10-07 19:59
> Though the new function "compareAdjacentBBT" triggers the relocation function more often than necessary it's no problem except for songs that contain changes in measures. There it comes to false relocations even without user action.

Hmm. I thought I had that tested. Could you describe the conditions the redundant call occur?

> In my opinion one way would be to keep the bars (in Ardour) and the patterns in H2 consistent. 

Definitely. And I'm certain there is no one on the development team who would think differently. But this is due to some core parts of the audio engine, which are around for almost 20 years by now.

In the long run (not 1.2 but maybe 1.3 or 1.4) I would like to tackle this code and replace it by a clean alternative. But this has most probably some major side effects and will take quite some time (incl. redesign of some GUI components).  Nothing I can pull off right now. But in the meantime we need a clean interim solution.

Just assuming all Hydrogen patterns will correspond to the measures in another application will be quite esoteric and confusing for a lot of users. One could make a new option in the menu with three choices: assume constant tempo, constant measure, identical bars. The user could decide for herself which one to pick. On the other hand, I'm not quite sure whether this is already overfitting the problem. One could also easily make Hydrogen the timebase master and be in control of distributing tempo, measure, and position information. 

By the way, H2 is distributing measure information based on the length of the current/next pattern. I totally forgot about this. So, Hydrogen does use fixed measures and disregard measures provided by Jack. But since H2 AFAIK can not handle measures/pattern length longer than the smallest pattern in a pattern group (a column in the GUI), this is not really another degree of freedom we can play with (without rewriting other core parts of the code).

**Comment by drmanfred** [comment] 2020-10-08 18:44
I simply let play one of my test songs. It starts with tempo 120 bpm at 4/4. In bar 4 the measure changes to 3/4. In bar 7 it goes back to 4/4. Later in bar 11 there is a speed change to 110.2 bpm. I let it play without any user interaction from the beginning to bar 13.
The screenshot gives you also the setting. Attached I provide you also the console output. I should say that I also added a printState(); statement at the end of the relocation function to get more information. Beside that I let your code exactly as you had it committed.
I let it play with both versions of Ardour. You see slight differences.
![screenshot](https://user-images.githubusercontent.com/69665765/95494595-75287300-099e-11eb-8e3a-a1af573c3ecf.jpg)
[console_output.txt](https://github.com/hydrogen-music/hydrogen/files/5350418/console_output.txt)
(Unfortunately the Infolog output is printed later than the stream output. I'm sure you know that.)
In this example H2 comes out of sync in the 3/4 part (Bars 4-6). The bar/pattern counting part of the relocation function calculates in lack of knowing the history with a wrong value in fBarConversion (due to ... beats_per_bar is 3 now).
So for my requirements it would be sufficient leaving this part out by using the jack bar information.
But definitely you will find some or more users that are unhappy with the constraint keeping bars and patterns consistent for some reason. And I also guess it is a bit overdone choosing in an option menu which constraint should be assumed.

I also thought about making Hydrogen the time master but this won't work with Ardour and I guess with no other sequencer which copes with midi and audio tracks. If they received an external speed change for the midi tracks they would have to recalculate the remaining time line in respect to the audio tracks. 
Only if I would give both (H2 and Ardour) a consistent set of speed changes it would work. But that is something I won't prefer.

**Comment by theGreatWhiteShark** [comment] 2020-10-09 20:23
> In this example H2 comes out of sync in the 3/4 part (Bars 4-6). The bar/pattern counting part of the relocation function calculates in lack of knowing the history with a wrong value in fBarConversion (due to ... beats_per_bar is 3 now).

Thanks for the analysis! I will take a look soon.

> But definitely you will find some or more users that are unhappy with the constraint keeping bars and patterns consistent for some reason.

I do this myself quite often. For a first draft of a song I make patterns double or quadruple their length to get a more concise representation in the editor.

>  And I also guess it is a bit overdone choosing in an option menu which constraint should be assumed.

Yeah, probably. But I think I will do it nevertheless. It's always a good idea to have a working solution before planning to write some code in some unspecified distant future. :D

> I also thought about making Hydrogen the time master but this won't work with Ardour and I guess with no other sequencer which copes with midi and audio tracks. If they received an external speed change for the midi tracks they would have to recalculate the remaining time line in respect to the audio tracks.
Only if I would give both (H2 and Ardour) a consistent set of speed changes it would work. But that is something I won't prefer.

I'm not into Ardour, so I may got it wrong. Is this an issue of Ardour not handling the tempo provided by the Jack timebase master properly or does the Hydrogen implementation do something wrong?

**Comment by theGreatWhiteShark** [comment] 2020-10-10 20:19
> There it comes to false relocations even without user action.

This should be fixed with the latest commit.

**Comment by drmanfred** [comment] 2020-10-11 13:35
Yes, with your last commit the transport rolls correctly through the 3/4 bar region as long as the user does not relocate. :-)

Well, if you think it is a good idea to let the user select which constraint he prefers, I won't persuade you to stop it.

> Is this an issue of Ardour not handling the tempo provided by the Jack timebase master properly or does the Hydrogen implementation do something wrong?

I see that Hydrogen does propagate the bpm information to JACK. It is displayed in the QjackCtl window. But Ardour does not react to this. I read the manual but I did not find it explicitly stated that Ardour listen to external bpm information. In the GUI of version 6.2 you can find one spot where you can choose which commands of the time master jack should be active (start/stop-, speed-changing- and locate- commands). So this makes the impression that there is a command interface between jack and Ardour.
In our case it makes no difference which of these commands are selected active or inactive the behavior is always the same.

**Comment by theGreatWhiteShark** [comment] 2020-10-12 20:58
I just pushed the changes. The default is set only different speeds in the timebase master (Ardour) and have the same measure all the way. Because of this the patterns in Hydrogen can be whatever. (exactly the state we had a couple of days ago). But now you can head to the preference menu and choose the "identical bars" option in a dropdown menu. When doing so H2 interprets the bar information provided by Jack as the corresponding number of patterns (which must match in length). Hope this solves your problem.

> But Ardour does not react to this.

IMHO it is very sad Paul Davis tries to make Ardour as monolithic and LV2-based as possible. As one of the main contributors to Jack1 it would probably be no hardship for him to properly implement Jack support.

**Comment by drmanfred** [comment] 2020-10-13 15:56
Hi theGreatWhiteShark,
yes, your latest commit works fine and I guess everybody can be happy with it. 
Thanks a lot for fixing the issue.

**Comment by theGreatWhiteShark** [comment] 2020-10-13 20:11
@drmanfred also thanks to you for reporting and testing!

**Closed** 2020-11-14 13:42 UTC
Labels: bug, confirmed
