### ISSUE TITLE
high-res icon not showing in KDE5

### ISSUE THREAD

**Issue by wolftune** [hydrogen-music/hydrogen#417] opened 2016-10-08 04:17 UTC
https://github.com/hydrogen-music/hydrogen/pull/163 added a high-res icon, but I'm using KXStudio repos in Neon and my icon is still the old blurry icon on my higher-res screen.

**Comment by elpescado** [comment] 2016-10-11 10:35
I added hires icons for Mac only in that pull request. I don't know how KDE uses icons, put I see that there are .pngs for up to 64 pixels only in repository.

**Comment by mauser** [comment] 2016-10-23 20:14
Hi! 

i don't know how KDE picks the icon which they are using and what file formats they are using.. We're shipping hydrogen with a .desktop file which points to the svg file (which is the source of @elpescado 's highres icon). In addition, i don't know whether KXStudio uses our .desktop file or if they're shipping a modified one. Could you get in contact with the KXStudio guys to see where the problem is?

**Comment by wolftune** [comment] 2016-10-23 20:36
Can I just ping @falkTX here?

**Comment by falkTX** [comment] 2016-10-23 20:40
hydrogen.desktop has Icon=h2-icon.
the svg file is in a random folder though, here is at /usr/share/hydrogen/data/img/gray/h2-icon.svg.
so the desktop file needs to point to that file instead of just "h2-icon", which I think leads to /usr/share/pixmaps/h2-icon.xpm

**Comment by Yvan-Masson** [comment] 2016-11-15 18:47
Hi,

I don't know much on this subject, but I take the liberty of adding two things:

- In Gnome, the 32x32 XPM icon is also used, which is too small even on non high-resolution screen
- KDE, Gnome and most other desktops follow the freedesktop icon theme specification (https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) which says that:
 - XPM files should be avoided if possible (I don't know if it is possible here)
 - support of SVG is optional

Hoping this help finding the right solution,
Yvan

**Comment by mauser** [comment] 2016-11-15 21:23
Hi! 

The .xpm image seems to be added by distributors, at least i can't find it in the hydrogen repository and it is not generated/installed by our cmake script. 

I have now added a line to our cmake script which installs the svg icon to /usr/share/pixmaps, so if you get a vanilla version of hydrogen from our git repository and run a "make install" you should see the svg image (if svg is supported..). This seems to work fine on my system..

**Comment by mauser** [comment] 2016-11-17 16:57
@wolftune : Could you test if this solution works for you? It is present in the latest git master branch.

**Comment by wolftune** [comment] 2016-11-17 22:59
Sorry, overloaded now and can't make time to build from source. Whenever @falkTX (or another KXStudio maintainer) packages the fix in KXStudio, I can report if it's working. Thanks for working on this, I hope to have more time eventually.

**Comment by elpescado** [comment] 2017-01-20 13:55
I was just randomly browsing Hydrogen sources and found something that may be relevant:

`setWindowIcon( QPixmap( Skin::getImagePath() + "/icon16.png" ) );`
(hydrogen/src/gui/src/MainForm.cpp:98)

**Comment by elpescado** [comment] 2017-03-10 12:17
PR #487 should fix this.

**Comment by mauser** [comment] 2017-06-03 11:32
The pull request has been merged, so i'm going to close this issue now..

**Closed by mauser** 2017-06-03 11:32 UTC
