### ISSUE TITLE
"Save changes in library"  clones samples

### ISSUE THREAD

**Issue by utkorose** [hydrogen-music/hydrogen#182] opened 2014-06-21 09:05 UTC
Library was created. If i mark "save changes in library" hydrogen clone samples in library. For example, "hiTom_OH_FF_12.wav" to "hiTom_OH_FF_12_1.wav", "hiTom_OH_FF_12_1_2.wav" and "hiTom_OH_FF_12_1_2_1.wav". 

Xubuntu 14.04. Latest version of Hydrogen.

Russian text:
Создана библиотека. Если пометить "Сохранить в библиотеку проделанные изменения", Hydrogen склонирует семплы в библиотеке. Например, "hiTom_OH_FF_12.wav" в "hiTom_OH_FF_12_1.wav", "hiTom_OH_FF_12_1_2.wav" и "hiTom_OH_FF_12_1_2_1.wav".

**Comment by thijz** [comment] 2015-02-20 12:23
hi utkorose
can you please retest this with the latest code ?

thanks
Thijs

**Comment by thijz** [comment] 2015-09-25 11:14
hi utkorose
any update on this ?

**Comment by thijz** [comment] 2015-09-29 19:43
cant reproduce this + no feedback from user > closing item

**Closed by thijz** 2015-09-29 19:43 UTC
Labels: bug
