### ISSUE TITLE
Fails to load samples from imported drumkit

### ISSUE THREAD

**Issue by jacek99** [hydrogen-music/hydrogen#858] opened 2020-05-03 19:11 UTC
Hydrogen version *          : 0.9.7
Operating system + version  : Ubuntu Studio (latest)
Audio driver + version      : qjackctl 0.5.0

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I used the Big Mono toolkit as a base and heavily customized it in a custom drumkit.
Saved it under a different name.

When I tried to load that drumkit into a different song...it loaded, but with all the samples/layers
empty. Just the instrument names, but no samples. If I looked at drumkit.xml, everything looks fine.

I've exported the entire drumkit (full 137MB). But when I re-imported it, the same thing happens: none of the samples get loaded.

![image](https://user-images.githubusercontent.com/36376/80923233-050b2680-8d48-11ea-81f4-2274f02ce09e.png)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by jacek99** [comment] 2020-05-03 19:13
see loaded drumkit, all instruments name are there, but everyone has no samples loaded

![image](https://user-images.githubusercontent.com/36376/80923269-3e439680-8d48-11ea-8627-7ba345a6cdb3.png)

**Comment by jacek99** [comment] 2020-05-03 19:15
folder with imported drumkit, all samples were imported

![image](https://user-images.githubusercontent.com/36376/80923324-95496b80-8d48-11ea-97d0-4d1e2bd3100f.png)

**Comment by jacek99** [comment] 2020-05-03 19:16
[drumkit.xml.tar.gz](https://github.com/hydrogen-music/hydrogen/files/4571430/drumkit.xml.tar.gz)

**Comment by jacek99** [comment] 2020-05-03 19:18
I see plenty of errors/warning if starting hydrogen from terminal:


Hydrogen 0.9.7 [Sep 19 2017]  [http://www.hydrogen-music.org]
Copyright 2002-2008 Alessandro Cominu
Copyright 2008-2016 The hydrogen development team

Hydrogen comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions. See the file COPYING for details

no more csLADSPA plugins
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/BigMono/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Brian%20Tama%20Superstar/drumkit.xml, at line 13, column 17: Element {http://www.hydrogen-music.org/drumkit}instrumentList is not defined in this scope.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Forzee%20Stereo%20Drumkit/drumkit.xml, at line 22, column 17: Element {http://www.hydrogen-music.org/drumkit}instrumentList is not defined in this scope.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Hammond_DPM48Kit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Ianhall_SampleSetKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Jovica_Tonic_fullKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Kawai_XD5Kit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Korg_DDD1Kit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Ltibbits_RockKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Lugenfalscher_BlitzboxKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/MatiasReccius_heavyMetalKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Moogish_fullKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/MXR_M185Kit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/RedRokkit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Roland_CR-1000Kit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Suonho_deconstructionKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/thanvannispen_industrisplodeKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Yamaha_Tg33_fullKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Yamaha_TX16WKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Yoursck+Vitriolix_TexturizerKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Zaraza%204%20Big%20Mono/drumkit.xml, at line 194, column 10: Content of element {http://www.hydrogen-music.org/drumkit}Decay does not match its type definition: Double content does not match the maxInclusive facet..
Error XSDError in file:///home/jacekf/.hydrogen/data/drumkits/Zaraza4_1/drumkit.xml, at line 103, column 10: Content of element {http://www.hydrogen-music.org/drumkit}Decay does not match its type definition: Double content does not match the maxInclusive facet..
Error XSDError in file:///usr/share/hydrogen/data/drumkits/Audiophob/drumkit.xml, at line 11, column 17: Element {http://www.hydrogen-music.org/drumkit}instrumentList is not defined in this scope.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/BJA_Pacific/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/circAfrique%20v4/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/ColomboAcousticDrumkit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/ElectricEmpireKit/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/ForzeeStereo/drumkit.xml, at line 22, column 17: Element {http://www.hydrogen-music.org/drumkit}instrumentList is not defined in this scope.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/Gimme%20A%20Hand%201.0/drumkit.xml, at line 11, column 17: Element {http://www.hydrogen-music.org/drumkit}instrumentList is not defined in this scope.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/HardElectro1/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/Millo-Drums_v.1/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/Millo_MultiLayered2/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/Millo_MultiLayered3/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/rumpf_kit_z01_h2/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/The%20Black%20Pearl%201.0/drumkit.xml, at line 11, column 17: Element {http://www.hydrogen-music.org/drumkit}instrumentList is not defined in this scope.
Error XSDError in file:///usr/share/hydrogen/data/drumkits/VariBreaks/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
(E) Effects::getPluginList Error loading the library. (/usr/lib/ladspa/lsp-plugins-ladspa.so)
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/BigMono/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Brian Tama Superstar/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Forzee Stereo Drumkit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Hammond_DPM48Kit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Ianhall_SampleSetKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Jovica_Tonic_fullKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Kawai_XD5Kit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Korg_DDD1Kit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Ltibbits_RockKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Lugenfalscher_BlitzboxKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/MatiasReccius_heavyMetalKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Moogish_fullKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/MXR_M185Kit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/RedRokkit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Roland_CR-1000Kit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Suonho_deconstructionKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/thanvannispen_industrisplodeKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Yamaha_Tg33_fullKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Yamaha_TX16WKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Yoursck+Vitriolix_TexturizerKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Zaraza 4 Big Mono/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /home/jacekf/.hydrogen/data/drumkits/Zaraza4_1/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/Audiophob/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/BJA_Pacific/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/circAfrique v4/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/ColomboAcousticDrumkit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/ElectricEmpireKit/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/ForzeeStereo/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/Gimme A Hand 1.0/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/HardElectro1/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/Millo-Drums_v.1/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/Millo_MultiLayered2/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/Millo_MultiLayered3/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/rumpf_kit_z01_h2/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/The Black Pearl 1.0/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/VariBreaks/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail

**Comment by trebmuh** [comment] 2020-05-03 21:43
Can you please try a 1.0.0-beta2 version and report if the issue is still there?

**Comment by jacek99** [comment] 2020-05-03 22:33
I tried installing the beta version from flathub...but it does seem to be compiled with JACK support? can't connec t to my Jack audio system

**Comment by jacek99** [comment] 2020-05-03 22:34
but it was able to load the drumkit, so that is good.

Is there anything I can do to the drumkit.xml to make it load in 0.9.7?

**Comment by trebmuh** [comment] 2020-05-03 23:36
I don't really know, that's been a lllooong of time since I've last use the 0.9.7 .
If that's all good with the beta, I'll consider this fixed and then closing it. Feel free to reopen it if you'd need.

**Closed by trebmuh** 2020-05-03 23:36 UTC
