### ISSUE TITLE
Midi exported file has an offset of +24 on Midi notes

### ISSUE THREAD

**Issue by jduemes** [hydrogen-music/hydrogen#411] opened 2016-09-26 20:17 UTC
_(Note: message edited by @trebmuh for better readability using the so-called "Insert code" tag)_

Hi Folks,

I manually edited the GMKit drumkit.xml file adding midi notes to the instruments. This way I connect (via Jack audio connection Kit) Hydrogen to a keyboard(1) and - as expected - Hydrogen sends the notes to the keyboard.

Now, if I export my song to a Midi file, open this Midi file with Drumstick MIDI Player connected to that same keyboard, it plays very different notes.

I did a test connecting Drumstick MIDI Player to QMidiRoute and QMidiRoute to the keyboard. Then changing the "Note Offset" option on QMidiRoute to -24. Surprise !!! It plays exactly the same notes as using Hydrogen. As I understand the Hydrogen Midi export is buggy.

(1) I used a keyboard but the same happens if I use another midi synthetizer like Qsynth (a Fluydsynth GUI).

```
$ hydrogen --version
0.9.7-'2a5e0cb'
```

```
$ uname -a
Linux myhostname 4.7.4-1-ARCH #1 SMP PREEMPT Thu Sep 15 15:24:29 CEST 2016 x86_64 GNU/Linux
```

Can somebody confirm this or point me an option or workaround to get a correct midi file ?

Cheers,
Jeff

**Comment by mauser** [comment] 2016-10-03 17:58
Hi! 

I've tried to reproduce the problem, but i couldn't find any issues with the export. Attached is a screenshot of a minimal example, just a fresh song with GMKit and the result in Bitwig. The same note is shown in Hydrogen and Bitwig. 

Nevertheless, the hydrogen midi out / midi export handling can be confusing: #307 has more informations about possible problems. Does your problem persist with every song (even new songs)`or is it affecting only some songs?  

![hydromidiexport](https://cloud.githubusercontent.com/assets/202461/19047612/f0d638f0-89a2-11e6-97a3-0f240843da37.png)

**Comment by elpescado** [comment] 2016-10-04 06:35
I vaguely remember encountering the same problem. As far as I remember, MIDI defines note 60 to middle C, but does not define "middle C", so different software use C3, C4 and C5 as "middle C" (C3 being most common), and I'm not sure whether Hydrogen is consistent with this.

**Comment by elpescado** [comment] 2016-10-04 06:58
Hydrogen seems to offset notes by 36 and 60 in different places (60 - 36 = 24 which explains two octave difference):

https://github.com/hydrogen-music/hydrogen/blob/725ace212ba2c2a617d6b1164639cd47900b9456/src/core/src/basics/instrument.cpp#L60
https://github.com/hydrogen-music/hydrogen/blob/df7be3df5a9227e9d9c382060ff701d794b351ba/src/core/src/IO/portmidi_driver.cpp#L268
https://github.com/hydrogen-music/hydrogen/blob/47e46e557e6905b2be5da2953a33d2c61d0af745/src/core/src/IO/jack_midi_driver.cpp#L423

**Comment by mauser** [comment] 2016-10-30 21:18
Hi,

in addition, the alsa midi driver sends out 'note on' midi messages for the first instrument with midi note 36 but 'note off' messages with mide note 60. What a mess..

**Comment by mauser** [comment] 2016-11-22 16:55
@jduemes (or everyone else who can reproduce the behaviour): Can you provide me with a midi file and the corresponding song file which shows the incorrect behaviour? 

I've tried to export different songs yesterday, but in all cases, the note values which are displayed in hydrogen matched the note values in the exported midi file. I've checked the note values in the midi file by looking at the output of the program midicsv.

**Comment by jduemes** [comment] 2016-12-05 18:39
Hi Mauser,

your are right about "the note values which are displayed in hydrogen matched the note values in the exported midi file". I see the same behavior here. The thing is, H2 does not "speaks" those values when talking to a sequencer. That sequencer can be the Fluydsynth software or a external hardware like a music keyboard.
[songs.zip](https://github.com/hydrogen-music/hydrogen/files/631970/songs.

**Comment by mauser** [comment] 2016-12-07 21:03
Hi Jeff!

Thanks, this makes it clear. Then the problem can be boiled down to the lines which @elpescado has identified earlier. So the core of the problem is in the code of hydrogen's midi drivers. 

Thanks for reporting the issue and sending the example song!

**Comment by jduemes** [comment] 2016-12-11 18:49
Hi Sebastian,

I'm happy to help. Is there a chance to link this issue to the release announcement of the version where this problem is already resolved ?

**Comment by jduemes** [comment] 2017-04-20 12:32
#450

**Comment by thijz** [comment] 2018-03-05 16:44
related to 
https://github.com/hydrogen-music/hydrogen/issues/63
https://github.com/hydrogen-music/hydrogen/wiki/MIDI-implementation

**Comment by trebmuh** [comment] 2018-03-23 18:31
Hi @jduemes : reading at this thread, it looks to me that @elpescado and @mauser fixed the issue with https://github.com/hydrogen-music/hydrogen/pull/450 .

Could you please re-test it with the beta release [1.0.0-beta1](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0-beta1) and report back here confirming us that the issue is gone?

Thanks.

**Comment by elpescado** [comment] 2018-10-14 19:10
I hope this is fixed by me in #666.

**Comment by jduemes** [comment] 2019-01-10 13:48
Using my Achlinux laptops I just tested Hydrogen 1.0.0.beta1.r3322.538eaeb9-1 using the GMRockKit as it comes with H2.
With a new project (Ctrl+N) without any adjustments but setting the channel of the instrument (Kick) to something different than 'off'.

My test setup is easy to reproduce. 
Using Jack:
- connect Hydrogen-midi TX port to Midi-Through capture port;
- Watch the Midi-Through playback port with "aseqdump -p <X:Y>"
Obs: to get X:Y of the Midi-Through playback port use "aseqdump -l"

Using only alsa: 
- Watch the Hydrogen midi out port with "aseqdump -p $(aseqdump -l | grep Hydrogen | cut -c-6)"

Using jack or alsa, Hydrogen still sends out the notes 2 octaves under what is defined for the instrument. An offset off -24. In my test with Kick which has the default note 36 aseqdump shows note 12.

```
$ aseqdump -p 14:0
Waiting for data. Press Ctrl+C to end.
Source  Event                  Ch  Data
  0:1   Port subscribed        129:0 -> 131:0
 14:0   Note off                8, note 12, velocity 0
 14:0   Note on                8, note 12, velocity 78
 14:0   Note off                8, note 12, velocity 0
```

Another observation: When SENDING midi notes to Hydrogen, GMRockKit seems to be very GM compatible, so to speak, and Hydrogen seems to work as expected. What I mean is, sending note 39 plays Hand Clap, sending 44 plays Hat Pedal and so on.

> I hope this is fixed by me in #666.

> Hi @jduemes : reading at this thread, it looks to me that @elpescado and @mauser fixed the issue with #450 .
> 
> Could you please re-test it with the beta release [1.0.0-beta1](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0-beta1) and report back here confirming us that the issue is gone?

**Comment by elpescado** [comment] 2019-01-10 21:32
Hi,

Unfortunately, fix #666 hasn't made its way to 1.0.0 branch yet.

Could you please test it on my branch? I'd appreciate if you post test results in that thread, as I need some help with testing.

**Comment by JosteinAndersen** [comment] 2019-01-11 07:38
Oh, sorry, I thought I reported it months ago! I have tested it and it works great as far as I can see. Well done and thank you very much for doing it. 

I wonder something: Why does one hit on an instrument trigger three events? It's a note off-on-off sequence.  A note off first will make or example cymbals sound unnatural in for example Superior Drummer or other players that strive to behave like real drummers. A note on event only should be sufficient in most cases.

**Comment by mauser** [comment] 2020-03-19 21:06
Hi,

the fix from @elpescado is since march 2019 part of our master branch and this problem seems to be solved from me (tested for alsa with aseqdump as shown above), so i think that the issue can be closed. 

If someone still experiences problems, just comment here and the issue will be re-opened.

**Closed by mauser** 2020-03-19 21:06 UTC
Labels: MIDI related, bug, confirmed, contains patch
