### ISSUE TITLE
Crash after editing SoundLibraryProperties

### ISSUE THREAD

**Issue by ojenning** [hydrogen-music/hydrogen#662] opened 2018-09-30 09:49 UTC
Hydrogen version *          : f66b29af2daaa0c00694e583bd4fd55b269d3211
Operating system + version  : Debian 9.5
Audio driver + version      : jack, version 1.9.11

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Start H2-beta from source path ./hydrogen -V Debug

Variant 1:
Load an user drum kit. The pattern editor works

Edit SoundLibrary Properties and save

Wait for ~40 seconds the window crashes.

```
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Snare Rimshot). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Hand Clap). 0 unused remain.
(I) SoundLibraryPropertiesDialog::SoundLibraryPropertiesDialog INIT
(I) Drumkit::save Saving drumkit Frame Drum 55cm - REMO into /home/ojenning/.hydrogen/data/drumkits/Frame Drum 55cm - REMO
(I) Drumkit::save_samples Saving drumkit Frame Drum 55cm - REMO samples into /home/ojenning/.hydrogen/data/drumkits/Frame Drum 55cm - REMO
(I) Drumkit::save_file Saving drumkit definition into /home/ojenning/.hydrogen/data/drumkits/Frame Drum 55cm - REMO/drumkit.xml
(I) SoundLibraryPropertiesDialog::~SoundLibraryPropertiesDialog DESTROY
Speicherzugriffsfehler
```

Variant2:
Load an user drum kit. The pattern editor works

Edit SoundLibrary Properties and save

Click in the pattern editor

```
(I) Hydrogen::loadDrumkit Frame Drum 55cm - REMO
(I) Hydrogen::loadDrumkit Loading instrument (0 of 3) [Frame Drum - Dum]
(I) Hydrogen::loadDrumkit Loading instrument (1 of 3) [Frame Drum - Tek [hard]]
(I) Hydrogen::loadDrumkit Loading instrument (2 of 3) [Frame Drum - Slap]
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Bell). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Hat Semi-Open). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Splash). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Ride 2). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Crash). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Ride). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Cowbell). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Hat Open). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Tom 1). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Hat Pedal). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Tom 2). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Hat Closed). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Floor Tom). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Snare Rimshot). 0 unused remain.
(I) Hydrogen::__kill_instruments Deleting unused instrument (XXX_Hand Clap). 0 unused remain.
(I) SoundLibraryPropertiesDialog::SoundLibraryPropertiesDialog INIT
(I) Drumkit::save Saving drumkit Frame Drum 55cm - REMO into /home/ojenning/.hydrogen/data/drumkits/Frame Drum 55cm - REMO
(I) Drumkit::save_samples Saving drumkit Frame Drum 55cm - REMO samples into /home/ojenning/.hydrogen/data/drumkits/Frame Drum 55cm - REMO
(I) Drumkit::save_file Saving drumkit definition into /home/ojenning/.hydrogen/data/drumkits/Frame Drum 55cm - REMO/drumkit.xml
(I) SoundLibraryPropertiesDialog::~SoundLibraryPropertiesDialog DESTROY
hydrogen: /home/ojenning/Development/hydrogen/src/core/src/sampler/sampler.cpp:292: bool H2Core::Sampler::__render_note(H2Core::Note*, unsigned int, H2Core::Song*): Zusicherung »pMainCompo« nicht erfüllt.
Abgebrochen
```
[build-info.txt](https://github.com/hydrogen-music/hydrogen/files/2431421/build-info.txt)

**Comment by ojenning** [comment] 2018-09-30 09:51
The changes to the properties are stored.

**Comment by mauser** [comment] 2018-09-30 19:10
Hi! 

Thanks for the report, i can reproduce the behaviour. The crash is happened when saving the song, triggered by the auto-save time (which is responsible for this strange timing..).

**Comment by theGreatWhiteShark** [comment] 2019-08-23 22:12
This bug get's fixed with #752

**Comment by trebmuh** [comment] 2019-08-24 06:34
@ojenning : can you try again and confirmed that this is fixed? Thank you.

**Comment by mauser** [comment] 2019-09-02 19:54
Re-tested with current master. The bug seems to be fixed by the fix from @theGreatWhiteShark.

**Closed by mauser** 2019-09-02 19:54 UTC
Labels: bug
